// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/_SimpleInfographicDataDrillingSupport","dojo/_base/declare dojo/on dojo/when dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/query esri/dijit/geoenrichment/FlowList ../grid/coreUtils/GridDataUtil ./dataDrilling/DataDrillingLibrary esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/WaitingUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes dojo/i18n!../../../../../nls/jsapi".split(" "),
function(k,m,n,r,l,C,w,x,t,y,p,z,D,u,v,A,q){q=q.geoenrichment.dijit.ReportPlayer.ReportPlayer;var B=k(t.itemRenderers.DefaultItemRenderer,{createLabelNode:!0,labelClass:"TrimWithEllipses esriGEReportPlayerTabs_label"});k=k(null,{drillingOptionsList:null,_drillingSections:null,_drillingSectionsButtons:null,postCreate:function(){var a=this;this.inherited(arguments);m(this.backToMainViewButton,"click",function(){a._setViewMode("viewMain",!0)})},_addDataDrillingHandlers:function(a,d){var b=this,e=y.getFieldInfo(d.getFieldCells()[0]);
if(p.hasDrillingOptions(e)){var h=l.create("div",{"class":"simpleInfographic_drillDataButton"},a.domNode);l.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonIcon esriGESpaceAfterBig"},h);l.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonLabel",innerHTML:q.drillForMoreData},h);m.once(this.domNode,"mouseover",function(){var c=[];a.getTables().forEach(function(a){c.push(a.domNode)});var b=z.intersectNodeBoxes(c,a.domNode);w.set(h,{left:b.x+"px",top:b.y+"px",width:b.w+
"px",height:b.h+"px",lineHeight:b.h+"px"})});m(h,"click",function(){b._selectedOptionsCache=b._selectedOptionsCache||{};var a=b._selectedOptionsCache[e.variableID]||0,d=b._setViewMode("viewDataDrilling",!0);b._loadDataDrillingOptionsList(e);b.drillingOptionsList.setSelectedIndex(a);b._loadDataDrillingView(e,b.drillingOptionsList.selectedItem.label,null,null,d)});this._drillingSectionsButtons.push({destroy:function(){l.destroy(h)}})}},_selectedOptionsCache:null,_createDrillingOptionsList:function(a){this._selectedOptionsCache=
this._selectedOptionsCache||{};var d=new t({"class":"simpleInfographic_drillingOptionsList",itemRenderer:new B});this.own(d);u.makePopup(d,this,a,{orient:["before","below"]});return d},_updateDrillingOptionsListWithFieldInfo:function(a,d){var b=this;a.onChange=function(){u.close(a);b._selectedOptionsCache[d.variableID]=a.selectedIndex;b._setViewMode("viewDataDrilling",!0);b._loadDataDrillingView(d,a.selectedItem.label)};var e=p.getDrillingOptions(d).map(function(a,b){return{label:a.name,value:b}});
a.setItems(e)},_loadDataDrillingOptionsList:function(a){this.drillingOptionsList||(this.drillingOptionsList=this._createDrillingOptionsList(this.drillingOptionsButton));this._updateDrillingOptionsListWithFieldInfo(this.drillingOptionsList,a);r[1<this.drillingOptionsList.items.length?"add":"remove"](this.domNode,"hasMultipleDrillingOptions")},_dataDrillingState:null,_loadDataDrillingView:function(a,d,b,e,h){var c=this;this._destroyDrillingSections();this._dataDrillingState={fieldInfo:a,optionName:d,
calcState:b,sectionVisualState:e};v.showProgress(c.waitingDiv);n(function(){var e=p.getDrillingOptionInfo(a,d,c.width,c.height,b),f=e.fieldsToEnrich;return n(f&&f.length&&c.viewModel.enrichFieldData(f),function(){return e})}(),function(b){var f,g={"class":"infographicContainer_Section"};g.initialWidth=c.width;g.json={type:A.DETAILS,stack:[b.tableJson]};g.viewModel=c.viewModel;g.themeContext=c.themeContext;g.theme=c.theme;g.tableClass="infographicContainerTable";g.hasFixedLayout=!1;g.isInfographicSection=
!0;g.calculationStatesGroup=b.calculationStatesGroup;g.onCalculationStateChanged=function(b){c._loadDataDrillingView(a,d,b,f.getVisualState())};n(h,function(){f=c.viewModel.layoutBuilder.createElement("section",g,c.drilledDataViewDiv);f.setResizedHeight(c.height);c._drillingSections.push(f);r[x(".sectionDynamicSettings_settingsButton",c.domNode)[0]?"add":"remove"](c.domNode,"hasChartSettingsButton");f.domNode.style.opacity="0.01";setTimeout(function(){f.setVisualState(e);f.domNode.style.opacity="";
v.removeProgress(c.waitingDiv)})})})},_getDataDrillingState:function(){return this._dataDrillingState},_setDataDrillingState:function(a){a&&this._loadDataDrillingView(a.fieldInfo,a.optionName,a.calcState,a.sectionVisualState)},_destroyDrillingSections:function(){this._drillingSections=this._drillingSections||[];this._drillingSections.forEach(function(a){a.destroy()});this._drillingSections.length=0;this.domNode&&l.empty(this.drilledDataViewDiv)},_destroyDrillingSectionsButtons:function(){this._drillingSectionsButtons=
this._drillingSectionsButtons||[];this._drillingSectionsButtons.forEach(function(a){a.destroy()});this._drillingSectionsButtons.length=0}});k.VIEW_MAIN="viewMain";k.VIEW_DATA_DRILLING="viewDataDrilling";return k});