// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/SimpleInfographic.html":'\x3cdiv class\x3d"esriGESimpleInfographic"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"mainViewDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"dataDrillingViewDiv" class\x3d"esriGEAbsoluteStretched"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"drilledDataViewDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"topToolbar" class\x3d"simpleInfographic_topToolbar"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"backToMainViewButton" class\x3d"simpleInfographic_backToMainViewButton"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"drillingOptionsButton" class\x3d"simpleInfographic_drillingOptionsButton"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"waitingDiv"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n\r\n\r\n'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/SimpleInfographic","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin ./_SimpleInfographicDataDrillingSupport esri/dijit/geoenrichment/_Invoke ./infographicUtils/InfographicLayoutResizer ./infographicUtils/InfographicJsonConversionUtil ./infographicUtils/InfographicThemeUtil ../supportClasses/TableUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/animation/Animator ../sections/supportClasses/InfographicValueController esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes dojo/text!../templates/SimpleInfographic.html".split(" "),
function(t,n,m,u,l,v,w,g,x,y,z,A,p,k,q,B,C,D){function r(a){return a&&a.shape&&a.shape.shapeJson.showAsBar}return t([v,w,x,g],{templateString:D,viewModel:null,themeContext:null,theme:null,isEditMode:!1,_sections:null,_currentInfographicJson:null,postCreate:function(){this.inherited(arguments);this._setViewMode(g.VIEW_MAIN)},_destroySections:function(){this._destroyDrillingSections();this._destroyDrillingSectionsButtons();this._sections=this._sections||[];this._sections.forEach(function(a){a.destroy()});
this._sections.length=0;this.domNode&&u.empty(this.mainViewDiv)},updateInfographic:function(a){this.domNode&&(this._currentInfographicJson=this._applyThemeToJson(a),this._doUpdateInfographic())},_doUpdateInfographic:function(){var a=this;if(this.domNode){this._destroySections();var b=this._currentInfographicJson;this.width&&this.height&&(b.style.width!=this.width||b.style.height!=this.height)&&y.resizeLayout(b,{w:this.width,h:this.height});var h=this.viewModel.getStaticInfographicDefaultStyles(this.theme||
this.themeContext);l.set(this.domNode,"backgroundColor",b.style.backgroundColor||h&&h.backgroundColor);l.set(this.domNode,{width:b.style.width+"px",height:b.style.height+"px"});this._preRender();this._renderHeader();this._renderVariableTables();this._sections.forEach(function(b){b.setViewMode(a.isEditMode?"edit":"previewValues")})}},_infographicViewController:null,_preRender:function(){this._infographicViewController=new B;var a=this._currentInfographicJson.variableTables.filter(r);this._infographicViewController.setVariableTables(a)},
_renderHeader:function(){var a=this._currentInfographicJson.header;this._createSection(p.getTableWidth(a),p.getTableHeight(a),[a],a.style,null,-1)},_renderVariableTables:function(){var a=this;this._currentInfographicJson.variableTables.forEach(function(b,h){var c=z.variableTableToNormalTables(b);a._createSection(b.style.width,b.style.height,c.tableJsons,b.style,b,h,c)})},_prepareSectionCreationParams:function(a,b){return null},_createSection:function(a,b,h,c,d,f,g){var e={"class":"infographicContainer_Section"};
e.initialWidth=a;e.json={type:C.DETAILS,stack:h};e.viewModel=this.viewModel;e.themeContext=this.themeContext;e.theme=this.theme;e.tableClass="infographicContainerTable";e.hasFixedLayout=!1;e.isInfographicSection=!0;e.infographicViewController=r(d)&&this._infographicViewController;n.mixin(e,this._prepareSectionCreationParams(d,-1===f));a=this.viewModel.layoutBuilder.createElement("section",e,this.mainViewDiv);a.setResizedHeight(b);l.set(a.domNode,{position:"absolute",left:(c.left||0)+"px",top:(c.spaceBefore||
c.top||0)+"px"});this._sections.push(a);this.viewModel.dynamicReportInfo&&"US"===this.viewModel.dynamicReportInfo.infographicOptions.countryID&&!this.viewModel.dynamicReportInfo.isFixedDataMode&&g&&this._addDataDrillingHandlers(a,a.getTables()[g.variableIndex]);return a},_mode:null,_setViewMode:function(a,b){function h(){a==g.VIEW_MAIN?(k.show(c.mainViewDiv),k.hide(c.dataDrillingViewDiv)):(k.show(c.dataDrillingViewDiv),k.hide(c.mainViewDiv));c._mode=a;m[a==g.VIEW_DATA_DRILLING?"add":"remove"](c.domNode,
"isDrillingData");m.remove(c.domNode,"isShowingAnimation")}var c=this;if(this._mode!=a){m.add(this.domNode,"isShowingAnimation");if(b){k.show([this.mainViewDiv,this.dataDrillingViewDiv]);var d=a==g.VIEW_DATA_DRILLING,f=l.get(this.domNode,"width");q.animateProperty({obj:this.mainViewDiv.style,duration:250,properties:{left:{start:d?0:-f,end:d?-f:0,addPx:!0},right:{start:d?0:f,end:d?f:0,addPx:!0}},endFunction:function(){h()}});return q.animateProperty({obj:this.dataDrillingViewDiv.style,duration:250,
properties:{left:{start:d?f:0,end:d?0:f,addPx:!0},right:{start:d?-f:0,end:d?0:-f,addPx:!0}}}).promise}h()}},getVisualState:function(){return{dataDrilling:this._mode==g.VIEW_DATA_DRILLING?this._getDataDrillingState():null}},setVisualState:function(a){a&&a.dataDrilling&&this._setDataDrillingState(a.dataDrilling)},_applyThemeToJson:function(a){var b=this.viewModel.getStaticInfographicDefaultStyles(this.theme||this.themeContext);return A.applyThemeSettingsToJson(a,b)},_undoThemeFromJson:function(a){return a},
width:null,height:null,resize:function(a,b){this.width&&this.height&&this._currentInfographicJson&&this._currentInfographicJson.style.width==a&&this._currentInfographicJson.style.height==b||(this.width=a,this.height=b,this.invoke("_doResize",50))},_doResize:function(){this._doUpdateInfographic()},toJson:function(){var a=n.clone(this._currentInfographicJson);return this._undoThemeFromJson(a)},destroy:function(){this._destroySections();this.inherited(arguments)}})});