// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/debounce":function(){define([],function(){return function(r,u){var k;return function(){k&&clearTimeout(k);var f=this,h=arguments;k=setTimeout(function(){r.apply(f,h)},u)}}})},"esri/numberUtils":function(){define(["dojo/has","dojo/number","dojo/i18n!dojo/cldr/nls/number","./kernel"],function(r,u,k,f){var h=function(f,n){return f-n},y={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(f){var n=String(f),l=n.match(y._reNumber);f={integer:0,fractional:0};l&&l[1]?(f.integer=l[1].split("").length,
f.fractional=l[3]?l[3].split("").length:0):-1<n.toLowerCase().indexOf("e")&&(l=n.split("e"),n=l[0],l=l[1],n&&l&&(n=Number(n),l=Number(l),(f=0<l)||(l=Math.abs(l)),n=y.getDigits(n),f?(n.integer+=l,n.fractional=l>n.fractional?0:n.fractional-l):(n.fractional+=l,n.integer=l>n.integer?1:n.integer-l),f=n));return f},getFixedNumbers:function(f,n){var l,k;l=Number(f.toFixed(n));l<f?k=l+1/Math.pow(10,n):(k=l,l-=1/Math.pow(10,n));l=Number(l.toFixed(n));k=Number(k.toFixed(n));return[l,k]},getPctChange:function(f,
k,l,h){var n={prev:null,next:null},x;null!=l&&(x=f-l,n.prev=Math.floor(Math.abs(100*(k-l-x)/x)));null!=h&&(x=h-f,n.next=Math.floor(Math.abs(100*(h-k-x)/x)));return n},round:function(f,k){var l=f.slice(0),n,x,r,u,z,d,w,H,p,t=k&&null!=k.tolerance?k.tolerance:2,F=k&&k.indexes,B=k&&null!=k.strictBounds?k.strictBounds:!1;if(F)F.sort(h);else for(F=[],d=0;d<l.length;d++)F.push(d);for(d=0;d<F.length;d++)if(p=F[d],n=l[p],x=0===p?null:l[p-1],r=p===l.length-1?null:l[p+1],u=y.getDigits(n),u=u.fractional){w=0;
for(H=!1;w<=u&&!H;)z=y.getFixedNumbers(n,w),z=B&&0===d?z[1]:z[0],H=y.hasMinimalChange(n,z,x,r,t),w++;H&&(l[p]=z)}return l},hasMinimalChange:function(f,k,l,h,r){f=y.getPctChange(f,k,l,h);k=null==f.prev||f.prev<=r;l=null==f.next||f.next<=r;return k&&l||f.prev+f.next<=2*r},_reAllZeros:new RegExp("\\"+k.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$","g"),format:function(f,k){k=k||{places:20,round:-1};var l=u.format(f,k);l&&(l=l.replace(y._reSomeZeros,"$1").replace(y._reAllZeros,""));return l}};r("extend-esri")&&
(f.numberUtils=y);return y})},"esri/renderers/utils":function(){define("dojo/_base/lang dojo/_base/array dojo/has dojo/date/locale ../kernel ../numberUtils ../Color dojo/i18n!../nls/jsapi dojo/i18n!dojo/cldr/nls/gregorian".split(" "),function(r,u,k,f,h,y,x,n,l){function P(d){return d&&u.map(d,function(d){return new x(d)})}function L(d,f,k){var p="";0===f?p=G.lt+" ":f===k&&(p=G.gt+" ");return p+d}var A={},G={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%"},z={millisecond:0,second:1,minute:2,
hour:3,day:4,month:5,year:6},d={millisecond:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},second:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},minute:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},hour:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},day:{selector:"date",dateOptions:{formatLength:"long"}},month:{selector:"date",dateOptions:{formatLength:"long"}},year:{selector:"date",dateOptions:{selector:"year"}}},
w={formatLength:"short",fullYear:!0},H={formatLength:"short"};r.mixin(A,{timelineDateFormatOptions:{selector:"date",dateOptions:{formatLength:"short",fullYear:!0}},formatDate:function(d,t){var p,k=[];null==d||d instanceof Date||(d=new Date(d));t=t||{};t=r.mixin({},t);var h=t.selector?t.selector.toLowerCase():null;p=!h||-1<h.indexOf("time");h=!h||-1<h.indexOf("date");p&&(t.timeOptions=t.timeOptions||H,t.timeOptions&&(t.timeOptions=r.mixin({},t.timeOptions),t.timeOptions.selector=t.timeOptions.selector||
"time",k.push(t.timeOptions)));h&&(t.dateOptions=t.dateOptions||w,t.dateOptions&&(t.dateOptions=r.mixin({},t.dateOptions),t.dateOptions.selector=t.dateOptions.selector||"date",k.push(t.dateOptions)));k&&k.length?(k=u.map(k,function(p){return f.format(d,p)}),p=1==k.length?k[0]:l["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(d,f){return k[f]})):p=f.format(d);return p},createColorStops:function(d){var f=d.values,p=d.colors,k=d.labelIndexes,l=d.isDate,h=d.dateFormatOptions;
d=[];return d=u.map(f,function(d,t){var n=null;if(!k||-1<u.indexOf(k,t)){var B;(B=l?A.formatDate(d,h):y.format(d))&&(n=L(B,t,f.length-1))}return{value:d,color:p[t],label:n}})},updateColorStops:function(d){var f=d.stops,p=d.changes,k=d.isDate,l=d.dateFormatOptions,h=[],n,r=u.map(f,function(d){return d.value});u.forEach(p,function(d){h.push(d.index);r[d.index]=d.value});n=y.round(r,{indexes:h});u.forEach(f,function(d,p){d.value=r[p];if(null!=d.label){var t,h=null;(t=k?A.formatDate(n[p],l):y.format(n[p]))&&
(h=L(t,p,f.length-1));d.label=h}})},createClassBreakLabel:function(d){var f=d.minValue,p=d.maxValue,k=d.isFirstBreak?"":G.gt+" ";d="percent-of-total"===d.normalizationType?G.pct:"";f=null==f?"":y.format(f);p=null==p?"":y.format(p);return k+f+d+" "+n.smartMapping.minToMax+" "+p+d},setLabelsForClassBreaks:function(d){var f=d.classBreaks,k=d.classificationMethod,p=d.normalizationType,l=[];f&&f.length&&("standard-deviation"===k?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):
d.round?(l.push(f[0].minValue),u.forEach(f,function(d){l.push(d.maxValue)}),l=y.round(l),u.forEach(f,function(d,f){d.label=A.createClassBreakLabel({minValue:0===f?l[0]:l[f],maxValue:l[f+1],isFirstBreak:0===f,normalizationType:p})})):u.forEach(f,function(d,f){d.label=A.createClassBreakLabel({minValue:d.minValue,maxValue:d.maxValue,isFirstBreak:0===f,normalizationType:p})}))},updateClassBreak:function(d){var f=d.classBreaks,k=d.normalizationType,p=d.change,l=p.index,p=p.value,h=-1,n=-1,r=f.length;"standard-deviation"===
d.classificationMethod?console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method."):(0===l?h=l:l===r?n=l-1:(n=l-1,h=l),-1<h&&h<r&&(d=f[h],d.minValue=p,d.label=A.createClassBreakLabel({minValue:d.minValue,maxValue:d.maxValue,isFirstBreak:0===h,normalizationType:k})),-1<n&&n<r&&(d=f[n],d.maxValue=p,d.label=A.createClassBreakLabel({minValue:d.minValue,maxValue:d.maxValue,isFirstBreak:0===n,normalizationType:k})))},calculateDateFormatInterval:function(d){var f,
k,l=d.length,p,h,n,r,w,x,y=Infinity,A;d=u.map(d,function(d){return new Date(d)});for(f=0;f<l-1;f++){p=d[f];n=[];w=Infinity;x="";for(k=f+1;k<l;k++)h=d[k],h=p.getFullYear()!==h.getFullYear()&&"year"||p.getMonth()!==h.getMonth()&&"month"||p.getDate()!==h.getDate()&&"day"||p.getHours()!==h.getHours()&&"hour"||p.getMinutes()!==h.getMinutes()&&"minute"||p.getSeconds()!==h.getSeconds()&&"second"||"millisecond",r=z[h],r<w&&(w=r,x=h),n.push(h);w<y&&(y=w,A=x)}return A},createUniqueValueLabel:function(f){var k=
f.value,l=f.fieldInfo,h=f.domain;f=f.dateFormatInterval;var p=String(k);(h=h&&h.codedValues?h.getName(k):null)?p=h:"number"===typeof k&&(p=l&&"esriFieldTypeDate"===l.type?A.formatDate(k,f&&d[f]):y.format(k));return p},cloneColorInfo:function(d){var f;d&&(f=r.mixin({},d),f.colors=P(f.colors),f.stops=f.stops&&u.map(f.stops,function(d){d=r.mixin({},d);d.color&&(d.color=new x(d.color));return d}),f.legendOptions&&(f.legendOptions=r.mixin({},f.legendOptions)));return f},cloneOpacityInfo:function(d){var f;
if(d){f=r.mixin({},d);if(d=f.opacityValues)f.opacityValues=d.slice(0);if(d=f.stops)f.stops=u.map(d,function(d){return r.mixin({},d)});if(d=f.legendOptions)f.legendOptions=r.mixin({},d)}return f},cloneSizeInfo:function(d){var f;d&&(f=r.mixin({},d),f.stops&&(f.stops=u.map(f.stops,function(d){return r.mixin({},d)})),(d=f.minSize)&&"object"===typeof d&&(f.minSize=A.cloneSizeInfo(d)),(d=f.maxSize)&&"object"===typeof d&&(f.maxSize=A.cloneSizeInfo(d)),d=f.legendOptions)&&(f.legendOptions=r.mixin({},d),d=
d.customValues)&&(f.legendOptions.customValues=d.slice(0));return f}});k("extend-esri")&&r.setObject("renderer.utils",A,h);return A})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/debounce dojo/has dojo/sniff dojo/Deferred dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-class dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/utils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/SimpleLineSymbol ../symbols/jsonUtils ../renderers/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(r,
u,k,f,h,y,x,n,l,P,L,A,G,z,d,w,H,p,t,F,B,T,Q,O,J,E,M,Y,Z,aa,ba,ca,da,R,ea,U,V,N,W,X,S){var I=u([X,p],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,_preserveCacheOnDestroy:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,transparencyRampColor:new x([64,64,64]),defaultText:"Aa",sizeRampLightColor:new x([255,255,255]),sizeRampDarkColor:new x([128,128,128]),layerConnects:[],gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",
gt:"\x3e"},_ieTimer:100,_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(a,b){k.mixin(this,S.widgets.legend);this._i18n=S.widgets.legend;a=a||{};a.map?b?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===a.respectVisibility?!1:!0,this._preserveCacheOnDestroy=a.preserveCacheOnDestroy?!0:!1,this.arrangement=a.arrangement===I.ALIGN_RIGHT?I.ALIGN_RIGHT:I.ALIGN_LEFT,this.arrangement===I.ALIGN_RIGHT&&
(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[],this.hideLayersInLegend={},this.refresh=n(this.refresh,0)):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],b,c;for(b=0;b<a.length;b+=1)c=a[b],r.locale&&-1!==r.locale.indexOf(c)&&(-1!==r.locale.indexOf("-")?-1!==r.locale.indexOf(c+
"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},startup:function(){this.inherited(arguments);this._initialize();9>l("ie")&&(this._repaintItems=k.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();
this._removeCachedLegendResponses();this._removeHoverHandlers();this.inherited(arguments)},_removeCachedLegendResponses:function(){this._preserveCacheOnDestroy||f.forEach(this.layers,function(a){delete a.legendResponse})},refresh:function(a){if(this.domNode){a?(this.layerInfos=a,this.layers=[],f.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=
a.hideLayers,this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=null);for(a=this.domNode.children.length-1;0<=a;a--)d.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&
(this.layers=[],f.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=a.hideLayers,this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=
!0;this.layers=[];var a=[],b=[];f.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);var g;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==c.declaredClass&&(g=c.getLayers(),f.forEach(g,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(g=c.getFeatureLayers(),f.forEach(g,function(a){b.push(a.id)},this))},this);f.forEach(this.map.graphicsLayerIds,function(c){var g=
this.map.getLayer(c);-1==f.indexOf(a,c)&&-1==f.indexOf(b,c)&&this._isSupportedLayerType(g)&&this._isLayerDrawingEnabled(g)&&(g.arcgisProps&&g.arcgisProps.title&&(g._titleForLegend=g.arcgisProps.title),this.layers.push(g))},this)}this._createLegend()},_isLayerDrawingEnabled:function(a){return a&&(a._params&&a._params.drawMode||a.isFeatureReductionActive&&a.isFeatureReductionActive())},_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=h.connect(this.map,
"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=h.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=h.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=h.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),f.forEach(this.layers,function(a){var b={};b.oarcConnect=h.connect(a,"onFeatureReductionRendererChange",this,"_refreshLayers");b.oaicConnect=h.connect(a,"onFeatureReductionChange",this,"_refreshLayers");
b.ovcConnect=h.connect(a,"onVisibilityChange",this,"_refreshLayers");b.oocConnect=h.connect(a,"onOpacityChange",this,"_refreshLayers");b.oscConnect=h.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(b.odcConnect=h.connect(a,"_onDynamicLayersChange",k.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(b.oirConnect=h.connect(a,"onRenderingChange",k.partial(this._updateImageServiceLayers,
this,a)),b.oivrConnect=h.connect(a,"onRendererChange",k.partial(this._updateImageServiceLayers,this,a)));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(b.oivrConnect=h.connect(a,"onRendererChange",k.hitch(this,"_refreshLayers")));this.layerConnects[a.id]=b},this))},_deactivate:function(){this._ozeConnect&&h.disconnect(this._ozeConnect);this._olaConnect&&h.disconnect(this._olaConnect);this._olroConnect&&h.disconnect(this._olroConnect);this._olrConnect&&h.disconnect(this._olrConnect);
f.forEach(this.layers,function(a){a=this.layerConnects[a.id]||{};a.oarcConnect&&h.disconnect(a.oarcConnect);a.oaicConnect&&h.disconnect(a.oaicConnect);a.ovcConnect&&h.disconnect(a.ovcConnect);a.oocConnect&&h.disconnect(a.oocConnect);a.oscConnect&&h.disconnect(a.oscConnect);a.odcConnect&&h.disconnect(a.odcConnect);a.oirConnect&&h.disconnect(a.oirConnect);a.oivrConnect&&h.disconnect(a.oivrConnect)},this);this.layerConnects=[]},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},
_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];f.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);f.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this._isLayerDrawingEnabled(a)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=
!1,b=!1;w.set(this.domNode,"position","relative");d.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var c=[];f.forEach(this.layers,function(e){if("esri.layers.KMLLayer"==e.declaredClass||"esri.layers.GeoRSSLayer"==e.declaredClass){var g;e.loaded?("esri.layers.KMLLayer"==e.declaredClass?g=e.getLayers():"esri.layers.GeoRSSLayer"==e.declaredClass&&(g=e.getFeatureLayers(),this.hideLayersInLegend[e.id]&&(g=f.filter(g,function(a){return-1==
f.indexOf(this.hideLayersInLegend[e.id],a.id)},this))),f.forEach(g,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&e._titleForLegend&&(a._titleForLegend=e._titleForLegend+" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_areas),c.push(a))},this)):h.connect(e,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===
e.declaredClass)if(!e.loaded)h.connect(e,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}));else{if((!this._respectVisibility||this._respectVisibility&&e.visible)&&0<e.layerInfos.length&&f.some(e.layerInfos,function(a){return a.legendURL})){var C=!1;f.forEach(e.layerInfos,function(b){if(b.legendURL&&-1<f.indexOf(e.visibleLayers,b.name)){C||(d.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(e._titleForLegend||e.name||e.id)+"\x3c/span\x3e"},this.domNode),C=!0);
var c;b=b.legendURL;if(e.customParameters||e.customLayerParameters){var g=k.clone(e.customParameters||{});k.mixin(g,e.customLayerParameters||{});for(c in g)b+=(-1===b.indexOf("?")?"?":"\x26")+c+"\x3d"+g[c]}d.create("div",{innerHTML:"\x3cimg src\x3d'"+b+"'/\x3e"},this.domNode);a=!0}},this)}}else"esri.layers.WFSLayer"!==e.declaredClass||e.renderer?c.push(e):(g=d.create("div",{id:this.id+"_"+e.id,"class":"esriLegendService"}),d.create("span",{innerHTML:this._getServiceTitle(e),"class":"esriLegendServiceLabel"},
d.create("td",{align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},g))))),d.place(g,this.id,"first"),g=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),g=d.create("tbody",{},g),"esriGeometryComplex"===e.geometryType?(this._buildRow_Renderer(e,e._pointSymbol,null,this.NLS_points,null,g),this._buildRow_Renderer(e,e._lineSymbol,null,this.NLS_lines,null,g),this._buildRow_Renderer(e,e._polygonSymbol,null,this.NLS_areas,null,g)):
"esriGeometryPoint"===e.geometryType?this._buildRow_Renderer(e,e._pointSymbol,null,"",null,g):"esriGeometryPolyline"===e.geometryType?this._buildRow_Renderer(e,e._lineSymbol,null,"",null,g):"esriGeometryPolygon"===e.geometryType&&this._buildRow_Renderer(e,e._polygonSymbol,null,"",null,g),b=!0)},this);var g=[];f.forEach(c,function(a){if(!a.loaded)var b=h.connect(a,"onLoad",this,function(a){h.disconnect(b);b=null;this.refresh()});else if((!this._respectVisibility||this._respectVisibility&&a.visible)&&
(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var c=d.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},c)))));d.place(c,this.id,"first");a.legendResponse||a.renderer&&"esri.renderer.StretchRenderer"!==a.renderer.declaredClass?this._createLegendForLayer(a):
this.isHostedTileService(a)?this._getLayerInfos(a).then(k.hitch(this,function(a){this._createLegendForLayer(a)}),k.hitch(this,function(a){g.push(this._legendRequest(a))})):g.push(this._legendRequest(a))}},this);0!==g.length||a||b?(new A(g)).addCallback(k.hitch(this,function(c){a||b?z.byId(this.id+"_msg").innerHTML="":z.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()})):(z.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate())},_createLegendForLayer:function(a){if(a.legendResponse||
a.renderer||this.isHostedTileService(a)){var b=!1;if(a.legendResponse||this.isHostedTileService(a)){var c=a.dynamicLayerInfos||a.layerInfos;c&&c.length?f.forEach(c,function(c,e){if(!this.hideLayersInLegend[a.id]||-1===f.indexOf(this.hideLayersInLegend[a.id],c.id)){var g=this._buildLegendItems(a,c,e);b=b||g}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+
1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(w.set(z.byId(this.id+"_"+a.id),"display","block"),w.set(z.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);h.connect(a,"onLoad",k.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";
(c=a._getToken())&&(b+="?token\x3d"+c);var g=k.hitch(this,"_processLegendResponse"),e={f:"json"};a._params.dynamicLayers&&(e.dynamicLayers=G.stringify(this._createDynamicLayers(a)),"[{}]"===e.dynamicLayers&&(e.dynamicLayers="[]"));a._params.bandIds&&(e.bandIds=a._params.bandIds);a._params.renderingRule?e.renderingRule=a._params.renderingRule:a.rasterFunctionInfos&&0<a.rasterFunctionInfos.length&&f.forEach(a.rasterFunctionInfos,function(a){a&&a.name&&"none"===a.name.toLowerCase()&&(e.renderingRule=
G.stringify({rasterFunction:a.name}))});return O({url:b,content:e,callbackParamName:"callback",load:function(b,c){g(a,b,c)},error:Q.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!l("ie")||8<l("ie"))b+="\x26returnbytes\x3dtrue";var c=k.hitch(this,"_processLegendResponse");return O({url:b,content:{f:"json"},callbackParamName:"callback",
load:function(b,e){c(a,b,e)},error:Q.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,z.byId(this.id+"_"+a.id)&&d.empty(z.byId(this.id+"_"+a.id)),d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},z.byId(this.id+"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+
y.toJson(b))},_buildLegendItems:function(a,b,c){var g=!1,e=z.byId(this.id+"_"+a.id),q=b.parentLayerId;if(b.subLayerIds)a=d.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:{display:"none"},"class":-1==q?0<c?"esriLegendGroupLayer":"":this._legendAlign},-1==q?e:z.byId(this.id+"_"+a.id+"_"+q+"_group")),d.create("td",{innerHTML:B.encode(b.name),align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(this._respectVisibility&&
a.visibleLayers)if(c=a.dynamicLayerInfos||a.layerInfos)if(a._params&&a._params.layers){if(-1===f.indexOf(a.visibleLayers,b.id))return g}else{if(c=this._getReallyVisibleLayers(c,a.visibleLayers),-1===f.indexOf(c,b.id))return g}else if(-1===f.indexOf(a.visibleLayers,b.id))return g;e=d.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:{display:"none"},"class":-1<q?this._legendAlign:""},-1==q?e:z.byId(this.id+"_"+a.id+"_"+q+"_group"));d.create("td",{innerHTML:B.encode(b.name)||"",align:this._align},d.create("tr",
{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},e))));c=a.dynamicLayerInfos||a.layerInfos;q=!1;c&&c.length&&(q=f.some(c,function(a){return!!a.drawingInfo}));if(a.legendResponse)g=g||this._buildLegendItems_Tools(a,b,e);else if(a.renderer||q)g=g||this._buildLegendItems_Renderer(a,b,e)}return g},_getReallyVisibleLayers:function(a,b){if(!a||!b||!b.length)return[];var c=[],g=[],e;for(e=0;e<a.length;e++)if(a[e].subLayerIds){if(-1===f.indexOf(b,a[e].id)||-1<f.indexOf(g,
a[e].id))g=g.concat(a[e].subLayerIds)}else-1<f.indexOf(b,a[e].id)&&-1===f.indexOf(g,a[e].id)&&c.push(a[e].id);return c},_buildLegendItems_Tools:function(a,b,c){var g=b.parentLayerId,e=this.map.getScale(),q=!1,C=function(a,b){var c,e;for(c=0;c<a.length;c++)if(b.dynamicLayerInfos)for(e=0;e<b.dynamicLayerInfos[e].length;e++){if(b.dynamicLayerInfos[e].mapLayerId==a[c].layerId)return a[c]}else if(b.id==a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,
b,e)){var k=!0;if(this._respectCurrentMapScale&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISMapServiceLayer"===a.declaredClass)){var v=this._getEffectiveScale(a,b);if(v.minScale&&v.minScale<e||v.maxScale&&v.maxScale>e)k=!1}if(k){var e=C(a.legendResponse.layers,b),l=e.legendType,m=e.layerType,h=e.legend;if(h){"esri.layers.ArcGISImageServiceLayer"!==a.declaredClass&&this._sanitizeLegendResponse(a,e,b);c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%",
"class":"esriLegendLayer"},c);var n=d.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b);var p=[];f.forEach(h,function(c){if(!(10.1<=a.version&&!c.values&&1<h.length)||!a._hideDefaultSymbol&&"\x3call other values\x3e"!==c.label&&(c.label||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version||"Raster Layer"===m)){var e=c.label;if(c.url&&0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)q=!0,e&&-1!==f.indexOf(p,e)||(p.push(e),this._buildRow_Tools(c,
n,a,b.id,l))}},this)}}}q&&(w.set(z.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<g&&(w.set(z.byId(this.id+"_"+a.id+"_"+g+"_group"),"display","block"),this._findParentGroup(a.id,a,g)));return q},_getLayerInfos:function(a){var b=new L,c=a.dynamicLayerInfos||a.layerInfos;if(c&&c.length)if(f.some(c,function(a){return!!a.drawingInfo}))b.resolve(a);else{var g=a.url,e=g.indexOf("?"),g=-1==e?g+"/layers":g.substring(0,e)+"/layers"+g.substring(e,g.length);O({url:g,content:{f:"json"},callbackParamName:"callback",
load:function(e,g){e.layers?(f.forEach(c,function(a){var b=f.filter(e.layers,function(b){return a.source?b.id===a.source.mapLayerId:b.id===a.id});b&&b[0]&&b[0].drawingInfo&&(a.drawingInfo=b[0].drawingInfo,a.fields=b[0].fields)}),b.resolve(a)):b.reject(a)},error:function(c){b.reject(a)}})}return b},_sanitizeLegendResponse:function(a,b,c){var g=b.legend;if(10.1<=a.version&&1<g.length&&!b._sanitized){a=k.getObject("layerDefinition.drawingInfo.renderer",!1,c);var e,d;a||(a=k.getObject("drawingInfo.renderer",
!1,c));f.some(g,function(a){if(a.values)return!0})&&f.some(g,function(a,b){a.values||(d=b,e=a);return!!e});a?"uniqueValue"===a.type?e&&(g.splice(d,1),g.push(e)):"classBreaks"===a.type&&(e&&g.splice(d,1),g.reverse(),e&&g.push(e)):e&&(g.splice(d,1),g.push(e));b._sanitized=!0}},_buildRow_Tools:function(a,b,c,g,e){var f=d.create("tr",{},b),C;this.alignRight?(b=d.create("td",{align:this._isRightToLeft?"left":"right"},f),C=d.create("td",{align:this._isRightToLeft?"left":"right",width:35},f)):(C=d.create("td",
{width:35,align:"center"},f),b=d.create("td",{},f));f=a.url;(!l("ie")||9<=l("ie")||9>l("ie")&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&a.imageData&&0<a.imageData.length?f="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(f=c.url+"/"+g+"/images/"+a.url,(g=c._getToken())&&(f+="?token\x3d"+g));g=d.create("img",{src:f,border:0,style:"opacity:"+c.opacity},C);a=d.create("td",{innerHTML:B.encode(a.label),align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",
{width:"95%",dir:"ltr"},b))));e&&"Stretched"===e&&10.3<=c.version&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass&&(a.style.verticalAlign="top",a.style.lineHeight="1",g.style.marginBottom="-1px",g.style.display="block",b.style.verticalAlign="top");9>l("ie")&&(g.style.filter="alpha(opacity\x3d"+100*c.opacity+")")},_getVariable:function(a,b,c){var g;a&&(g=(a=a.getVisualVariablesForType(b,c))&&a[0]);return g},_getVariables:function(a,b,c){a=[this._getVariable(a,"colorInfo",!1),this._getVariable(a,
"opacityInfo",!1),this._getVariable(a,"sizeInfo",!1)];return b?f.filter(a,function(a){return!(!a||a.field!==b||a.normalizationField!=c)}):a},_getFieldAlias:function(a,b,c){var g=b.infoTemplate||(b.infoTemplates&&c&&b.infoTemplates[c.id]?b.infoTemplates[c.id].infoTemplate:null),g=g&&g.getFieldInfo&&g.getFieldInfo(a);a=k.isFunction(a)?null:this.getField(b,a,c);b=g||a;c="";b&&(c=g&&g.label||a&&a.alias||b.name||b.fieldName);return c},_getDomainName:function(a,b,c,g){var e;a&&!k.isFunction(a)&&(e=(c=(a=
this.getField(c,a,g))&&c.getDomain?c.getDomain(a.name):null)&&c.codedValues?c.getName(b):null);return e},_getRampTitle:function(a,b,c){var g,e=a.field,d=a.normalizationField,f=!1,l=!1,v=!1,e=k.isFunction(e)?null:e,d=k.isFunction(d)?null:d;if(a.legendOptions&&a.legendOptions.title)g=a.legendOptions.title;else if(a.valueExpressionTitle)g=a.valueExpressionTitle;else{if(b.renderer&&b.renderer.authoringInfo&&b.renderer.authoringInfo.visualVariables){var h=b.renderer.authoringInfo.visualVariables;for(a=
0;a<h.length;a++){var m=h[a];if("colorInfo"===m.type&&"ratio"===m.style){f=!0;break}else if("colorInfo"===m.type&&"percent"===m.style){l=!0;break}else if("colorInfo"===m.type&&"percentTotal"===m.style){v=!0;break}}}(f=v&&"showRatioPercentTotal"||l&&"showRatioPercent"||f&&"showRatio"||d&&"showNormField"||e&&"showField"||null)&&(g=J.substitute({field:e&&this._getFieldAlias(e,b,c),normField:d&&this._getFieldAlias(d,b,c)},this._i18n[f]))}return g},_getRendererTitle:function(a,b,c){var g;if(a){var e,d,
f;"esri.renderer.ClassBreaksRenderer"===a.declaredClass&&(e=a.attributeField,d=a.normalizationField,f="percent-of-total"===a.normalizationType);e=k.isFunction(e)?null:e;d=k.isFunction(d)?null:d;a.legendOptions&&a.legendOptions.title?g=a.legendOptions.title:a.valueExpressionTitle?g=a.valueExpressionTitle:(a=d&&"showNormField"||(f?"showNormPct":null)||e&&"showField"||null)&&(g=J.substitute({field:e&&this._getFieldAlias(e,b,c),normField:d&&this._getFieldAlias(d,b,c)},this._i18n[a]))}return g},_buildLegendItems_Renderer:function(a,
b,c){var g=b.parentLayerId,e=this.map,q=e.getScale(),C,l=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,q)){var v,h,m,n,p,r,t,x;m="esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass?a.renderer.renderer:b&&b.drawingInfo?W.fromJson(k.clone(b.drawingInfo.renderer)):a.isFeatureReductionActive&&a.isFeatureReductionActive()?a.getFeatureReductionRenderer():a.renderer;if("esri.renderer.ScaleDependentRenderer"===m.declaredClass&&(m=(e="zoom"===m.rangeType?m.getRendererInfoByZoom(e.getZoom()):
m.getRendererInfoByScale(q))&&e.renderer,!m))return!1;var D=this._getVariables(m),u=f.filter(D,function(a){return!!a}).length,q=D[0],e=D[1],D=D[2],y,A,K,E,F;q&&(n=this._getMedianColor(m,q),q.field&&(r=k.isFunction(q.field)?null:this.getField(a,q.field,b)),y=!(q.legendOptions&&!1===q.legendOptions.showLegend));e&&(e.field&&(x=k.isFunction(e.field)?null:this.getField(a,e.field,b)),A=!(e.legendOptions&&!1===e.legendOptions.showLegend));D&&(D.field&&(t=k.isFunction(D.field)?null:this.getField(a,D.field,
b)),K=!(D.legendOptions&&!1===D.legendOptions.showLegend));if("esri.renderer.HeatmapRenderer"===m.declaredClass)C=l=!0,this._showHeatRamp(a,b,m,c);else if("esri.renderer.DotDensityRenderer"===m.declaredClass)C=l=!0,this._showDotDensityLegend(a,b,m,c);else if("esri.renderer.TemporalRenderer"===m.declaredClass)C=l=!0,h=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=d.create("tbody",{},h),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(h,a,b),m.latestObservationRenderer&&
"esri.renderer.SimpleRenderer"===m.latestObservationRenderer.declaredClass&&this._buildRow_Renderer(a,m.latestObservationRenderer.symbol,n,B.encode(m.latestObservationRenderer.label)||this.NLS_currentObservations,null,v),m.observationRenderer&&"esri.renderer.SimpleRenderer"===m.observationRenderer.declaredClass&&this._buildRow_Renderer(a,m.observationRenderer.symbol,n,B.encode(m.observationRenderer.label)||this.NLS_previousObservations,null,v);else if("esri.renderer.UniqueValueRenderer"===m.declaredClass){if(m.infos&&
0<m.infos.length){C=l=!0;if(m.legendOptions&&m.legendOptions.title||m.valueExpressionTitle)h=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=d.create("tbody",{},h),u=m.legendOptions&&m.legendOptions.title?m.legendOptions.title:m.valueExpressionTitle,this._buildRow_Renderer(a,null,n,B.encode(u),null,v);h=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);v=d.create("tbody",{},h);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(h,
a,b);m.attributeField&&D&&this._addSubHeader(v,this._getFieldAlias(m.attributeField,a,b));var G=[];f.forEach(m.infos,function(c){var e=null;a._editable&&a.types&&(e=this._getTemplateFromTypes(a.types,c.value));var g=c.label;null==g&&(g=this._getDomainName(m.attributeField,c.value,a,b)||c.value);-1===f.indexOf(G,g)&&(G.push(g),this._buildRow_Renderer(a,c.symbol,n,B.encode(g),e,v))},this)}F=this._displayDefaultSymbol(a,m,c)}else if("esri.renderer.ClassBreaksRenderer"===m.declaredClass){if(m.infos&&
0<m.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass)C=l=!0,E=this._isUnclassedRenderer(m),q||1!==m.infos.length||(p=(p=m.infos[0])&&p.symbol),E||(h=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=d.create("tbody",{},h),u=this._getRendererTitle(m,a,b),this._buildRow_Renderer(a,null,n,B.encode(u),null,v)),h=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=d.create("tbody",{},h),(a._hoverLabel||
a._hoverLabels)&&this._createHoverAction(h,a,b),E&&D&&K||(u=m.infos.slice(0).reverse(),f.forEach(u,function(b){var c=b.label;null!=c||E||(c=b.minValue+" - "+b.maxValue);this._buildRow_Renderer(a,b.symbol,n,B.encode(c),null,v)},this)),"esri.layers.ArcGISImageServiceVectorLayer"!==a.declaredClass||a.renderer.style!==R.STYLE_SCALAR&&a.renderer.style!==R.STYLE_SINGLE_ARROW||(this._buildRow_Renderer(a,m.defaultSymbol,null,"",null,v),a._hideDefaultSymbol=!0);E||(F=this._displayDefaultSymbol(a,m,c))}else"esri.renderer.SimpleRenderer"===
m.declaredClass&&(C=l=!0,h=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=d.create("tbody",{},h),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(h,a,b),p=null,a._editable&&a.templates&&0<a.templates.length&&(p=a.templates[0]),h=1<u?null:r&&y||x&&A||t&&K,this._buildRow_Renderer(a,m.symbol,n,B.encode(h?this._getRampTitle(1<u?null:q||e||D,a,b):m.label),p,v),p=q?null:m.symbol,h&&(r=x=t=null));C&&(q&&y&&(q.field||q.valueExpression)&&this._showGradientRamp(a,
b,m,null,c,q,r,null,D&&K?!0:!1),D&&K&&(D.field||D.valueExpression)&&(C=q&&y||"esri.renderer.UniqueValueRenderer"===m.declaredClass?!1:!0,this._showSizeLegend(a,b,m,D,n,c,t,null,C)),e&&A&&(e.field||e.valueExpression)&&this._showGradientRamp(a,b,m,p&&!p.url&&p.color?p.color:this.transparencyRampColor,c,e,x,null,!1));F||E&&!y&&!K&&!A||(F=this._displayDefaultSymbol(a,m,c));l=l||F}l&&(w.set(z.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<g&&(w.set(z.byId(this.id+"_"+a.id+"_"+g+"_group"),"display",
"block"),this._findParentGroup(a.id,g)));return l},_isUnclassedRenderer:function(a,b){var c;if("esri.renderer.ClassBreaksRenderer"===a.declaredClass&&a.infos&&1===a.infos.length){c=a.attributeField;var g=a.normalizationField;c=b?c===b:!!this._getVariables(a,c,g).length}return c},_displayDefaultSymbol:function(a,b,c){var g;!a._hideDefaultSymbol&&b.defaultSymbol&&(g=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),c=d.create("tbody",{},c),this._buildRow_Renderer(a,
b.defaultSymbol,null,B.encode(b.defaultLabel)||"others",null,c));return g},_showGradientRamp:function(a,b,c,g,e,f,h,l,v){v=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(v?"":" esriLegendSubFragment")},e);e=d.create("tbody",{},v);(a._hoverLabel||a._hoverLabels||l)&&this._createHoverAction(v,a,b,l);(h||f.valueExpression||f.legendOptions&&f.legendOptions.title)&&this._addSubHeader(e,this._getRampTitle(f,a,b));h=f.field;var q;h&&(q=k.isFunction(h)?null:this.getField(a,
h,b));(b=this._getRampStops(c,f,g,q&&"esriFieldTypeDate"===q.type))&&b.length&&this._drawGradientRamp(e,b,!0,a,this._getRampBorderColor(c),!!g)},_getMedianColor:function(a,b){var c,g;b.colors?(c=b.minDataValue,g=b.maxDataValue):b.stops&&(c=b.stops[0].value,g=b.stops[b.stops.length-1].value);return a.getColor(c+(g-c)/2,{colorInfo:b})},_getRampStops:function(a,b,c,g){var e,d,h,k,l=!1;b.colors||b.opacityValues?(d=b.maxDataValue-b.minDataValue,e=f.map([0,.25,.5,.75,1],function(a){h=b.minDataValue+a*d;
return Number(h.toFixed(6))}),this._checkPrecision(0,4,e)):b.stops&&(e=f.map(b.stops,function(a){return a.value}),(l=f.some(b.stops,function(a){return!!a.label}))&&(k=f.map(b.stops,function(a){return a.label})));var p=e[0],m,n;d=e[e.length-1]-p;return f.map(e,function(f,h){c?(m=new x(c.toRgba()),n=a.getOpacity(f,{opacityInfo:b}),null!=n&&(m.a=n)):m=a.getColor(f,{colorInfo:b});var q="";if(l)q=k[h];else{var q=g?M.formatDate(f,M.timelineDateFormatOptions):E.format(f),C="";0===h?C=this._specialChars.lt+
" ":h===e.length-1&&(C=this._specialChars.gt+" ");q=C+q}return{value:f,color:m,offset:1-(f-p)/d,label:q}},this).reverse()},_checkPrecision:function(a,b,c){var g=a+(b-a)/2,e=c[a],d=c[g],f=c[b],h=Math.floor(e),k=Math.floor(d),l=Math.floor(f);h===e&&l===f&&k!==d&&h!==k&&l!==k&&(c[g]=k);a+1!==g&&this._checkPrecision(a,g,c);g+1!==b&&this._checkPrecision(g,b,c)},_getRampBorderColor:function(a){var b;if("esri.renderer.SimpleRenderer"===a.declaredClass)b=a.symbol;else if("esri.renderer.UniqueValueRenderer"===
a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)b=a.infos[0].symbol;return(a=b&&-1===b.type.indexOf("linesymbol")?b.getStroke():null)&&a.color},_drawGradientRamp:function(a,b,c,g,e,h){var k=d.create("tr",{},a),q,v,n,m,p,r=b.length-1,u;m=0;this.alignRight?(a=d.create("td",{align:this._isRightToLeft?"left":"right"},k),q=d.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},k)):(q=d.create("td",{width:this.gradientWidth,align:"center"},k),a=d.create("td",
{},k));k=e&&0<e.a&&!(240<=e.r&&240<=e.g&&240<=e.b);v=d.create("div",{"class":k?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},q);q=d.create("div",{"class":"esriLegendColorRamp"+(h?" esriLegendTransparencyRamp":"")},v);h=w.get(q,"width");k&&(e=9>l("ie")?e.toHex():"rgba("+e.toRgba().join(",")+")",w.set(q,"border",this.colorRampBorder+" "+e));c?(e=this.gradientHeight*r,w.set(q,"height",e+"px")):e=w.get(q,"height");w.set(v,"height",e+"px");k=t.createSurface(q,
h,e);9>l("ie")&&(m=k.getEventSource(),w.set(m,"position","relative"),w.set(m.parentNode,"position","relative"),m=1);try{c&&f.forEach(b,function(a,b){a.offset=b/r}),p=k.createRect({x:-m,y:-m,width:h+m,height:e+m}),p.setFill({type:"linear",x1:0,y1:0,x2:0,y2:e,colors:b}).setStroke(null),k.createRect({width:h,height:e}).setFill(new x([255,255,255,1-g.opacity])).setStroke(null),this._surfaceItems.push(k)}catch(fa){k.clear(),k.destroy()}f.forEach(b,function(a,c){if(a.label){u="top:"+100*a.offset+"%;";var e=
"";0===c&&(e+=" esriLegendColorRampTickFirst");c===b.length-1&&(e+=" esriLegendColorRampTickLast");d.create("div",{"class":"esriLegendColorRampTick"+e,innerHTML:"\x26nbsp;",style:u},v)}});n=d.create("div",{"class":"esriLegendColorRampLabels",style:{height:e+this.gradientHeight+"px"}},a);c?f.forEach(b,function(a){d.create("div",{"class":"esriLegendColorRampLabel",innerHTML:B.encode(a.label)||"\x26nbsp;"},n)}):(d.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},n),d.create("div",
{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,style:"top: "+(e+this.gradientHeight-2*this.gradientHeight)+"px;"},n))},_showHeatRamp:function(a,b,c,g,e){var f,h=c.field;f=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);g=d.create("tbody",{},f);(a._hoverLabel||a._hoverLabels||e)&&this._createHoverAction(f,a,b,e);(h=h&&this.getField(a,h,b))&&this._addSubHeader(g,this._getFieldAlias(h.name,a,b));b=this._getHeatmapStops(c);b.length&&this._drawGradientRamp(g,
b,!1,a)},_getHeatmapStops:function(a){var b=a.colorStops;a=a.colors;var c,g,e,d;b&&b[0]?(c=b.length-1,(a=b[0]&&null!=b[0].ratio)?(a=b[c])&&1!==a.ratio&&(b=b.slice(0),b.push({ratio:1,color:a.color}),c++):(g=b[0].value,e=b[c].value-g,b=f.map(b,function(a){return{color:a.color,ratio:(a.value-g)/e}}))):a&&a[0]&&(c=a.length-1,d=1/(a.length-1),b=f.map(a,function(a,b){return{color:a,ratio:b*d}}));b=f.map(b,function(a,b){var e="";0===b?e="Low":b===c&&(e="High");return{color:a.color,label:e,offset:1-a.ratio}});
return b.reverse()},_showDotDensityLegend:function(a,b,c,g){var e=c.legendOptions,h,l,n,v,p,m,r,t=this.dotDensitySwatchSize,u=Math.round(t/2);e&&(l=e.backgroundColor,n=e.outline,v=e.valueUnit,p=e.dotCoverage);p=(p||this.dotCoverage)/100;r=Math.round(t*t/Math.pow(c.dotSize,2)*p);g=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);m=d.create("tbody",{},g);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(g,a,b);this._addSubHeader(m,J.substitute({value:c.dotValue,
unit:v||""},this.NLS_dotValue));f.forEach(c.fields,function(e){e=k.mixin({},e);e.numPoints=r;h=new U(c._generateImageSrc(t,t,[e],{x:0,y:0},{x:t,y:t},l),n||c.outline,t,t);e=this.getField(a,e.name,b)||e;this._buildRow_Renderer(a,h,null,B.encode(this._getFieldAlias(e.name,a,b)),null,m,{type:"path",path:"M "+-u+","+-u+" L "+u+","+-u+" L "+u+","+u+" L "+-u+","+u+" L "+-u+","+-u+" E"})},this)},_showSizeLegend:function(a,b,c,g,e,f,h,l,v){var q=g.legendOptions,q=q&&q.customValues;e=this._getSizeSymbol(c,
e);if((!g.valueUnit||"unknown"===g.valueUnit)&&e&&(q||null!=g.minSize&&null!=g.maxSize&&null!=g.minDataValue&&null!=g.maxDataValue||g.stops&&!(1>=g.stops.length))){v=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(v?"":" esriLegendSubFragment")},f);f=d.create("tbody",{},v);(a._hoverLabel||a._hoverLabels||l)&&this._createHoverAction(v,a,b,l);(h||g.valueExpression||g.legendOptions&&g.legendOptions.title)&&this._addSubHeader(f,this._getRampTitle(g,a,b));h=g.field;
var m;l=k.isFunction(h);h&&(m=l?null:a.isFeatureReductionActive&&a.isFeatureReductionActive()?a.getFeatureReductionField(h):this.getField(a,h,b));b=m&&"esriFieldTypeDate"===m.type;var q=q||this._getDataValues(c,e,g,b),n,p=q.length-1;for(m=p;0<=m;m--)v=q[m],e=N.fromJson(e.toJson()),this._applySize(e,c,g,v),v=b?M.formatDate(v,M.timelineDateFormatOptions):E.format(v),n="",m===p?n=this._specialChars.gt+" ":0===m&&(n=h&&!l&&"cluster_count"===h.toLowerCase()&&1===q[m]?"":this._specialChars.lt+" "),n="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+
B.encode(n+v)+"\x3c/span\x3e",this._buildRow_Renderer(a,e,null,n,null,f)}},_getSizeSymbol:function(a,b){var c,g;if("esri.renderer.SimpleRenderer"===a.declaredClass)c=a.symbol;else if("esri.renderer.VectorFieldRenderer"===a.declaredClass)c=a.defaultSymbol;else if("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)c=a.infos[0].symbol,g=1<a.infos.length;if(c=c&&-1!==c.type.indexOf("fillsymbol")?null:c)if(c=N.fromJson(c.toJson()),b||g)-1!==c.type.indexOf("linesymbol")?
c.setColor(new x(this.sizeRampDarkColor)):(c.setColor(new x(this.sizeRampLightColor)),c.setOutline&&(g=new V,g.setColor(new x(this.sizeRampDarkColor)),g.setWidth(1.5),c.setOutline(g)));return c},_getDataValues:function(a,b,c,g,e,d){e=null==e?5:e;d=null==d?20:d;var h=a.getSizeRangeAtScale(c,this.map.getScale());e=this._interpolateSizeRange(h,e);var k=this._getDataRange(c),l=f.map(e,function(a){return this._getDataValueFromSize(a,k,h)},this);if(!g){var q,l=E.round(l);for(g=1;g<l.length-1;g++)if(q=this._roundDataValue(a,
b,c,l[g],l[g-1],d))l[g]=q[0],e[g]=q[1]}return l},_getDataRange:function(a){var b=a.stops;return b?{min:b[0].value,max:b[b.length-1].value}:{min:a.minDataValue,max:a.maxDataValue}},_interpolateSizeRange:function(a,b){var c=a.minSize,d=(a.maxSize-c)/(b-1),e,f=[];for(e=0;e<b;e++)f.push(c+d*e);return f},_getDataValueFromSize:function(a,b,c){var d=c.minSize;c=c.maxSize;var e=b.min;b=b.max;return a<=d?e:a>=c?b:(a-d)/(c-d)*(b-e)+e},_roundDataValue:function(a,b,c,d,e,f){var g=this._getSize(b,a,c,d);e=this._getSize(b,
a,c,e);var h,k=E.getDigits(d),l=k.integer,k=k.fractional,m,q,n,p,r,t,u,w,x,y,z;0<d&&1>d&&(h=Math.pow(10,k),d*=h,l=E.getDigits(d).integer);for(--l;0<=l&&(m=Math.pow(10,l),k=Math.floor(d/m)*m,m*=Math.ceil(d/m),null!=h&&(k/=h,m/=h),q=(k+m)/2,q=E.round([k,q,m],{indexes:[1]})[1],n=this._getSize(b,a,c,k),p=this._getSize(b,a,c,m),r=this._getSize(b,a,c,q),t=E.getPctChange(g,n,e,null),u=E.getPctChange(g,p,e,null),w=E.getPctChange(g,r,e,null),x=t.prev<=f,y=u.prev<=f,x&&y&&(t.prev<=u.prev?(x=!0,y=!1):(y=!0,
x=!1)),x?z=[k,n]:y?z=[m,p]:w.prev<=f&&(z=[q,r]),!z);l--);return z},_applySize:function(a,b,c,d){var e=a.type;b=this._getSize(a,b,c,d);switch(e){case "simplemarkersymbol":a.setSize(b);break;case "picturemarkersymbol":e=a.width;c=a.height;a.setHeight(b);a.setWidth(e/c*b);break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(b);break;case "textsymbol":a.font&&a.font.setSize(b)}},_getSize:function(a,b,c,d){return b.getSize(d,{sizeInfo:c,scale:this.map.getScale(),shape:-1!==a.type.indexOf("markersymbol")?
a.style:null})},_buildRow_Renderer:function(a,b,c,g,e,f,h){var k=d.create("tr",{},f),l;this.alignRight?(f=d.create("td",{align:this._isRightToLeft?"left":"right"},k),b&&(l=d.create("td",{align:this._isRightToLeft?"left":"right",width:35},k))):(b&&(l=d.create("td",{width:35,align:"center"},k)),f=d.create("td",{},k));var q=k=30,m;if(b){if("simplemarkersymbol"==b.type)k=Math.min(Math.max(k,b.size+12),125),q=Math.min(Math.max(q,b.size+12),125);else if("picturemarkersymbol"==b.type)k=Math.min(Math.max(k,
b.width),125),q=Math.min(b.height||q,125);else if("textsymbol"==b.type){var n,p;b.text||(n=b.text,p=!0,b.setText(this.defaultText));k=Math.min(Math.max(k,b.getWidth()+12),125);q=Math.min(Math.max(q,b.getHeight()+12),125);p&&b.setText(n)}m=d.create("div",{style:"width:"+k+"px;height:"+q+"px;"},l)}J.isDefined(g)&&"number"===typeof g&&(g=""+g);d.create("td",{innerHTML:g||"",align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},f))));b&&(a=this._drawSymbol(m,b,c,k,q,e,
a,h),this._surfaceItems.push(a))},_addSubHeader:function(a,b){var c=d.create("tr",{},a),c=d.create("td",{align:this._align,colspan:2},c);d.create("td",{innerHTML:B.encode(b)||"",align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},c))))},_drawSymbol:function(a,b,c,d,e,f,h,n){b=N.fromJson(b.toJson());var g=h.opacity;c&&b.setColor(new x(c.toRgba()));if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();
c[3]*=g;b.color.setColor(c)}else"simplemarkersymbol"===b.type||"simplefillsymbol"===b.type?(b.color&&(c=b.color.toRgba(),c[3]*=g,b.color.setColor(c)),b.outline&&b.outline.color&&(c=b.outline.color.toRgba(),c[3]*=g,b.outline.color.setColor(c))):"picturemarkersymbol"===b.type&&(a.style.opacity=g,a.style.filter="alpha(opacity\x3d("+100*g+"))");a=t.createSurface(a,d,e);9>l("ie")&&(c=a.getEventSource(),w.set(c,"position","relative"),w.set(c.parentNode,"position","relative"));f=this._getDrawingToolShape(b,
f)||N.getShapeDescriptors(b);var q,g=(c=f.defaultShape)&&"text"===c.type;try{g&&!c.text&&(c.text=this.defaultText),q=a.createShape(n||c).setFill(f.fill).setStroke(f.stroke),g&&q.setFont(f.font)}catch(ga){a.clear();a.destroy();return}var m=q.getBoundingBox();n=m.width;f=m.height;var g=-(m.x+n/2),p=-(m.y+f/2);c=a.getDimensions();g={dx:g+c.width/2,dy:p+c.height/2};if("simplemarkersymbol"===b.type&&"path"===b.style)d=h._getScaleMatrix(m,b.size),q.applyTransform(F.scaleAt(d.xx,d.yy,{x:c.width/2,y:c.height/
2}));else if(n>d||f>e)h=n/d>f/e,d=((h?d:e)-5)/(h?n:f),k.mixin(g,{xx:d,yy:d});q.applyTransform(g);return a},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 Z"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 Z"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 Z"};
break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){f.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&k.isArray(a.children)&&
f.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,b,c,g){if(g=b._hoverLabel||b._hoverLabels&&b._hoverLabels[c.id]||g)g=B.encode(g),b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=h.connect(a,"onmousemove",k.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,w.set(z.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(k.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=
!0,z.byId(this.id+"_hoverLabel")){var e=z.byId(this.id+"_hoverLabel");e.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";w.set(e,"top",b+"px");w.set(e,"left",a+15+"px");w.set(e,"display","")}else d.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},g)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=h.connect(a,"onmouseout",k.hitch(this,function(a){this.mouseY=
this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,w.set(z.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var a;f.forEach(this.layers,function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)h.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)h.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=[],c;f.forEach(a.dynamicLayerInfos||a.layerInfos,function(d){c={id:d.id};c.source=d.source&&d.source.toJson();
var e;a.layerDefinitions&&a.layerDefinitions[d.id]&&(e=a.layerDefinitions[d.id]);e&&(c.definitionExpression=e);var f;a.layerDrawingOptions&&a.layerDrawingOptions[d.id]&&(f=a.layerDrawingOptions[d.id]);f&&(c.drawingInfo=f.toJson());c.minScale=d.minScale||0;c.maxScale=d.maxScale||0;b.push(c)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,e=
b.dynamicLayerInfos||b.layerInfos;for(d=0;d<e.length;d++)if(c==e[d].id){-1<e[d].parentLayerId&&(w.set(z.byId(this.id+"_"+a+"_"+e[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,e[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,d){var e=a.layer.dynamicLayerInfos||a.layer.layerInfos,g,h;for(g=0;g<e.length;g++)if(e[g].id===c&&e[g].subLayerIds)for(h=0;h<e[g].subLayerIds.length;h++){var k=e[g].subLayerIds[h];-1===f.indexOf(d,k)&&(d.push(k),b(k,d))}}a.layer.layerInfos&&
f.forEach(this.hideLayersInLegend[a.layer.id],function(c){b(c,this.hideLayersInLegend[a.layer.id])},this)},_isLayerInScale:function(a,b,c){var d,e=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var f=a.legendResponse.layers[d];if(b.id==f.layerId){var h,k;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==f.minScale&&a.tileInfo&&(h=a.tileInfo.lods[0].scale),0==f.maxScale&&a.tileInfo&&(k=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(h=Math.min(a.minScale,
f.minScale)||a.minScale||f.minScale,k=Math.max(a.maxScale,f.maxScale));if(0<h&&h<c||k>c)e=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)e=!1;return e},_getServiceTitle:function(a){var b=a._titleForLegend;b||(b=a.url,a.url?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+
1,b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&a.vectorFieldPixelFilter&&(a=a.vectorFieldPixelFilter.outputUnit?this["NLS_"+a.vectorFieldPixelFilter.outputUnit]:this["NLS_"+a.vectorFieldPixelFilter.inputUnit],J.isDefined(a)&&(b+=" ("+a+")"));return B.encode(b)},_getEffectiveScale:function(a,
b){var c=b.minScale,d=b.maxScale;if(J.isDefined(b.parentLayerId)){var e=a.layerInfos,f=b.parentLayerId,h;for(h=e.length-1;0<=h;h--)if(e[h].id==f)if(0==c&&0<e[h].minScale?c=e[h].minScale:0<c&&0==e[h].minScale||0<c&&0<e[h].minScale&&(c=Math.min(c,e[h].minScale)),d=Math.max(d||0,e[h].maxScale||0),-1<e[h].parentLayerId)f=e[h].parentLayerId;else break}return{minScale:c,maxScale:d}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.WFSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1},isHostedTileService:function(a){var b=
/(https?:)?\/\/services.*\.arcgis\.com/i;return"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass&&b.test(a.url)?!0:!1},getField:function(a,b,c){if(a.getField)return a.getField(b);if(c&&c.fields){var d;f.forEach(c.fields,function(a){a.name===b&&(d=a)});return d}return null}});k.mixin(I,{ALIGN_LEFT:0,ALIGN_RIGHT:1});l("extend-esri")&&k.setObject("dijit.Legend",I,T);return I});