// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/_ImageContainerMixin","dojo/_base/declare dojo/Deferred dojo/sniff dojox/gfx dojox/gfx/matrix dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/when esri/dijit/geoenrichment/_Invoke esri/dijit/geoenrichment/utils/ImageInfoUtil ./annotationUtils/AnnotationsUtil ./annotationUtils/CircularMaskUtil ../supportClasses/images/ImageDataHolder esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/WaitingUtil dojo/i18n!../../../../../nls/jsapi".split(" "),
function(t,u,v,z,A,e,d,B,c,l,w,x,n,y,p,f,q,m){m=m.geoenrichment.dijit.ReportPlayer.ReportPlayer;return t(w,{themeContext:null,theme:null,imageJson:null,relativeParent:null,imageTriggerJson:null,movable:!1,alignParams:null,showError:!0,createMapFunc:null,getDynamicImageFunc:null,_circularMask:!1,_fitParent:!0,_angle:0,_opacity:1,_isLogoPlaceholder:!1,_logoPlaceholderType:null,_dynamicBehavior:null,_isMapImage:!1,_webMapId:null,_defaultBasemapId:null,_thumbnailUrl:null,_useDefaultImageSizeFlag:!1,_fileName:null,
_imageData:null,postCreate:function(){this._configurePropertiesFromImageJson();this._isMapImage||(this.createMapFunc=null);this.content=this.createMapFunc?d.create("div",{"class":"templateMap"}):d.create(this._isMapImage?"div":"img",{"class":"floatingElement templateImage"});this.inherited(arguments);this._configureDomNodeStylesFromParameters();this._addAdditionalUI();this._isMapImage?this.resize():this._isLogoPlaceholder&&(this.content._wToHRatio=1,this.resize());this._applyOpacity();this._applyRotation();
this.alignParams&&n.alignAnnotationContainer(this,this.alignParams);(this.imageJson.fileName||this.imageJson.isLogoPlaceholder||this._imageData)&&this._initWithImageData()},_configurePropertiesFromImageJson:function(){this.fieldStyle=this.fieldStyle||{};this.fieldStyle.width=this.imageJson.style.width||150;this.fieldStyle.height=this.imageJson.style.height||0;this._circularMask=!!this.imageJson.circularMask;this._isMapImage=!!this.imageJson.isMapImage;this._webMapId=this.imageJson.webMapId;this._defaultBasemapId=
this.imageJson.defaultBasemapId;this._thumbnailUrl=this.imageJson.thumbnailUrl;this._isLogoPlaceholder=!!this.imageJson.isLogoPlaceholder;this._logoPlaceholderType=this.imageJson.logoPlaceholderType;this._fileName=this.imageJson.fileName;this._opacity=Math.max(0,Math.min(1,void 0!==this.imageJson.style.opacity?this.imageJson.style.opacity:1));this._angle=this.imageJson.style.angle||0;this._dynamicBehavior=this.imageJson.dynamicBehavior;this._fitParent=!1!==this.imageJson.fitParent;this.imageJson.style.width||
(this._useDefaultImageSizeFlag=!0)},_configureDomNodeStylesFromParameters:function(){this._isLogoPlaceholder&&e.add(this.domNode,"templateImage_logoPlaceholder");"short"==this._logoPlaceholderType&&e.add(this.domNode,"templateImage_logoPlaceholderShort");this._isMapImage&&!this.createMapFunc&&this._setMapImageBackground();e.add(this.domNode,!1===this.movable?"templateImageContainerStatic":"templateImageContainerMovable");e.add(this.domNode,"floatingElementContainer templateImageContainer");c.set(this.domNode,
"position","absolute");c.set(this.domNode,"top",(this.imageJson.style.top||0)+"px");c.set(this.domNode,"left",(this.imageJson.style.left||0)+"px")},_addAdditionalUI:function(){},_applyOpacity:function(){0<this._opacity&&1>this._opacity?(this._ieHackClipMask&&(this._ieHackClipMask.style.opacity=this._opacity),this.content.style.opacity=this._opacity):(delete this.content.style.opacity,this._ieHackClipMask&&delete this._ieHackClipMask.style.opacity)},_applyRotation:function(){this._angle=0<this._angle||
0>this._angle?this._angle:0;var a=v("safari")?"webkitTransform":"transform";this.content.style[a]="rotate("+this._angle+"deg)";this._updateCircularMask()},_initWithImageData:function(){var a=this;return l(this._reloadImageData(),function(){a.onInitialized();a._circularMask&&a._updateCircularMask()})},_reloadImageData:function(){function a(a,c){return b._setImageData({data:a,fileName:c,recalcImageContainerDimentions:b._useDefaultImageSizeFlag,preserveHeight:!1,dispatchEvents:!1})}var b=this;if(!this._isMapImage)if(this._isLogoPlaceholder){if(this.getDynamicImageFunc){var c=
d.create("div",null,this.domNode);q.showProgress(c);this.onContentLoadingStart();return l(this.getDynamicImageFunc(this._dynamicBehavior,this.theme||this.themeContext)).then(function(b){return b&&a(b)}).always(function(){d.destroy(c);b.onContentLoadingEnd()})}}else return a(p.getImageData(b._fileName)||b.imageJson.data,b._fileName)},_setImageData:function(a){var b=this,h=a.data,d=a.fileName,e=a.recalcImageContainerDimentions,g=a.preserveHeight,r=a.dispatchEvents,k=new u;b._showErrorMessage(!1);c.set(this.domNode,
"opacity","0.01");x.getImageInfo(h,d).then(function(a){r&&b.onImageDataPreChanged();var h=a.width/a.height;b.content._wToHRatio=h;var d;d=b._fitParent?b._useDefaultImageSizeFlag?150:Math.min(b.getWidth(),b.getHeight()*h):b.imageJson.style.width||150;c.set(b.content,"width",d+"px");c.set(b.content,"height",d/h+"px");b.content.onload=function(){e&&b._recalcImageContainerDimentions(g);r&&b.onImageDataChanged();k.resolve()};b.content.onerror=function(a){k.reject(a)};b._fileName=a.filename;b._imageData=
a.dataUrl;b._applyBackgroundUrl(a.dataUrl);p.putImageData(a.filename,a.dataUrl);b._syncLogoStateAfterLoadingImage()},k.reject);k.promise.then(function(){b.domNode&&c.set(b.domNode,"opacity","")},function(){b._showErrorMessage(!0)});return k.promise},_syncLogoStateAfterLoadingImage:function(){this.domNode&&e[this._fileName||this._imageData?"remove":"add"](this.domNode,"templateImage_logoPlaceholder");this._isLogoPlaceholder=!this._fileName},_showErrorMessage:function(a){this.showError&&(a&&!this.errorMessageDiv&&
(this.errorMessageDiv=d.create("div",{"class":"templateImage_errorMessage",innerHTML:this._isMapImage?m.mapLoadError:m.imageLoadError},this.domNode),c.set(this.errorMessageDiv,"top",c.get(this.domNode,"height")/2-20+"px")),f[a?"show":"hide"](this.errorMessageDiv))},_recalcImageContainerDimentions:function(a){if(this.domNode){var b=f.position(this.content),c=a&&this.getHeight();this.setWidth(b.w);this.setHeight(b.h);a&&this.setHeight(c)}},_setMapImageBackground:function(){var a=this;e.add(this.content,
"templateMapImage");this._thumbnailUrl?this._applyBackgroundUrl(this._thumbnailUrl):this._webMapId&&(a._applyBackgroundUrl(null),l(this._updateThumbnailUrl(),function(){a._thumbnailUrl&&a._applyBackgroundUrl(a._thumbnailUrl);a.__updateThumbnailClass()}));this.__updateThumbnailClass()},__updateThumbnailClass:function(){e[this._thumbnailUrl?"add":"remove"](this.content,"templateImageWithThumbnail")},_updateThumbnailUrl:function(){},_applyBackgroundUrl:function(a){this._isMapImage?this.content.style.backgroundImage=
a?"url("+a+")":"":this.content.src=a||"";this.__updateThumbnailClass();this._updateCircularMask()},_getBackgroundUrl:function(){return this._isMapImage?c.get(this.content,"backgroundImage").replace("url","").replace("(","").replace(")","").replace(/\"/g,""):this.content.src},isMapImage:function(){return this._isMapImage},_lastAlignParams:null,resize:function(a,b){a&&(this.setWidth(a.w),this.setHeight(a.h),this._useDefaultImageSizeFlag=!1);if(this._isMapImage){var h=c.get(this.content,"width"),d=this.getWidth(),
e=c.get(this.content,"height"),g=this.getHeight();if(h!==d||e!==g)c.set(this.content,"width",d+"px"),c.set(this.content,"height",g+"px"),this.createMapFunc&&this._placeMap()}else this._lastAlignParams=b,this._resizeContentImage();this._updateCircularMask()},_getContentImageWToHRatio:function(){return this.content._wToHRatio||(this.imageJson.style._imageW||this.imageJson.style.width)/(this.imageJson.style._imageH||this.imageJson.style.height)},_resizeContentImage:function(){var a=this._getContentImageWToHRatio(),
b;b=this._fitParent?Math.min(this.getWidth(),this.getHeight()*a):Math.min(this.imageJson.style.width,this.imageJson.style.height*a,this.getWidth(),this.getHeight()*a);c.set(this.content,"width",b+"px");c.set(this.content,"height",b/a+"px");n.alignAnnotationContainer(this,this._lastAlignParams);this._updateCircularMask()},scaleProportionallyWithinParent:function(a){var b=this.getImageBox(!1);this.resize({w:b.w*a.xScale,h:b.h*a.yScale});c.set(this.domNode,{left:b.l*a.xScale+"px",top:b.t*a.yScale+"px"})},
_isPlacingMapFlag:!1,_currentMap:null,_placeMap:function(){function a(){f&&f.remove();g&&clearTimeout(g);d.destroy(e);c._finalizePlaceMap()}function b(){a();c._showErrorMessage(!0);c.onMapLoadError()}var c=this;this._showErrorMessage(!1);this._isPlacingMapFlag&&this._finalizePlaceMap();this._currentMap&&this._currentMap.destroy();this._currentMap=null;d.empty(this.content);var e=d.create("div",null,this.content);q.showProgress(e);this.onContentLoadingStart();this._isPlacingMapFlag=!0;var f,g;return l(this.createMapFunc(this.content,
{webMapId:this._webMapId,defaultBasemapId:this._defaultBasemapId}),function(d){(c._currentMap=d)?(c._mapExtentPending&&c.setVisualState({mapExtent:c._mapExtentPending}),c.own(d),d.loaded?a():(f=on.once(d,"load",a),g=setTimeout(function(){b()},6E4))):b()},b)},_finalizePlaceMap:function(){this._isPlacingMapFlag&&(this._isPlacingMapFlag=!1,this.onContentLoadingEnd())},_mapExtentPending:null,getVisualState:function(){return{mapExtent:this._currentMap&&this._currentMap.extent}},setVisualState:function(a){this._mapExtentPending=
null;a&&a.mapExtent&&(this._currentMap&&this._currentMap.setExtent?this._currentMap.setExtent(a.mapExtent):this._mapExtentPending=a.mapExtent)},_ieHackClipMask:null,_updateCircularMask:function(){this.createMapFunc||(this._ieHackClipMask&&d.destroy(this._ieHackClipMask),this._ieHackClipMask=y.setCircularMask(this._circularMask&&this._imageData,this.content,this._getBackgroundUrl(),this._angle),this._applyOpacity())},getFitParent:function(){return this._fitParent},setFitParent:function(a){this._fitParent=
a;this._resizeContentImage()},getImageBox:function(a){a=!1!==a&&f.position(this.content);return{w:a?a.w:this.getWidth(),h:a?a.h:this.getHeight(),l:this.domNode?c.get(this.domNode,"left"):0,t:this.domNode?c.get(this.domNode,"top"):0}},setImageWidth:function(a){this._fitParent||(this.imageJson.style.width=a,this.imageJson.style.height=a/this._getContentImageWToHRatio(),this._resizeContentImage())},setImageHeight:function(a){this._fitParent||(this.imageJson.style.height=a,this.imageJson.style.width=
a*this._getContentImageWToHRatio(),this._resizeContentImage())},onInitialized:function(){},onImageDataPreChanged:function(){},onImageDataChanged:function(){},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},onMapLoadError:function(){},toJson:function(){var a=f.position(this.content),b={id:"img",fileName:this._isLogoPlaceholder?null:this._fileName,isMapImage:this._isLogoPlaceholder?!1:this._isMapImage,webMapId:this._webMapId,defaultBasemapId:this._defaultBasemapId,thumbnailUrl:this._thumbnailUrl,
circularMask:this._circularMask,isLogoPlaceholder:this._isLogoPlaceholder,logoPlaceholderType:this._isLogoPlaceholder?this._logoPlaceholderType:null,dynamicBehavior:this._isLogoPlaceholder?this._dynamicBehavior:null,fitParent:this._fitParent,style:{top:this.domNode?c.get(this.domNode,"top"):0,left:this.domNode?c.get(this.domNode,"left"):0,angle:this._angle,opacity:this._opacity,_imageW:a.w,_imageH:a.h}};this._fitParent?(b.style.width=this.getWidth(),b.style.height=this.getHeight()):(b.style.width=
a.w,b.style.height=a.h);return b},destroy:function(){this._finalizePlaceMap();this.inherited(arguments)}})});