// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/ShapeContainer","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-style ../grid/ValueField esri/dijit/geoenrichment/utils/ShapeUtil ./annotationUtils/AnnotationsUtil dojo/i18n!../../../../../nls/jsapi".split(" "),function(u,h,l,f,c,v,q,d,x){var w={borderColor:"#AAAAAA",fillColor:"#AAAAAA"};return u(v,{shapeJson:null,relativeParent:null,alignParams:null,applyThemeStyle:!0,getPreviewValueFunction:null,_g:!1,
_viewBox:!1,_shapeStyle:null,_shapeThemeStyle:null,_preserveAspectRatio:void 0,_showAsBar:!1,_showBarBackground:!1,_barBackgroundStyle:null,_isPlaceholder:!1,postCreate:function(){this.content=f.create("div",{"class":"floatingElement templateShape"});this.fieldStyle=this.fieldStyle||{};this.fieldStyle.width=this.shapeJson.style.width;this.fieldStyle.height=this.shapeJson.style.height;this._g=this.shapeJson.g;this._viewBox=this.shapeJson.viewBox;this._shapeStyle=this.shapeJson.style||{};this._shapeThemeStyle=
this.applyThemeStyle?this.shapeJson.themeStyle:null;this._preserveAspectRatio=this.shapeJson.preserveAspectRatio;this._isPlaceholder=this.shapeJson.isPlaceholder;this._showAsBar=this.shapeJson.showAsBar;this._showBarBackground=this.shapeJson.showBarBackground;this._barBackgroundStyle=this.shapeJson.barBackgroundStyle||{};this.inherited(arguments);l.add(this.domNode,"templateShapeContainerStatic");l.add(this.domNode,"floatingElementContainer templateShapeContainer");c.set(this.domNode,"position","absolute");
c.set(this.domNode,"top",(this.shapeJson.style.top||0)+"px");c.set(this.domNode,"left",(this.shapeJson.style.left||0)+"px");this._updateShapeNode();this.alignParams&&d.alignAnnotationContainer(this,this.alignParams);this.onInitialized()},getBorders:function(){return{outer:{t:1,b:0,l:1,r:0},inner:{t:0,b:0,l:0,r:0}}},resize:function(a,b){a&&(this.setWidth(a.w-3),this.setHeight(a.h-3));this._updateShapeNode();d.alignAnnotationContainer(this,b)},scaleProportionallyWithinParent:function(a){var b=this.getShapeBox();
this.resize({w:b.w*a.xScale,h:b.h*a.yScale});c.set(this.domNode,{left:b.l*a.xScale+"px",top:b.t*a.yScale+"px"})},getShapeBox:function(){return{l:c.get(this.domNode,"left"),t:c.get(this.domNode,"top"),w:this.getWidth(),h:this.getHeight()}},_updateShapeNode:function(){function a(a){function d(a){var d=q.createSVGNode(b._viewBox,{width:g+"px",height:m+"px",overflow:"visible"});b._preserveAspectRatio&&d.setAttribute("preserveAspectRatio",b._preserveAspectRatio);b._g.forEach(function(a){(a=q.createNodeByAttributes(a,
p))&&d.appendChild(a)});var e=f.create("div",{"class":"shapeContainer_svgContainerElement"},n);c.set(e,"left",a*g+"px");f.place(d,e)}var n=f.create("div",{"class":"shapeContainer_svgContainer esriGEAbsoluteStretched"},b.content),p;a?(l.add(n,"shapeContainer_svgContainerBackground"),p=h.mixin({},b._barBackgroundStyle,w)):p=h.mixin({},b._shapeThemeStyle,b._shapeStyle);var e=1;b._showAsBar&&(e=a?1:b.getPreviewValueFunction?b.getPreviewValueFunction().normalizedValue:.5+.5*Math.random(),c.set(n,"width",
e*k+"px"),l.add(n,"shapeContainer_svgContainerShowAsBar"));a=b._showAsBar?Math.floor(k/g):1;a=Math.round(e*a);for(e=0;e<a;e++)d(e)}var b=this,k=this.getWidth(),d=this.getHeight(),r=this._viewBox.width/this._viewBox.height,t=Math.min(k,d*r),g,m;"none"===this._preserveAspectRatio?(g=k,m=d):(g=t,m=t/r);c.set(this.content,"width",(this._showAsBar?k:g)+"px");c.set(this.content,"height",m+"px");f.empty(this.content);this._isPlaceholder?f.create("div",{"class":"shapeContainer_svgPlaceholder"},this.content):
(this._showAsBar&&this._showBarBackground&&a(!0),a())},onInitialized:function(){},_domNodePositionToShapeStyle:function(){this.domNode&&(this._shapeStyle.top=c.get(this.domNode,"top"),this._shapeStyle.left=c.get(this.domNode,"left"))},toJson:function(){this._domNodePositionToShapeStyle();var a={id:"shape",g:this._g,viewBox:this._viewBox,preserveAspectRatio:this._preserveAspectRatio,isPlaceholder:this._isPlaceholder,style:h.mixin({},this._shapeStyle,{width:this.getWidth(),height:this.getHeight()}),
themeStyle:this._shapeThemeStyle,showAsBar:this._showAsBar,showBarBackground:this._showBarBackground,barBackgroundStyle:h.mixin({},this._barBackgroundStyle)};return h.clone(a)}})});