// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/MapBuilder","dojo/_base/Color dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/Evented dojo/when dojo/dom-construct dojo/dom-style dojo/dom-geometry esri/graphic esri/layers/GraphicsLayer esri/arcgis/utils esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/graphicsUtils ./WebMapsUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(h,c,E,k,t,u,n,l,v,w,x,y,p,z,m,A,q,B){var C=
c(t,{_mapImageInfo:null,_mapImage:null,loaded:!1,error:!1,constructor:function(a,b){this._mapImageInfo=a;this._mapImage=n.create("img",{"class":"esriGEAbsoluteStretched"},b);l.set(this._mapImage,{width:l.get(b,"width")+"px",height:l.get(b,"height")+"px"});l.set(b,"position","relative")},load:function(){function a(a){b.error=!0;a&&console.log(a);b.destroy();d.resolve()}var b=this,d=new k;if(!this._mapImageInfo.url)return a(Error("No URL specified.")),d.promise;this._mapImage.onload=function(){b.loaded=
!0;d.resolve()};this._mapImage.onerror=a;this._mapImage.src=this._mapImageInfo.url;return d.promise},destroy:function(){n.destroy(this._mapImage)}});c=c(null,{_mapDivs:null,_mapDivId:0,_mapImageInfos:null,constructor:function(){this.reset()},setArcgisUrl:function(a){a&&(y.arcgisUrl=B.combine(a,"/sharing/rest/content/items"))},reset:function(){this._mapDivs={};this._mapImageInfos=null},collectAreaMaps:function(a){var b=[];a=a||0;var d=this._mapDivs[a],c;for(c in d){var f=d[c];if(f.parentNode){var g=
v.position(f);b.push({areaIndex:a,node:f,x:g.x,y:g.y,position:-1,map:f._map,itemId:f._itemId})}}b.sort(function(b,a){return b.x-a.x});b.sort(function(b,a){return b.y-a.y});b.forEach(function(b,a){b.position=a});return b},collectAllAreasMaps:function(){var a=[],b;for(b in this._mapDivs)a=a.concat(this.collectAreaMaps(b));return a},setFallbackMapImageInfos:function(a){a?(this._mapImageInfos={},a.forEach(function(b){var a=b.areaIndex||0;(this._mapImageInfos[a]=this._mapImageInfos[a]||{})[b.itemId]=b},
this)):this._mapImageInfos=null},createMap:function(a,b){function d(e){return q.createMap(e,a,{extent:A.graphicsExtent(b.features).expand(b.expandFactor||1.5),sliderPosition:!1===b.sliderPosition?"none":b.sliderPosition||"top-right",defaultBasemapId:b.defaultBasemapId}).then(function(a){return a&&a.map?c(a.map):(new k).reject(Error("Can't create a map."))})}function c(e){var r=new x;e.addLayer(r);b.features.forEach(function(a){var b=a.getLayer(),e=b&&b.renderer&&b.renderer.getSymbol(a)||a.symbol,
c=a.geometry;e||("point"==a.geometry.type?e=new p(p.STYLE_CIRCLE,20,new m(m.STYLE_SOLID,new h([255,255,255,.7]),2),new h([255,0,0,.7])):(e=new z,e.setOutline(new m(m.STYLE_SOLID,new h([255,0,0,1]),2)),e.setColor(new h([100,100,100,.25]))));c=new w(c,e,a.attributes);c.setInfoTemplate(b&&b.infoTemplate||a.infoTemplate);r.add(c)});void 0===a.__mapDivId&&(a.__mapDivId=g._mapDivId++);a._map=e;a._itemId=b.webMapId;(g._mapDivs[f]=g._mapDivs[f]||{})[a.__mapDivId]=a;return e}b=b||{};var f=b.areaIndex||0,g=
this;return u(q.getItem(b.webMapId),function(a){if(!a)return(new k).reject(Error("Can't load an item or the item is incorrect."));var b=new k;try{d(a).then(b.resolve,b.reject)}catch(D){b.reject(D)}return b.promise}).otherwise(function(){var c=g._mapImageInfos&&g._mapImageInfos[f]&&g._mapImageInfos[f][b.webMapId],d=c&&new C(c,a);return d&&d.load().then(function(){return d.loaded?d:null})})}});c.EXPAND_FACTOR=1.5;return c});