// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProviders/supportClasses/ReportDataProcessor","dojo/_base/lang dojo/when ./tasks/EnrichAreasTask ./tasks/RunReportTask ./CustomReportsManager esri/dijit/geoenrichment/utils/DateUtil ../../core/supportClasses/templateJsonUtils/FieldInfoNameUtil".split(" "),function(l,g,m,n,h,k,p){return{populateReportDataFromAttachmentsStore:function(b,c){var a=c.getNotes();a&&a.length&&(b.fieldData.metadata.SiteNote=a[0].text,b.fieldData.metadata.SiteNotes=a.map(function(a){return a.text}).join("\x3cbr/\x3e\x3cbr/\x3e"))},
runReportAndGetData:function(b){return g(h.getCustomReportByID(b),function(c){return(new n).execute({geoenrichmentUrl:b.geoenrichmentUrl,analysisAreas:b.analysisAreas,countryID:b.countryID,hierarchy:c.hierarchy,report:{reportID:c.reportID,portalUrl:c.templateData.getPortalUrl(!0)}}).then(function(a){return{taskID:a.taskID,selectedReport:c,featureSets:a.featureSets}},function(a){b.fieldData.errors.push(a);return null})})},applyRunReportAndGetDataResults:function(b,c){if(b&&b.featureSets){c.fieldData.runReportTaskID=
b.taskID;var a,e=[];b.featureSets.forEach(function(b){b.calculatorName===c.fieldData.mainCalculatorName?a=b:e.push(b)});a&&(this._parseFeatureSet(a,c.fieldData.featureData),this._reportDataFromAreas(c.analysisAreas,c.fieldData.featureData),this._reportDataFromReport(b.selectedReport,c.fieldData))}},enrichFieldData:function(b,c){function a(a){return c.fieldData.featureData.every(function(b){return void 0!==b[a]})}var e=this,f=[],d={};b.forEach(function(b){a(b.fieldName)||(f.push(b.mapTo),d[b.mapTo.toUpperCase()]=
b.fieldName,d[b.mapTo.substr(b.mapTo.indexOf(".")+1).toUpperCase()]=b.fieldName)});if(f.length)return g(h.getCustomReportByID(c),function(a){return(new m).enrichAreas({geoenrichmentUrl:c.geoenrichmentUrl,analysisAreas:c.analysisAreas,countryID:c.countryID,hierarchy:a.hierarchy,fields:f}).then(function(a){e._parseFeatureSet(a[0],c.fieldData.featureData,function(a){var b={},c;for(c in a){var e=d[c.toUpperCase()];e&&(b[e]=a[c])}return b})},function(a){c.fieldData.errors.push(a)})})},_parseFeatureSet:function(b,
c,a){b&&b.features.forEach(function(b,f){var d=c[f],d=l.mixin(d||{},a?a(b.attributes):b.attributes);c[f]=d})},_applyFeatureSetToFieldData:function(b,c,a){this._parseFeatureSet(b,c,a)},_reportDataFromReport:function(b,c){var a=c.metadata;b&&!a.Title&&(a.Title=b.title);a.Source="Esri";a.Date=k.getReportFooterDate();a.Copyright="\u00a9"+k.getFullYear()+" Esri";a.ProductLabel="";a.ProductUrl="";a.PhoneNumber="";a.TrialUrlText=""},_reportDataFromAreas:function(b,c){b.forEach(function(a,b){var f=a.feature,
d=c[b];if(d){for(var e in f.attributes){var g=p.createFieldNameFromVariable(e);void 0===d[g]&&(d[g]=f.attributes[e])}d["headers.SITE_NAME"]=a.name||a.shortName||"";d["headers.STORE_NAME"]=a.name||a.shortName||"";d["headers.AREA_DESC"]=a.description||"";d["headers.AREA_DESC2"]=a.description||"";d["headers.AREA_DESC3"]=a.description||"";d["headers.STORE_ADDR"]=a.address||"";d["headers.STORE_LAT"]=a.latitude||"";d["headers.STORE_LONG"]=a.longitude||"";d.AREA_ID=b}})},convertReportData:function(b){var c=
this;b=b.fieldData;b.metadata=this._convertObjectToUpperCase(b.metadata);b.featureData=b.featureData.map(function(a){return c._convertObjectToUpperCase(a)})},_convertObjectToUpperCase:function(b){var c={};Object.keys(b).forEach(function(a){c[a.toUpperCase()]=b[a]});return c}}});