// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/FieldInfoBuilder",["./utils","dojo/i18n!../../../../../../nls/jsapi"],function(d,l){l=l.geoenrichment.dijit.ReportPlayer.ReportPlayer;var k={createFieldInfoFromCalculator:function(a,g,b){if(!a)return null;g=b&&b.format;var e=b&&b.autoformatCurrency;b=b&&b.additionalText;var c={triggerJson:null};c.alias=a.getDescriptionWithType()||a.getAliasWithType();var f=a.variable;c.hasVariable=!0;c.variableID=f.id;c.vintage=f.vintage;
c.fullName=f.fullName;c.fieldCategory=f.fieldCategory;var h=a.getToggleGroup&&a.getToggleGroup();c.statefulName=h?h.value:"n/"+f.fullName;h=a.getCalcType().charAt(0);c.name=d.name.createFieldNameFromVariable(f,h);d.name.provideQualifiedFieldInfoTemplateName(c);g?d.format.setFieldInfoFormat(c,g):(c.decimals=a.getDecimals(),c.showCurrency=e&&"n"==h&&f.units&&"CURRENCY"==f.units.toUpperCase(),c.showPercent="p"==h,c.useThousandsSeparator=!0);c.additionalText=b;f.isWebMap?(c.isWebMap=!0,c.webMapFieldName=
f.fieldName,c.webMapField=f.field,c.webMapId=f.webMapId,!g&&f.field&&f.field.format&&(c.decimals=f.field.format.places,c.useThousandsSeparator=f.field.format.digitSeparator)):f.customDataCollection&&(c.isCustomDataCollection=!0,c.customDataCollectionId=f.customDataCollection.id,c.customDataCollectionUrl=f.customDataCollection.url,c.customDataCollectionPortalUrl=f.customDataCollection.portalUrl);return c},createFieldInfoFromScript:function(a,g,b){g=b&&b.format;b=b&&b.additionalText;a=a||{};a.name=
a.name||d.name.DEFAULT_SCRIPT_NAME;a.alias=a.alias||l.scriptNameDefault;a.decimals=Number(a.decimals)||0;var e={triggerJson:null};e.name=d.name.createFieldNameFromScript(a);d.name.provideQualifiedFieldInfoTemplateName(e);e.script=a;g?d.format.setFieldInfoFormat(e,g):(e.decimals=Number(a.decimals),e.showCurrency=!1,e.showPercent=!1,e.useThousandsSeparator=!0);e.additionalText=b;return e},createFieldInfoFromChart:function(a){return{isChart:!0,chartJson:a}},createFieldInfoFromImage:function(a,d){return{isImage:!0,
imageJson:a,triggerJson:d}},createFieldInfoFromShape:function(a){return{isShape:!0,shapeJson:a}},createFieldInfoFromSection:function(a){return{isReportSection:!0,sectionJson:a}},createFieldInfoFromInfographic:function(a){return{isInfographic:!0,infographicJson:a}},createFieldInfoFromMissingVariable:function(a){return{isMissing:!0,variable:a,alias:a.alias}}},m=/^\[\w+\]$/,n=/\[\w+\]/;k.getFieldInfoFromLabel=function(a,g){if("string"!=typeof a)return null;a=a.trim();var b=m.test(a);if(!g||b){if(!b)return null;
a=a.replace(/\[|\]/g,"").toUpperCase();return k.createFieldInfoFromSpecialFieldName(d.fields.uiToTemplate(a))}return n.test(a)?(b=d.richText.collectFieldInfosFromRenderedXMLString(a))&&d.richText.createFieldInfoFromRichText(b.xmlString,b.fieldInfos,b.specialFieldInfos):null};k.createFieldInfoFromSpecialFieldName=function(a,g){if("string"!=typeof a)return null;var b;a=a.substr(a.indexOf(".")+1);var e=a.toUpperCase();"CURRDATE"==e?b={name:d.fields.DATE_FIELD_NAME,alias:d.fields.DATE_FIELD_ALIAS,format:g||
d.fields.DATE_FIELD_DEFAULT_FORMAT}:"SITENOTE"==e?b={name:d.fields.SITENOTE_FIELD_NAME,alias:d.fields.SITENOTE_FIELD_ALIAS}:"SITENOTES"==e&&(b={name:d.fields.SITENOTES_FIELD_NAME,alias:d.fields.SITENOTES_FIELD_ALIAS});if(b)return b;var c=d.fields.templateToUIHeader(e);c?b={name:d.fields.qualifyTemplateHeaderName(e),alias:c}:(e=d.fields.templateToUIReportVar(e))&&(b={name:e,alias:e});return b};return k});