// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/TemplateJsonModificationUtil",["dojox/uuid/generateRandomUuid","esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/DocumentOptions","esri/dijit/geoenrichment/utils/PageUnitsConverter","esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridLayoutCalculator"],function(t,p,q,r){var g={},m={getJsonStat:function(a){var b=0,c=0,d=[];a.sectionsTables.forEach(function(a){var e=0;a.data.columns.forEach(function(b){e+=
k.getFieldWidth(a,a.data.data[0],b)});b=Math.max(b,e);var g=0;a.data.data.forEach(function(b){g+=k.getDataHeight(a,b,a.data.columns[0])});c=Math.max(c,g);d.push({totalW:e,totalH:g})});return{tableInfos:d,totalWMax:b,totalHMax:c}}},k={getFieldWidth:function(a,b,c){return r.getFieldWidth({looseResize:!0},b,c)||c.style.width},getDataHeight:function(a,b,c){return r.getDataHeight({looseResize:!0},b,c.field)},getAverageFieldWidth:function(a,b){var c=0;a.data.data.forEach(function(d){c+=k.getFieldWidth(a,
d,b)});return c/a.data.data.length},getAverageDataHeight:function(a,b){var c=0;a.data.columns.forEach(function(d){c+=k.getDataHeight(a,b,d)});return c/a.data.columns.length}},n={scaleTableJsonWidth:function(a,b){a.data.columns.forEach(function(c){c.style.width*=b;a.data.data.forEach(function(a){(a=a.style.fields)&&(a=a[c.field])&&a.width&&(a.width*=b)})})},scaleTableJsonHeight:function(a,b){a.data.data.forEach(function(c){c.style.height*=b;var d=c.style.fields;d&&a.data.columns.forEach(function(a){(a=
d[a.field])&&a.height&&(a.height*=b)})})}};g.addRow=function(a,b){b=b||0;var c=1<a.sectionsTables.length,d=m.getJsonStat(a),e=a.sectionsTables[b],f=e.data.data,l=f[f.length-1],h={style:{height:k.getAverageDataHeight(e,l),fields:{}}};f.push(h);e.data.columns.forEach(function(a){var b=l.style.fields;b&&(b=b[a.field])&&b.width&&(h.style.fields[a.field]={width:b.width})});c?(d=d.tableInfos[b],n.scaleTableJsonHeight(e,d.totalH/(d.totalH+h.style.height))):g.adjustDocumentOptions(a);return{json:a,needRecalcContent:c}};
g.removeRow=function(a,b){b=b||0;var c=1<a.sectionsTables.length,d=m.getJsonStat(a),e=a.sectionsTables[b],f=k.getAverageDataHeight(e,e.data.data[e.data.data.length-1]);e.data.data.pop();c?(d=d.tableInfos[b],n.scaleTableJsonHeight(e,d.totalH/(d.totalH-f))):g.adjustDocumentOptions(a);return{json:a,needRecalcContent:c}};g.addColumn=function(a,b){b=b||0;var c=1<a.sectionsTables.length,d=m.getJsonStat(a),e=a.sectionsTables[b],f=e.data.columns,l=f[f.length-1],h={field:t(),style:{width:k.getAverageFieldWidth(e,
l)}};f.push(h);e.data.data.forEach(function(a){if(a=a.style.fields){var b=a[l.field];b&&b.height&&((a[h.field]=a[h.field]||{}).height=b.height)}});c?(d=d.tableInfos[b],n.scaleTableJsonWidth(e,d.totalW/(d.totalW+h.style.width))):(e.style.width+=h.style.width,g.adjustDocumentOptions(a));return{json:a,needRecalcContent:c}};g.removeColumn=function(a,b){b=b||0;var c=1<a.sectionsTables.length,d=m.getJsonStat(a),e=a.sectionsTables[b],f=e.data.columns,l=k.getAverageFieldWidth(e,f[f.length-1]);f.pop();c?(d=
d.tableInfos[b],n.scaleTableJsonWidth(e,d.totalW/(d.totalW-l))):(e.style.width-=l,g.adjustDocumentOptions(a));return{json:a,needRecalcContent:c}};g.recalcTemplateJsonDimensions=function(a,b,c){m.getJsonStat(a).tableInfos.forEach(function(d,e){if(void 0!==b){var f=b/d.totalW;n.scaleTableJsonWidth(a.sectionsTables[e],f)}void 0!==c&&(f=c/d.totalH,n.scaleTableJsonHeight(a.sectionsTables[e],f))})};g.adjustDocumentOptions=function(a){if(a.documentOptions){var b=m.getJsonStat(a);if(!isNaN(b.totalWMax)&&
!isNaN(b.totalHMax)){a=a.documentOptions;var c=a.top+a.bottom+b.totalHMax;a.pagesize=p.combineCustomSizeString(q.pxToIn(a.left+a.right+b.totalWMax),q.pxToIn(c));(b=p.getClosestStandrdSizes(a)[0])&&.001>b.score&&b.orientation===a.orientation&&(a.pagesize=b.pagesize)}}};g.findUnfitPages=function(a){if(!a.documentOptions)return[];var b=p.getPageBox(a.documentOptions),c=[];m.getJsonStat(a).tableInfos.forEach(function(a,e){(.1<Math.abs(a.totalW-b.contentW)||.1<Math.abs(a.totalH-b.contentH))&&c.push(e)});
return c};return g});