// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/ChartBuilder","dojo/_base/declare dojo/_base/lang dojo/has dojox/gfx dojox/charting/axis2d/Default dojox/charting/plot2d/Lines ./ThemeCalculator ./ChartTypes ./ChartSorting ../../supportClasses/templateJsonUtils/FieldInfoRenderer ../../supportClasses/templateJsonUtils/FieldInfoNameUtil ../../supportClasses/conditionalStyling/ConditionalStyleUtil ./plots/ClusteredColumns ./plots/StackedColumns ./plots/ClusteredBars ./plots/StackedBars ./plots/Donut ./plots/Pie ./plots/Ring ./plots/PictureClusteredColumns ./plots/PictureClusteredBars ../../themes/ReportThemes ./CustomGridPlot ./AxisUtil esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/ObjectUtil".split(" "),
function(ga,l,ha,ia,ja,ka,v,g,A,O,J,B,P,Q,R,S,T,U,E,V,W,X,Y,Z,K,q){function aa(a,c){return void 0===a?c:a}function F(a,c,b,d,f,h,e){e=e||L;f.dynamicReportInfo?(a.fieldName||(a.fieldName=a.calculator?J.createFieldNameFromVariable({fullName:a.calculator.substr(a.calculator.indexOf("/")+1)},a.calculator.charAt(0)):J.createFieldNameFromScript(a.script)),(c=O.getFieldDataValue({name:a.fieldName},f.dynamicReportInfo.fieldData,h)||0)||console.log(a.fieldName)):(c=e[c%e.length],G[b]||(G[b]=.5+(.3-.6*Math.random())),
b=c*=G[b],a=a.calculator&&a.calculator.charAt(0),"p"==a&&(b=Number((b/20).toFixed(1))),"i"==a&&(b=Number((b/15).toFixed(1))),c=b);return c}function M(a,c){var b=L.slice();b.length=Math.min(b.length,c);var d=-Infinity;b.forEach(function(a){d=Math.max(d,a)});var f=1.1*a.max/d;return b=b.map(function(a){return a*f})}function N(a,c,b,d,f){var h=-1!=d.dataLabels.indexOf("Label"),e=-1!=d.dataLabels.indexOf("Value"),m=-1!=d.dataLabels.indexOf("Percent"),k="";if(f==g.RING)h&&(k+=c),e&&(k+=(h?E.LABEL_SEPARATOR:
"")+q.formatNumber(a,d.dataLabelsDecimals,!0)),m&&(k+=(h?E.LABEL_SEPARATOR:"")+(q.formatNumber(a/b*100,d.dataLabelsDecimals,!0)+"%"));else if(h||e||m)f=0,k="",h&&(k+="\x3cdiv\x3e"+c+"\x3c/div\x3e",f++),e&&(k+="\x3cdiv\x3e"+q.formatNumber(a,d.dataLabelsDecimals,!0)+"\x3c/div\x3e",f++),m&&(k+="\x3cdiv\x3e"+(q.formatNumber(a/b*100,d.dataLabelsDecimals,!0)+"%")+"\x3c/div\x3e",f++),k="\x3cdiv two-row-label\x3d'"+(1<f)+"'\x3e"+(k+"\x3c/div\x3e");return k}function H(a,c,b,d,f,h,e,g,k,l){function m(a,b){return q.formatNumber(a||
0,b||e.dataLabelsDecimals,!0)}return{color:k,label:c,seriesLabel:b,valueLabel:m(a),sumValueLabel:m(f),maxValueLabel:m(d),avgValueLabel:m(h),percentLabel:m(a/f*100)+"%",showPercent:-1!=e.dataLabels.indexOf("Percent"),value:a,conditionalStyling:l,getGroup:null}}function ca(a,c,b,d,f){a=288*d/680/(a+1);"Small"==b?a*=.5:"Large"==b&&(a*=1.5);return a/(f?1:c)}var C={},L=[1E3,1200,500,150,70,900,110,300,80,200,1700],G=[1,.7,1.2,.5,1.1,1.3,.3,2,.4],ea={configureChart:function(a){var c=a.chart,b=a.visualProperties,
d=a.chartType,f=a.themeSettings,h=a.viewModel;c._pointIndexToLabelMap={};var e=l.mixin({},f.xAxis.axisStyle,b.xAxis.style),e=K.toColor(e.color||"#000000");e.a=aa(b.yAxis.gridLinesOpacity,1);e=K.toCSSColor(e);c.addPlot("grid",{type:Y,vMajorLines:b.yAxis.gridLines,majorVLine:{color:e,width:.5},vMinorLines:!1,hMajorLines:b.xAxis.gridLines,majorHLine:{color:e,width:.5},hMinorLines:!1});e=c.getPlot("grid");e.xHasHalfTickOffset=b.yAxis.gridLinesCentered;e.yHasHalfTickOffset=b.xAxis.gridLinesCentered;var e=
{gap:50},m=-1!=b.dataLabels.indexOf("Label"),k=-1!=b.dataLabels.indexOf("Value"),ba=-1!=b.dataLabels.indexOf("Percent"),p=b.dataLabelsInside?"inside":"outside",m=m||k||ba?{precision:0,labels:!0,labelStyle:p,htmlLabels:!0,labelOffset:5,labelFunc:function(a){return N(a.y,a.name,a._valuesSumsInSeries,b)}}:null,k=h.dynamicReportInfo&&h.chartAnimationAllowed?{animate:{duration:600}}:null;switch(d){case g.COLUMN:c.addPlot("default",l.mixin({type:b.isStacked?Q:P},e,m,k));break;case g.BAR:c.addPlot("default",
l.mixin({type:b.isStacked?S:R},e,m,k));break;case g.LINE:c.addPlot("default",l.mixin({type:"Lines",markers:h.reportStyle==X.GRAPHIC},k));break;case g.PICTURE_COLUMN:c.addPlot("default",l.mixin({type:V},e,m,k));break;case g.PICTURE_BAR:c.addPlot("default",l.mixin({type:W},e,m,k))}c.movePlotToBack("grid");c.addAxis("x",this._createXAxis(null,b,d,f,c));c.addAxis("y",this._createYAxis(null,b,d,f));this.updateBarSize(a)},updateBarSize:function(a){var c=a.chart,b=a.visualProperties,d=a.seriesItems;if(c&&
a.chartType!=g.LINE){a=a.chartSize||b[a.chartType==g.COLUMN?"width":"height"];var f=0;d.forEach(function(a){f=Math.max(f,a.points.length)});b=ca(f,d.length,b.columnThickness,a,b.isStacked);c.getPlot("default").opt.maxBarSize=b;c.getPlot("default").opt.minBarSize=b}},_createXAxis:function(a,c,b,d,f){c=c.xAxis;var h="OtherSide"!=c.placement,e=l.mixin({},d.xAxis.axisStyle,c.style);d=l.mixin({},d.xAxis.titleStyle,c.titleStyle);b=b===g.BAR||b===g.PICTURE_BAR;b={stroke:e.color,title:c.title,titleOrientation:!b&&
h?"away":"axis",titleFont:v.combineFontString(d),titleFontColor:d.color,vertical:b,leftBottom:h,majorTicks:!0,majorTick:{length:c.show&&c.showTicks?5:0,color:e.color},majorTickStep:1,minorTicks:!1,microTicks:!1,minorTickStep:.5,microTickStep:.01,font:v.combineFontString(e),fontColor:e.color,dropLabels:!1,majorLabels:c.show,minorLabels:!1,labelFunc:function(a,b,c){b=f._pointIndexToLabelMap&&f._pointIndexToLabelMap[b];return void 0!==b?b:a},rotation:-c.labelsAngle||0};return l.mixin(b,a)},_createYAxis:function(a,
c,b,d){c=c.yAxis;var f="OtherSide"!=c.placement,h=l.mixin({},d.yAxis.axisStyle,c.style);d=l.mixin({},d.yAxis.titleStyle,c.titleStyle);b=b===g.BAR||b===g.PICTURE_BAR;b={fixUpper:"major",includeZero:!0,stroke:h.color,title:c.title,titleOrientation:b&&f?"away":"axis",titleFont:v.combineFontString(d),titleFontColor:d.color,vertical:!b,leftBottom:f,majorTicks:!0,majorTick:{length:c.show&&c.showTicks?5:0,color:h.color},majorTickStep:200,minorTicks:!1,microTicks:!1,minorTickStep:100,microTickStep:10,font:v.combineFontString(h),
fontColor:h.color,dropLabels:!1,majorLabels:c.show,minorLabels:!1,rotation:-c.labelsAngle||0};return l.mixin(b,a)},calcSeries:function(a){return a.chartType==g.LINE?this._calcSeriesLine(a):this._calcSeriesColumnBar(a)},_updatePointIndexToLabelMap:function(a,c,b){var d=a._pointIndexToLabelMap[c];if(void 0===d||""===d)a._pointIndexToLabelMap[c]=b.label},_calcSeriesColumnBar:function(a){var c=a.chart,b=a.visualProperties,d=a.seriesItems,f=a.chartType,h=a.themeSettings,e=a.viewModel,g=a.previewFeatureIndex,
k=a.isMultiFeatureChart,l=a.excludedSeriesHash,p=1==d.length&&a.sorting,t=this,r=0,z=[],n;b.isStacked&&(n=[]);c._pointIndexToLabelMap={};var D={},w;b.conditionalStyling&&(a=B.getStatistics(b.conditionalStyling))&&d.length&&(w=M(a,d[0].points.length));d.forEach(function(a,m){if(a.points.length){var u={name:a.label,data:[]},y=[],x=0,I=0;a.points.forEach(function(b,c){var d=F(b,c,m,!1,e,k?c:g,w);y[c]=d;l&&l[a.label]||(n?(n[c]=n[c]||0,n[c]+=d):r=Math.max(d,r),x+=d,I=Math.max(I,d))});var da=x/a.points.length;
a.points.forEach(function(c,e){var k=y[e]||0,g=e+1,l;b.conditionalStyling&&(l=(l=B.getConditionalStyle(k,b.conditionalStyling))&&l.backgroundColor);l=l||v.calcColorForPoint(c,a,e,m,d.length,f,h);var n=H(k,c.label,a.label,I,x,da,b,f,l,b.conditionalStyling),w=D[g]=D[g]||[];w.push(n);n.getGroup=function(){return w};u.data.push({x:g,y:k,unsortedIndex:e,name:c.label||"",_valuesSumsInSeries:x,point:c,fill:l,tooltip:n,stroke:{width:0}})});p&&p!=A.NONE&&(u.data.sort(function(a,b){return(a.y-b.y)*(p==A.DESC?
-1:1)}),u.data.forEach(function(a,b){a.x=b+1}));u.data.forEach(function(a){t._updatePointIndexToLabelMap(c,a.x,a.point)});z.push(u)}});n&&(n.sort(function(a,b){return b-a}),r=n[0]);this._prettifyYAxis(r,c,b,f,h);return z},_calcSeriesLine:function(a){var c=a.chart,b=a.visualProperties,d=a.seriesItems,f=a.chartType,h=a.themeSettings,e=a.viewModel,g=a.previewFeatureIndex,k=a.isMultiFeatureChart,l=this,p=0,t=[],r={};d.forEach(function(a,m){if(a.points.length){var n=v.calcColorForPoint(null,a,0,m,d.length,
f,h),w={name:a.label,data:[],params:{stroke:{color:n,width:b.lineThickness||1}}},x=[],y=0,u=0;a.points.forEach(function(a,b){var c=F(a,b,m,!1,e,k?b:g);x[b]=c;p=Math.max(c,p);y+=c;u=Math.max(u,c)});var q=y/a.points.length;a.points.forEach(function(d,e){var h=x[e],k=e+1;l._updatePointIndexToLabelMap(c,k,d);var g=H(h,d.label,a.label,u,y,q,b,f,n),m=r[k]=r[k]||[];m.push(g);g.getGroup=function(){return m};w.data.push({x:k,y:h,name:d.label||"",_valuesSumsInSeries:y,point:d,fill:n,tooltip:g})});t.push(w)}});
this._prettifyYAxis(p,c,b,f,h);return t},_prettifyYAxis:function(a,c,b,d,f){b.yAxis.show&&(c.removeAxis("y"),c.addAxis("y",this._createYAxis(Z.getPrettifyYAxisParameters(a),b,d,f)))}},fa={configureChart:function(a){a.chart.addPlot("default",this._createPiePlot(a.visualProperties,a.themeSettings,a.viewModel,a.chartType))},_createPiePlot:function(a,c,b,d){var f=-1!=a.dataLabels.indexOf("Label"),h=-1!=a.dataLabels.indexOf("Value"),e=-1!=a.dataLabels.indexOf("Percent");c=l.mixin({},c.dataLabelsStyle,
a.dataLabelsStyle);a=f||h||e?{labelStyle:a.dataLabelsStackedInColumns?"columns":a.dataLabelsInside?"inside":"outside",htmlLabels:!0,font:v.combineFontString(c),fontColor:c.color,omitLabels:!a.dataLabelsStackedInColumns}:{labels:!1};return l.mixin({type:d==g.RING?E:d==g.DONUT?T:U,fontColor:"black"},a,b.dynamicReportInfo&&b.chartAnimationAllowed?{animate:{duration:600}}:null)},calcSeries:function(a){var c=a.seriesItems,b=a.chartType,d=a.themeSettings,f=a.viewModel,h=a.visualProperties,e=a.previewFeatureIndex,
l=a.sorting;a=[];var k=c[0],q={name:"data",data:[]},p=[],t=0,r=0,z;if(b==g.RING&&h.conditionalStyling){var n=B.getStatistics(h.conditionalStyling);n&&k&&(z=M(n,k.points.length))}k.points.forEach(function(a,b){var c=F(a,b,0,!1,f,e,z);t+=c;p[b]=c;r=Math.max(r,c)});var D=t/k.points.length;k.points.forEach(function(a,e){var f=p[e],g;C.supportConditionalStyling(b)&&h.conditionalStyling&&(g=(g=B.getConditionalStyle(f,h.conditionalStyling))&&g.backgroundColor);g=g||v.calcColorForPoint(a,k,e,0,c.length,b,
d);q.data.push({x:1,y:Math.max(1E-4,f),name:a.label,point:a,fill:g,text:N(f,a.label,t,h,b),tooltip:H(f,a.label,null,r,t,D,h,b,g,h.conditionalStyling),stroke:{width:0}})});b==g.RING&&l&&l!=A.NONE&&q.data.sort(function(a,b){return(a.y-b.y)*(l==A.DESC?-1:1)});a.push(q);return a}};C.supportConditionalStyling=function(a){return a===g.COLUMN||a===g.BAR||a===g.RING};C.getChartBuilder=function(a){return a==g.PIE||a==g.DONUT||a==g.RING?fa:ea};return C});