// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/themes/ThemeLibrary","dojo/_base/lang ./BorderStyles ./ReportThemes ./ThemeUtil esri/dijit/geoenrichment/utils/ObjectUtil dojo/i18n!../../../../../nls/jsapi".split(" "),function(g,m,f,n,p,q){function h(a){a=a==f.CLASSIC?"Verdana":"Avenir Next";return{backgroundColor:"#FFFFFF",icon:{backgroundColor:"#56a5d8"},highlightedIcon:{backgroundColor:"#D6851A"},iconBarBackground:{backgroundColor:"#AAAAAA"},titleLine:{color:"#A8A7A8"},titleStyle:{fontFamily:a,
color:"#828282",fontSize:16,backgroundColor:"transparent"},variableLabelStyle:{fontFamily:a,color:"#56a5d8",fontSize:24,backgroundColor:"transparent"},variableDescriptionStyle:{fontFamily:a,color:"#828282",fontSize:13,backgroundColor:"transparent"}}}function k(){return{style:m.ALL,lineStyle:"dashed",thickness:1,color:"#b2b2b2"}}var b={DEFAULT_FONT_FAMILY_CLASSIC:"Verdana",DEFAULT_FONT_FAMILY_GRAPHIC:"Avenir Next",defaultStaticInfographic:h(),standardRamps:[{id:f.CLASSIC,colors:["#FFFFFF","#13729F",
"#DEA429"],additional:{table:{Default:{color:"#4C4C4C",backgroundColor:"#FFFFFF"},ReportTitle:{color:"#FFFFFF",backgroundColor:"#00436D"},TableHeader:{color:"#4C4C4C",backgroundColor:"#CCCCCC"},GreyText:{color:"#AAAAAA",backgroundColor:"#FFFFFF"},BlueText:{color:"#00436D",backgroundColor:"#FFFFFF"},AlternatingRow:{color:"#4C4C4C",backgroundColor:"#EEEEEE"}},chart:{renderSingleDataSeriesWithSameColor:!1,colors:"#13729F #DEA429 #6A9741 #A75523 #456E35 #D7DF22 #868686 #3C546D #829AB3 #DEDEDE #03406E #B1B1B1".split(" ")}}},
{id:f.GRAPHIC,colors:["#FFFFFF","#56A5D8","#D6851A"]},{id:"orange",colors:["#d3d3d3","#8b4513","#ff4500"]},{id:"dark",colors:["#6A6A6A","#FFFFFF","#EEEEEE"],additional:{chart:{ring:{colors:["#6B1010"]}}}},{id:"green2",colors:["#556b2f","#90ee90","#ffffe0"]},{id:"green",colors:["#FFFFFF","#0B7AC0","#35AC46"]}]},e={};b.standardRamps.forEach(function(a){var l=g.mixin({},a.additional);l.id=a.id;var c;c=a.id;var d=c==f.CLASSIC?"Verdana":"Avenir Next";c={document:{fontSize:10,fontFamily:d,backgroundImage:{data:null,
position:"center",repeat:!1,scale:!0,opacity:1},border:k()},chart:{renderSingleDataSeriesWithSameColor:!0,line:{},column:{},bar:{},pie:{},donut:{},ring:{},pictureColumn:{},pictureBar:{},titleStyle:{fontFamily:d,fontSize:16},dataLabelsStyle:{fontFamily:d,fontSize:10},xAxis:{axisStyle:{fontFamily:d,fontSize:9},titleStyle:{fontFamily:d,fontSize:10}},yAxis:{axisStyle:{fontFamily:d,fontSize:9},titleStyle:{fontFamily:d,fontSize:10}},legendStyle:{fontFamily:d,fontSize:10},icon:{backgroundColor:"#56a5d8"}},
infographic:{staticInfographic:h(c)}};n.applyThemeColorsToTheme(c,a.colors);p.populateObject(c,l,!0);b[a.id]=c;e[a.id]=c});b.TABLE_STYLES="Default ReportTitle TableHeader GreyText BlueText AlternatingRow".split(" ");b.getReportThemeById=function(a){return e[a]};b.isStandardTheme=function(a){return!!e[a]};b.getStandardThemes=function(){return Object.keys(e).map(function(a){return e[a]})};b.getDefaultStaticInfographicSettings=function(){return g.clone(b.defaultStaticInfographic)};b.getDefaultBorderSettings=
function(){return k()};return b});