// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProviders/_SerializationSupport","dojo/_base/declare dojo/_base/lang dojo/when dojo/promise/all ./supportClasses/AnalysisAreaJsonUtil ./supportClasses/AreasPreprocessor ./supportClasses/ReportDataProcessor ../core/supportClasses/templateJsonUtils/TemplateJsonSerializer ../core/conversion/PortalToEditorConverter ../core/themes/ThemeLibrary ../core/themes/ReportThemes".split(" "),function(p,q,f,e,m,r,h,n,t,u,v){var k={getAttachmentsStoreJson:function(a){return a?
e([a.getAttachments(),a.getAttributes(),a.getNotes()]).then(function(a){var b=a[0]||[],c=a[1]||[],d=a[2]||[];return e(b.map(function(a){return e([a.getThumbnail(),a.getAttachmentUrl()]).then(function(b){a.__thumbnail=b[0];a.__url=b[1]})})).then(function(){return{attachments:b.map(function(a){var b=a.__thumbnail,c=a.__url;delete a.__thumbnail;delete a.__url;return{description:a.description,thumbnail:b,url:c}}),attributes:c.map(function(a){return{value:a.value,alias:a.alias}}),notes:d.map(function(a){return{text:a.text}})}})}):
null},getAttachmentsStoreFromJson:function(a){return a?{getAttachments:function(){return a.attachments?a.attachments.map(function(a){return{description:a.description,getThumbnail:function(){return a.thumbnail},getAttachmentUrl:function(){return a.url}}}):[]},getAttributes:function(){return a.attributes||[]},getNotes:function(){return a.notes||[]}}:null}};return p(null,{reportDataToJson:function(a,d){d=d||{};return f(k.getAttachmentsStoreJson(a.attachmentsStore),function(b){var c=q.mixin({},a.config);
!1!==d.forceFixedDataMode&&(c.geoenrichmentUrl="");var e=a.isClassic,g=a.theme,w=a.reportType,f=a.reportTitle,h=n.serialize(a.templateJson),k={},l;for(l in a.reportObject)a.reportObject[l]&&"object"!==typeof a.reportObject[l]&&(k[l]=a.reportObject[l]);return{isClassic:e,theme:g,reportType:w,reportTitle:f,templateJson:h,reportObject:k,fieldData:a.fieldData,analysisAreas:m.areasToJson(a.analysisAreas),infographicOptions:a.infographicOptions&&a.infographicOptions.toJson(),attachmentsStore:b,config:c,
mapImageInfos:d.mapImageInfos}})},reportDataFromJson:function(a){return{isClassic:a.isClassic,theme:a.theme,reportType:a.reportType,reportTitle:a.reportTitle,templateJson:n.deserialize(a.templateJson),reportObject:a.reportObject,fieldData:a.fieldData,analysisAreas:m.areasFromJson(a.analysisAreas),infographicOptions:a.infographicOptions&&this._infographicOptionsProvider.getInfographicOptionsFromJson(a.infographicOptions),attachmentsStore:a.attachmentsStore&&k.getAttachmentsStoreFromJson(a.attachmentsStore),
config:a.config,mapImageInfos:a.mapImageInfos}},_reportDataFromServerData:function(a){var d=this;return e([function(){var b={isGraphicReport:!0,portalJson:{files:a.files}};return f(t.provideEditorJson(b),function(){b.templateJson=n.deserialize(b.templateJson);delete b.portalJson;return b})}(),function(){var b={analysisAreas:m.areasFromJson(a.studyAreas.map(function(a){return{feature:{geometry:a.geometry}}}))};return f(r.preprocessAreas(b,{generalize:!1,provideFeaturesForGeographies:!1,symbolizeAreas:!0}),
function(){return b.analysisAreas})}()]).then(function(b){var c=b[0],e=c.templateJson;b=b[1];var g={metadata:{},featureData:[],additionalCalcHash:{},errors:[]};h._applyFeatureSetToFieldData(a.featureSets[0],g.featureData);h._reportDataFromAreas(b,g.featureData);h._reportDataFromReport(c,g);var f;f=d._infographicOptionsProvider.getInfographicOptions({geoenrichmentUrl:"geUrl",countryID:"countryID",reportID:"reportID",analysisAreas:b});return{isClassic:!1,theme:e.theme||u.getReportThemeById(v.GRAPHIC),
templateJson:e,reportObject:c,fieldData:g,analysisAreas:b,infographicOptions:f,config:{portalUrl:a.portalUrl}}})},_reportDataToServerData:function(a){var d=a.analysisAreas.map(function(a){return{geometry:a.feature.geometry.toJson()}}),b=[{features:a.fieldData.featureData.map(function(a){return{attributes:a}})}];return a.reportObject.templateData.getFiles().then(function(c){return{portalUrl:a.config.portalUrl,studyAreas:d,featureSets:b,files:c}})}})});