// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/playerSupports/_ReportContainersSwitcher",["dojo/_base/declare","dojo/when","dojo/dom-class","esri/dijit/geoenrichment/utils/DomUtil"],function(h,l,k,m){var n={createContainer:function(a,c,b){function f(){return g.layoutBuilder.createElement("classic"==a?"reportContainer":"reportContainerGrid",{viewModel:g,isSourceContainer:!0,isDynamicReportMode:!0,onPendingDataApplied:function(){b._emitResizedEvent()},renderOptions:{center:!0,minTop:10}},b.reportContainerDiv)}
function d(){return g.layoutBuilder.createElement("reportContainerPagination",{viewModel:g,onResized:function(a){b._emitResizedEvent(a)},onPendingDataApplied:function(){b._emitResizedEvent()}},b.reportContainerDiv)}var g=b._viewModel,e=b.__containerDict.getContainer(a,c);e||(e="pagination"==a?d():f(),b.own(e));b.__containerDict.setContainer(e,a,c);return e}},p=h(null,{_containersHash:null,constructor:function(){this._containersHash={}},_getInfo:function(a,c,b,f){a=this._containersHash[a]=this._containersHash[a]||
[];var d=a[c];!d&&f&&(d=a[c]={container:f,loaded:!1});return b?d&&d[b]:d},getContainer:function(a,c){return this._getInfo(a,c,"container")},setContainer:function(a,c,b){this._getInfo(c,b,null,a)},isLoaded:function(a,c){return this._getInfo(a,c,"loaded")},setLoaded:function(a,c){var b=this._getInfo(a,c);b&&(b.loaded=!0)},resetAllLoaded:function(){for(var a in this._containersHash)this._containersHash[a].forEach(function(a){a.loaded=!1})}});return h(null,{__containerDict:null,postCreate:function(){this.__containerDict=
new p;this.inherited(arguments)},getCurrentReportContainer:function(){return this._currentReportContainer},__getCurrentViewType:function(){return this.isSlidesView?"pagination":this._reportData.isClassic?"classic":"graphic"},_setReportContainer:function(a){var c=this;a?this._resetLoadedFlags():this.__rememberCurrentContainerVisuals();this.__switchToCurrentReportContainer();return!a&&this.__isCurrentContainerLoaded()?l(this._resize({isPaginating:!0}),function(){c.__applyCurrentContainerVisuals();return!1}):
!0},__switchToCurrentReportContainer:function(){this._currentReportContainer&&this._hideContainer(this._currentReportContainer);var a=this.__getCurrentViewType();this._currentReportContainer=n.createContainer(a,this.getCurrentAnalysisAreaIndex(),this);k["pagination"==a?"add":"remove"](this.domNode,"esriGEReportPlayerPaginationView");k["pagination"==a?"remove":"add"](this.domNode,"esriGEReportPlayerFullView");this._showContainer(this._currentReportContainer);this._currentReportContainer.setViewMode&&
this._currentReportContainer.setViewMode("previewValues");this.notifyShown()},_hideContainer:function(a){a.__undoHideContainerHandle=m.hideNodeInBackground(a.domNode)},_showContainer:function(a){a.__undoHideContainerHandle&&(a.__undoHideContainerHandle.undo(),delete a.__undoHideContainerHandle)},_resetLoadedFlags:function(){this.__lastVisuals=null;this.__containerDict.resetAllLoaded()},__isCurrentContainerLoaded:function(){return this.__containerDict.isLoaded(this.__getCurrentViewType(),this.getCurrentAnalysisAreaIndex())},
_setCurrentContainerLoaded:function(){this.__applyCurrentContainerVisuals();this.__containerDict.setLoaded(this.__getCurrentViewType(),this.getCurrentAnalysisAreaIndex())},__lastVisuals:null,__rememberCurrentContainerVisuals:function(){if(this._currentReportContainer){var a=this._currentReportContainer;this.__lastVisuals={type:this.__getCurrentViewType(),scrollTop:a.getScrollableContainer&&a.getScrollableContainer().scrollTop||0,pageIndex:a.getCurrentPageIndex&&a.getCurrentPageIndex()||0,slideIndex:a.getCurrentSlideIndex&&
a.getCurrentSlideIndex()||0,zoomInfo:a.getZoomInfo&&a.getZoomInfo()}}else this.__lastVisuals=null},__applyCurrentContainerVisuals:function(){if(this.__lastVisuals)if(this.__lastVisuals.type!==this.__getCurrentViewType())this.__lastVisuals=null;else{var a=this._currentReportContainer;a.getScrollableContainer&&(a.getScrollableContainer().scrollTop=this.__lastVisuals.scrollTop||0);a.showSlideAt&&a.showSlideAt(this.__lastVisuals.slideIndex||0);a.showPageAt&&a.showPageAt(this.__lastVisuals.pageIndex||
0);a.setZoomInfo&&a.setZoomInfo(this.__lastVisuals.zoomInfo)}}})});