// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ReportContainer.html":'\x3cdiv class\x3d"esriGEReportPlayer_reportContainer esriGENonSelectable"\x3e\r\n    \x3cdiv\x3e\r\n        \x3cdiv class\x3d"horizontalRulerContainer" data-dojo-attach-point\x3d"horizontalRulerContainer"\x3e\r\n            \x3cdiv class\x3d"horizontalRuler" data-dojo-attach-point\x3d"horizontalRuler"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"mainContainer" class\x3d"reportContainer_mainContainer"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"stackContainer" class\x3d"reportContainer_stackContainer"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainers/ReportContainer","dojo/_base/declare dojo/_base/lang dojo/on dojo/dom-construct dojo/dom-class dojo/dom-geometry dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin ../grid/ValueField ./containerUtils/QueryUtil ./containerUtils/SerializationManager ../supportClasses/DocumentOptions esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes dojo/text!../templates/ReportContainer.html".split(" "),
function(n,k,x,e,g,p,d,q,r,t,h,u,v,l,m,w){return n([q,r],{templateString:w,viewModel:null,themeContext:null,theme:null,documentOptions:null,_sampleWatermarkDiv:null,queryUtil:h,serializationManager:null,postCreate:function(){this.inherited(arguments);this.serializationManager=(new this._getSerializationManagerClass)(this);this.updateLayout();this.setViewMode(null)},_getSerializationManagerClass:function(){return u},_sectionWidth:0,setDocumentOptions:function(a){this.documentOptions&&k.mixin(this.documentOptions,
a);this.updateLayout()},updateLayout:function(){if(this.documentOptions){this._sectionWidth=v.getPageBox(this.documentOptions).contentW-2;this._updateContainerSize();d.set(this.stackContainer,{paddingLeft:(this.documentOptions.left||0)+"px",paddingRight:(this.documentOptions.right||0)+"px",paddingTop:(this.documentOptions.top||0)+"px",paddingBottom:(this.documentOptions.bottom||0)+"px"});var a=this;this.getReportElements("setWidth").forEach(function(b){a.getElementSection(b).setWidth(a._getSectionWidth(),
{resizeContentToFit:!0,preserveRightOffset:!0})})}},_updateContainerSize:function(){d.set(this.stackContainer,"width",this._sectionWidth+("edit"==this._viewMode?145:0)+"px");d.set(this.mainContainer,"height",d.get(this.domNode,"height")+("edit"==this._viewMode?-17:0)+"px")},_getSectionWidth:function(){return this._sectionWidth},resize:function(a,b){void 0!==a&&d.set(this.domNode,{width:a+"px",height:b+"px"});this._updateContainerSize()},getCanvasOffsets:function(){var a=d.get(this.domNode,"width"),
b=d.get(this.stackContainer,"width")+p.getPadBorderExtents(this.stackContainer).w;return{l:Math.max(15,this.stackContainer.offsetLeft),r:Math.max(10,a-(this.stackContainer.offsetLeft+b))}},getFullWidth:function(){return Math.max(this.stackContainer.scrollWidth,d.get(this.stackContainer,"width"))},getFullHeight:function(){return Math.max(this.stackContainer.scrollHeight,d.get(this.stackContainer,"height"))},addSection:function(a,b,c,d,e){var f=this._createSectionCell(a);this._createSection(a,b,f);
a=this._createReportElement(a,f,c,d,b&&b.json,e);this.updateReportElement(a);return a},_createSection:function(a,b,c){b=b||{};b["class"]="reportContainer_Section";b.initialWidth=this._getSectionWidth();b.viewModel=this.viewModel;b.themeContext=this.themeContext;b.theme=this.theme;"empty"==a?a=this.viewModel.layoutBuilder.createElement("emptySection",b,c.getContentContainerNode()):(a=this.viewModel.layoutBuilder.createElement("section",b,c.getContentContainerNode()),(b=this.documentOptions.backgroundColor||
this.viewModel.getDocumentDefaultStyles(this.theme||this.themeContext).backgroundColor)&&d.set(a.domNode,"backgroundColor",b));c.setContent(a);return a},_getSectionCellClass:function(){return t},_getSectionCellParams:function(){return null},_createSectionCell:function(a){return(new this._getSectionCellClass)(k.mixin({sectionId:a,"class":"reportContainerCell"},this._getSectionCellParams()))},_createReportElement:function(a,b,c,d,g,h){var f=e.create("div",{"class":"reportElement"}),k=this._getCellSection(b);
a=f._fcPar={isReportElement:!0,sectionId:a,isEmpty:"empty"==a,sectionJson:this.isSourceContainer&&g,controls:[],cell:b,section:k,dragHandleElement:null,coverElement:null,sectionToolbar:null,sectionLabel:null};e.place(f,c?c:this.stackContainer,c?d:void 0);a.sectionLabel=e.create("div",{"class":"reportElementLabel",innerHTML:k.getSectionName()},f);b.rulerDiv=e.create("div",{"class":"reportElementRuler"},f);e.place(b.domNode,f);this._updateCellRuler(b);this.isEmptyElement(c)&&!1!==h&&(this._removeSection(c),
this._tryProvidingSmallEmpty(f));this.viewModel.dynamicReportInfo||(a.coverElement=e.create("div",{"class":"reportElement_coverElement"},f),l.hide(a.coverElement));return f},updateReportElement:function(a){var b=this.getElementParams(a);this._sectionToSectionCell(b.cell);this._sectionCellToSection(b.cell);this._updateChildrenViewMode(a);b.sectionToolbar&&b.sectionToolbar.update();b.sectionLabel&&b.section&&(b.sectionLabel.innerHTML=b.section.getSectionName())},_sectionCellToSection:function(a){this._getCellSection(a).setResizedHeight(a.getHeight());
this._updateCellRuler(a)},_sectionToSectionCell:function(a){var b=this._getCellSection(a);a.setMinHeight(b.hasTablesThatFitHeight&&b.hasTablesThatFitHeight()?20:b.getHeight());a.setHeight(b.getResizedHeight());this._updateCellRuler(a)},_updateCellRuler:function(a){d.set(a.rulerDiv,"height",d.get(a.domNode,"height")+"px")},_setChildCovered:function(a,b){var c=this.getElementParams(a,"coverElement");c&&(l[b?"show":"hide"](c),b?(a[this.draggableElementProperty]=c,d.set(c,{position:"absolute",left:"0px",
top:"0px",width:d.get(a,"width")+"px",height:d.get(a,"height")+"px"})):a[this.draggableElementProperty]=this.getElementParams(a,"dragHandleElement"))},_tryProvidingSmallEmpty:function(a){var b=this;this.getReportElements().filter(function(a){return b.isEmptyElement(a)}).length||this.addSection(m.EMPTY,{isSmallSize:!0},a,"after")},getElementHeight:function(a){return this.getElementCell(a).getHeight()},setElementHeight:function(a,b){var c=this.getElementCell(a);c.setHeight(b);this._sectionCellToSection(c);
this.updateReportElement(a)},getElementParams:function(a,b){var c=a&&a._fcPar;return b?c&&c[b]:c},getElementSection:function(a){return this.getElementParams(a,"section")},getElementCell:function(a){return this.getElementParams(a,"cell")},isEmptyElement:function(a){return!!this.getElementParams(a,"isEmpty")},isReportElement:function(a){return this.getElementParams(a)},_getCellSection:function(a){return a.content},scrollToElement:function(a){a&&this._animateScrolling(a.offsetTop-this.domNode.clientHeight/
5)},_animateScrolling:function(a){this.getScrollableContainer().scrollTop=a},getScrollableContainer:function(){return this.mainContainer},getReportElements:function(a){return h.getReportElements(this,a)},clear:function(a){var b=this;this.getReportElements().forEach(function(c){b._removeSection(c,!0===a)})},_removeSection:function(a,b){var c=this.getElementSection(a),d=this.getElementCell(a);a&&d&&(a===h.getElementWithSelectedTableCells(this)&&this.removeFieldInfoSelection(),c&&c.destroy(),d.destroy(),
e.destroy(a),0==this.getReportElements().length&&!1!==b&&this.addSection(m.EMPTY))},removeSection:function(a){this._removeSection(a)},removeSectionAtIndex:function(a){this._removeSection(this.getReportElements()[a])},moveSection:function(a,b,c){if((a=this.getReportElements()[a])&&a.parentNode){a.parentNode.removeChild(a);var d=this.getReportElements();d.length==b?e.place(a,d[d.length-1],"after"):e.place(a,this.getReportElements()[b],c)}},setHeight:function(a){d.set(this.mainContainer,"height",a+"px")},
_viewMode:null,getViewMode:function(){return this._viewMode},setViewMode:function(a){this._viewMode=a;"edit"==a?(g.add(this.domNode,"reportContainerEditMode"),g.remove(this.domNode,"reportContainerPreviewMode")):(g.remove(this.domNode,"reportContainerEditMode"),g.add(this.domNode,"reportContainerPreviewMode"));"previewValues"!=a||this.viewModel.dynamicReportInfo?l.hide(this._sampleWatermarkDiv):(this._sampleWatermarkDiv||(this._sampleWatermarkDiv=e.create("div",{"class":"sampleValuesWatermark"},this.stackContainer,
"first")),l.show(this._sampleWatermarkDiv));this._updateContainerSize();this._updateChildrenViewMode()},_updateChildrenViewMode:function(a){var b=this;(a?[a]:this.getReportElements()).forEach(function(a){b._setChildCovered(a,"edit"!=b._viewMode);(a=b.getElementSection(a))&&a.setViewMode&&a.setViewMode(b._viewMode)})},collectFieldInfos:function(a){return h.collectFieldInfos(this,a)},notifyShown:function(){this.serializationManager.notifyShown()},fromJson:function(a){return this.serializationManager.fromJson(a)},
toJson:function(a){return this.serializationManager.toJson(a)},onPendingDataApplied:function(){},removeFieldInfoSelection:function(){},onFieldInfoSelected:function(a){},emitOnPreChangeEvent:function(a,b){},destroy:function(){this.clear();this.inherited(arguments)}})});