// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ReportContainerGrid.html":'\x3cdiv class\x3d"esriGEReportPlayer_reportContainerGrid esriGENonSelectable"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"mainContainer" class\x3d"reportContainerGrid_mainContainer"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"fillerContainer" class\x3d"reportContainerGrid_gridZoomFillerContainer"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"scalableContainer" class\x3d"reportContainerGrid_gridZoomScalableContainer"\x3e\r\n                \x3cdiv data-dojo-attach-point\x3d"stackContainer" class\x3d"reportContainerGrid_gridStackContainer"\x3e\x3c/div\x3e\r\n            \x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainers/ReportContainerGrid","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/on dojo/sniff dojo/dom-construct dojo/dom-class dojo/dom-geometry dojo/dom-style dojo/store/Memory dijit/_WidgetBase dijit/_TemplatedMixin ../grid/coreUtils/GridDataUtil ./containerGridUtils/QueryUtil ./containerGridUtils/SerializationManager ./containerGridUtils/ContentLoadingEventManager ./containerGridUtils/ZoomUtil ../supportClasses/DocumentOptions ../supportClasses/templateJsonUtils/FieldInfoBuilder ../themes/ThemeUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes dojo/text!../templates/ReportContainerGrid.html".split(" "),
function(m,n,E,r,t,g,h,k,e,u,v,w,p,l,x,y,f,z,A,B,q,C,D){return m([v,w],{templateString:D,viewModel:null,themeContext:null,theme:null,serializationManager:null,loadingManager:null,documentOptions:null,isSourceContainer:!0,isDynamicReportMode:!1,showWatermark:!0,renderOptions:{center:!1,minTop:0},grids:null,postCreate:function(){this.serializationManager=(new this._getSerializationManagerClass)(this);this.grids=[];this.inherited(arguments);this.updateLayout();this.setViewMode(null);this.isSourceContainer&&
h.add(this.domNode,"reportContainerGrid_sourceContainer")},_getSerializationManagerClass:function(){return x},setDocumentOptions:function(a,b){this.documentOptions&&n.mixin(this.documentOptions,a);this.updateLayout(b)},updateLayout:function(a){var b=this;this.documentOptions&&(this._updateContainerSize(),this.grids.forEach(function(c,d){a&&void 0!==a.pageIndex&&a.pageIndex!==d||(b._updateGridWrappingNodeForCurrentDocumentLayout(c),c.setMaxWidth(b._getAllowedPageWidth()),c.resizeToFitAllowedWidth(),
c.resizeToFitHeight(b._getPageHeight()))}),this._syncFillerContainer())},getFirstPageDomNode:function(){var a=this.stackContainer.children[0];return a&&a.children[0]},getPageDomNodes:function(){return this._getGridContainers()},_getGridContainers:function(){for(var a=[],b=0;b<this.stackContainer.children.length;b++){var c=this.stackContainer.children[b];c&&a.push(c.children[0])}return a},_placeGridContainer:function(a,b){var c=g.create("div",{"class":"reportContainerGrid_gridContainerWrapper"}),d=
void 0!==b&&this.stackContainer.children[b];d?g.place(c,d,"before"):g.place(c,this.stackContainer);g.place(a,c);a.backgroundImage=g.create("div",{"class":"reportContainerGrid_stackContainerBackgroundImage esriGEAbsoluteStretched"},a);t("ie")||this.viewModel.dynamicReportInfo||!this.showWatermark||(this._sampleWatermarkDiv=g.create("div",{"class":"sampleValuesWatermark esriGEAbsoluteStretched"},a,"first"))},_getGridContainer:function(a){return a.domNode&&a.domNode.parentNode},_getGridContainerWrapper:function(a){return(a=
this._getGridContainer(a))&&a.parentNode},_updateGridWrappingNodeForCurrentDocumentLayout:function(a){if(a=this._getGridContainer(a)){var b=this.viewModel.getDocumentDefaultStyles(this.theme||this.themeContext);e.set(a,{paddingLeft:(this.documentOptions.left||0)+"px",paddingRight:(this.documentOptions.right||0)+"px",paddingTop:(this.documentOptions.top||0)+"px",paddingBottom:(this.documentOptions.bottom||0)+"px",backgroundColor:this.documentOptions.backgroundColor||b.backgroundColor})}B.applyBackgroundImageFromSettings(a.backgroundImage,
b.backgroundImage)},_updateContainerSize:function(){var a=0==this._heigth?"auto":e.get(this.domNode,"height")+"px";e.set(this.mainContainer,"height",a);e.set(this.mainContainer,"maxWidth",this._maxWidth?this._maxWidth+"px":"");e.set(this.mainContainer,"maxHeight",this._maxHeight?this._maxHeight+"px":"");this._syncFillerContainer()},getCurrentPageDim:function(){return z.getPageBox(this.documentOptions)},_getAllowedPageWidth:function(){return this.getCurrentPageDim().contentW},_getPageHeight:function(){return this.getCurrentPageDim().contentH},
getCanvasOffsets:function(){var a=k.position(this.mainContainer),b=k.position(this.fillerContainer);return{l:b.x-a.x,r:a.x+a.w-b.x-b.w}},collapseContent:function(){return this.grids.forEach(function(a){a.collapseContent()})},hasHiddenContent:function(){return this.grids.some(function(a){return a.hasHiddenContent()})},resizeRowHeightToShowCellsContent:function(){var a;this.grids.forEach(function(b){a=b.resizeRowHeightToShowCellsContent()||a});return a},_currentPageIndex:-1,getFullWidth:function(){var a=
this.getFirstPageDomNode();return k.getMarginBox(a).w+k.getMarginExtents(this.stackContainer).w},getFullHeight:function(){var a=this.getFirstPageDomNode();return k.getMarginBox(a).h+k.getMarginExtents(this.stackContainer).h},getNumberOfPages:function(){return this.grids.length},showAllPages:function(){this.showPageAt(-1)},showPageAt:function(a){this.grids.forEach(function(b,c){q[-1==a||a==c?"showNodeFromBackground":"hideNodeInBackground"](this._getGridContainerWrapper(b))},this);this._currentPageIndex=
a;this._syncFillerContainer()},getCurrentPageIndex:function(){return this._currentPageIndex},_width:0,_heigth:0,resize:function(a,b){this._width=void 0===a?this._width:a;this._heigth=void 0===b?this._heigth:b;void 0!==a&&e.set(this.domNode,"width",0==this._width?"auto":this._width+"px");void 0!==b&&e.set(this.domNode,"height",0==this._heigth?"auto":this._heigth+"px");this._updateContainerSize()},_maxWidth:0,_maxHeight:0,setMaxWidth:function(a){this._maxWidth=a},setMaxHeight:function(a){this._maxHeight=
a},scrollToElement:function(a,b){b=b||{};if(a&&a.parentGrid){var c=k.position(this.getScrollableContainer()),d=k.position(a.domNode),e=!(d.x>c.x&&c.x+c.w>d.x+d.w),g=!(d.y>c.y&&c.y+c.h>d.y+d.h),f=Math.min(c.h-d.h-30,(c.h-d.h)/2),h;h=Math.max(30,(c.w-d.w)/2)-(d.x-c.x);c=f-(d.y-c.y);if((!b.onlyIfOutOfView||e||g)&&this._getGridContainerWrapper(a.parentGrid)&&(!1===b.scrollHorizontally||!e&&b.onlyIfOutOfView||(this.getScrollableContainer().scrollLeft-=h),g||!b.onlyIfOutOfView))return this._animateScrolling(this.getScrollableContainer().scrollTop-
c,b.immdediate)}},_animateScrolling:function(a,b){this.getScrollableContainer().scrollTop=a},scrollToPageAt:function(a){this.scrollToElement(this.grids[a].getFieldCells()[0],{scrollHorizontally:!1})},scrollToLastPage:function(){this.scrollToPageAt(this.grids.length-1)},getCurrentViewedPageIndex:function(){var a=this.getScrollableContainer().scrollHeight/this.grids.length;return Math.round(this.getScrollableContainer().scrollTop/a)},getScrollableContainer:function(){return this.mainContainer},getLayoutCells:function(a){return l.getLayoutCells(this,
a)},clear:function(a){this.grids.forEach(function(a){a.destroy()});this.grids.length=0;g.empty(this.stackContainer);this._syncFillerContainer()},clearLayoutCell:function(a,b){a.parentGrid&&(a.parentGrid.clearCell(a),a.parentGrid.setCellStyle(a,{backgroundColor:"transparent"}),b&&a.parentGrid.insertFieldInfoToCell(a,this.createEmptySectionJson()))},_removeGrid:function(a){if(a){var b=this._getGridContainerWrapper(a);a.destroy();b&&g.destroy(b);this.grids.splice(this.grids.indexOf(a),1);this._syncFillerContainer()}},
setHeight:function(a){e.set(this.mainContainer,"height",a+"px")},_viewMode:null,getViewMode:function(){return this._viewMode},setViewMode:function(a){this._viewMode=a;"edit"==a?(h.add(this.domNode,"reportContainerEditMode"),h.remove(this.domNode,"reportContainerPreviewMode")):(h.remove(this.domNode,"reportContainerEditMode"),h.add(this.domNode,"reportContainerPreviewMode"));this._updateContainerSize();this._updateGridCellsOverlay();this.grids.forEach(function(b){b.setViewMode(a)})},_updateGridCellsOverlay:function(){var a=
this;this.getLayoutCells().forEach(function(b){a._updateLayoutCellOverlay(b)})},hasFocusedChild:function(){return l.hasFocusedChild(this)},collectFieldInfos:function(a){return l.collectFieldInfos(this,a)},_isLayoutCellDragEnabled:function(a){return!1},createGridFromSectionTableJson:function(a,b){var c=this;void 0!==b&&this._removeGrid(this.grids[b]);var d=a.data||{},e=m(this.viewModel.layoutBuilder.getClass("grid"),{_isDragEnabled:function(a){return this.inherited(arguments)&&c._isLayoutCellDragEnabled(a)}}),
f=g.create("div",{"class":"reportContainerGrid_stackContainer"});this._placeGridContainer(f,b);d=new e(n.mixin({"class":"outerAdjustableGrid",fieldCellClass:"outerAdjustableGridCell",viewModel:this.viewModel,themeContext:this.themeContext,theme:this.theme,viewPortContainer:this.mainContainer,stickToRight:!0,keepGridSizeWhenResized:!1,looseResize:!0,renderBordersFromTheme:!0,inheritThemeBackground:!1,columns:d.columns||[],store:new u({data:d.data||[],idProperty:"id"}),layoutDefaults:{defaultRowHeight:250,
rowMinHeight:100,columnMinWidth:100},_preRenderFieldCell:function(a){p.getFieldInfo(a)||c.isSourceContainer||p.setFieldInfo(a,c.createEmptySectionJson())},_postCreateFieldCell:function(a){c._updateLayoutCellOverlay(a);c._addControlsToLayoutCell(a)},onContentLoadingStart:function(){c.loadingManager&&c.loadingManager.onContentLoadingStart()},onContentLoadingEnd:function(){c.loadingManager&&c.loadingManager.onContentLoadingEnd()}},this._getGridCreationParams()),g.create("div",null,f));d.setMaxWidth(this._getAllowedPageWidth());
d.setSettings({style:{width:this._getAllowedPageWidth(),left:0,spaceBefore:0,spaceAfter:0}});d.setViewMode(this._viewMode);this._updateGridWrappingNodeForCurrentDocumentLayout(d);void 0!==b?this.grids.splice(b,0,d):this.grids.push(d);this._syncFillerContainer();return d},createEmptySectionJson:function(){return A.createFieldInfoFromSection({type:C.EMPTY})},_getGridCreationParams:function(){return null},_updateLayoutCellOverlay:function(a){if(!this.isDynamicReportMode){var b=q.enableContent(a.contentBlock,
"edit"==this._viewMode);b&&!this.isSourceContainer&&r(b,"dblclick",function(){a.content&&a.content.processDoubleClick&&a.content.processDoubleClick()})}},_addControlsToLayoutCell:function(a){},addEmptyPageGrid:function(a,b){var c=b||this.serializationManager.getEmptyPageJson(!0);this.createGridFromSectionTableJson(c.sectionsTables[0])},notifyShown:function(){this.serializationManager.notifyShown()},getVisualState:function(){return{grids:this.grids.map(function(a){return a.getVisualState()})}},setVisualState:function(a){a&&
a.grids&&a.grids.length==this.grids.length&&this.grids.forEach(function(b,c){b.setVisualState(a.grids[c])})},getZoomInfo:function(){return f.getZoomInfo(this)},setZoomInfo:function(a){f.setZoomInfo(this,a)},zoomIn:function(){f.zoomIn(this)},zoomOut:function(){f.zoomOut(this)},zoomToFitPage:function(){f.zoomToFitPage(this)},zoomToFitPageWidth:function(){f.zoomToFitPageWidth(this)},setZoomPercent:function(a){f.setZoomPercent(this,a)},setBestZoom:function(){f.setBestZoom(this)},resetZoom:function(){f.reset(this)},
onZoomChanged:function(){},_syncFillerContainer:function(){var a=this.getZoomInfo().scale;e.set(this.fillerContainer,"marginTop","");e.set(this.fillerContainer,{width:e.get(this.scalableContainer,"width")*a+"px",height:e.get(this.scalableContainer,"height")*a+"px"});this.renderOptions&&this.renderOptions.center&&(a=(e.get(this.mainContainer,"height")-e.get(this.fillerContainer,"height"))/2,e.set(this.fillerContainer,"marginTop",Math.max(this.renderOptions.minTop||0,a)+"px"))},fromJson:function(a,
b){this.resetZoom();this._currentPageIndex=-1;this.loadingManager&&this.loadingManager.destroy();this.loadingManager=null;b=b||{};if(!b.waitUntilAllContentIsReady)return this.serializationManager.fromJson(a);this.loadingManager=new y;this.loadingManager.init();this.serializationManager.fromJson(a);return this.loadingManager.returnOnLoadEnd()},toJson:function(){return this.serializationManager.toJson()},onPendingDataApplied:function(){},removeFieldInfoSelection:function(){},emitOnPreChangeEvent:function(a,
b){},destroy:function(){this.loadingManager&&this.loadingManager.destroy();this.loadingManager=null;this.clear();this.inherited(arguments)}})});