// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/renderers/SDFRenderer","require exports dojo/has ../../../core/libs/gl-matrix/mat4 ../../../core/libs/gl-matrix/vec4 ../../../core/libs/gl-matrix/vec3 ../../webgl/Program ../../webgl/VertexArrayObject ../GeometryUtils ./vtShaderSnippets".split(" "),function(F,G,A,l,m,q,B,C,D,n){var E=1/65536;return function(){function a(){this._attributeLocations={a_pos:0,a_vertexOffset:1,a_tex:2,a_levelInfo:3};this._initialized=!1;this._extrudeMat=l.create();this._haloColor=
m.create();this._sdfColor=m.create();this._scaleVec=q.create()}a.prototype.dispose=function(){this._sdfProgram&&(this._sdfProgram.dispose(),this._sdfProgram=null)};a.prototype.render=function(e,g,c,r,a,t,h,u,v,m,n,q){var b=this;if(!A("esri-vector-tiles-avoid-text")){this._initialized||this._initialize(e);var x=h.getLayoutValue("text-size",c),p=x/24;r=D.degToByte(r);var k=h.getLayoutValue("text-rotation-alignment",c);2===k&&(k=1===h.getLayoutValue("symbol-placement",c)?0:1);var y=0===k,k=h.getLayoutValue("text-keep-upright",
c)&&y,z=.1*24/x/n,w=q*h.getPaintValue("text-opacity",c);this._glyphTextureSize||(this._glyphTextureSize=new Float32Array([u.width/4,u.height/4]));y?l.copy(this._extrudeMat,v):l.copy(this._extrudeMat,m);this._scaleVec[0]=p;this._scaleVec[1]=p;this._scaleVec[2]=1;l.scale(this._extrudeMat,this._extrudeMat,this._scaleVec);e.bindProgram(this._sdfProgram);if(v=this._getSDFVAO(e,t))e.bindVAO(v),this._sdfProgram.setUniformMatrix4fv("u_transformMatrix",t.tileTransform.transform),this._sdfProgram.setUniformMatrix4fv("u_extrudeMatrix",
this._extrudeMat),this._sdfProgram.setUniform2fv("u_normalized_origin",t.tileTransform.displayCoord),this._sdfProgram.setUniform1f("u_depth",h.z+E),this._sdfProgram.setUniform2fv("u_mosaicSize",this._glyphTextureSize),this._sdfProgram.setUniform1f("u_mapRotation",r),this._sdfProgram.setUniform1f("u_keepUpright",k?1:0),this._sdfProgram.setUniform1f("u_level",10*c),this._sdfProgram.setUniform1f("u_fadeSpeed",10*a.fadeSpeed),this._sdfProgram.setUniform1f("u_minfadeLevel",10*a.minfadeLevel),this._sdfProgram.setUniform1f("u_maxfadeLevel",
10*a.maxfadeLevel),this._sdfProgram.setUniform1f("u_fadeChange",10*(c+a.fadeChange)),this._sdfProgram.setUniform1f("u_opacity",w),this._sdfProgram.setUniform1i("u_texture",0),g.glyphPerPageElementsMap.forEach(function(a,g){u.bind(e,9729,g,0);var d=h.getPaintValue("text-halo-color",c);if(0<d[3]){var f=d[3]*w;b._haloColor[0]=f*d[0];b._haloColor[1]=f*d[1];b._haloColor[2]=f*d[2];b._haloColor[3]=f;d=z+h.getPaintValue("text-halo-blur",c)/p/8;f=.75-h.getPaintValue("text-halo-width",c)/p/8;b._sdfProgram.setUniform4fv("u_color",
b._haloColor);b._sdfProgram.setUniform1f("u_edgeDistance",f);b._sdfProgram.setUniform1f("u_edgeWidth",d);e.drawElements(4,a[1],5125,12*a[0])}d=h.getPaintValue("text-color",c);0<d[3]&&(f=d[3]*w,b._sdfColor[0]=f*d[0],b._sdfColor[1]=f*d[1],b._sdfColor[2]=f*d[2],b._sdfColor[3]=f,b._sdfProgram.setUniform4fv("u_color",b._sdfColor),b._sdfProgram.setUniform1f("u_edgeDistance",.75),b._sdfProgram.setUniform1f("u_edgeWidth",z),e.drawElements(4,a[1],5125,12*a[0]))}),e.bindVAO()}};a.prototype._initialize=function(a){if(this._initialized)return!0;
this._sdfProgram=new B(a,n.sdfShaderVS,n.sdfShaderFS,this._attributeLocations);this._sdfVertexAttributes={geometry:[{name:"a_pos",count:2,type:5122,offset:0,stride:16,normalized:!1,divisor:0},{name:"a_vertexOffset",count:2,type:5122,offset:4,stride:16,normalized:!1,divisor:0},{name:"a_tex",count:4,type:5121,offset:8,stride:16,normalized:!1,divisor:0},{name:"a_levelInfo",count:4,type:5121,offset:12,stride:16,normalized:!1,divisor:0}]};return this._initialized=!0};a.prototype._getSDFVAO=function(a,
g){if(g.textVertexArrayObject)return g.textVertexArrayObject;var c=g.textVertexBuffer,e=g.textIndexBuffer;if(!c||!e)return null;g.textVertexArrayObject=new C(a,this._attributeLocations,this._sdfVertexAttributes,{geometry:c},e);return g.textVertexArrayObject};return a}()});