// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/tasks/PrintTask","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/_base/Deferred dojo/has ../kernel ../lang ../layerUtils ../deferredUtils ../Color ../urlUtils ./Task ../geometry/Polygon ../renderers/SimpleRenderer ../symbols/FillSymbol ./Geoprocessor ./PrintTemplate dojo/dom-attr dojo/dom-construct dojox/gfx/_base dojox/gfx/canvas dojox/json/query dojo/has!extend-esri?./PrintParameters dojo/has!extend-esri?./LegendLayer".split(" "),function(x,h,r,A,D,B,E,y,C,
F,G,H,I,J,K,L,M,N,O,P,v,z,Q){x=x(I,{declaredClass:"esri.tasks.PrintTask",constructor:function(a,e){this.url=a;this.printGp=new M(this.url);this._handler=h.hitch(this,this._handler);e&&e.async&&(this.async=e.async);this._colorEvaluator=Q("$..color")},_vtlExtent:null,_handler:function(a,e,f,b,c){try{var d;this.async?"esriJobSucceeded"===a.jobStatus&&this.printGp.getResultData(a.jobId,"Output_File",h.hitch(this,function(b){d=b.value;this._successHandler([d],"onComplete",f,c)})):(d=a[0].value,this._successHandler([d],
"onComplete",f,c))}catch(g){this._errorHandler(g,b,c)}},execute:function(a,e,f){var b=this._handler,c=this._errorHandler,d=a.template||new N;d.hasOwnProperty("showLabels")||(d.showLabels=!0);var g=d.exportOptions,q;g&&(q={outputSize:[g.width,g.height],dpi:g.dpi});var g=d.layoutOptions,n,l=[];if(g){this.legendAll=!1;g.legendLayers?r.forEach(g.legendLayers,function(b){var a={};a.id=b.layerId;b.subLayerIds&&(a.subLayerIds=b.subLayerIds);l.push(a)}):this.legendAll=!0;var k,m;if("Miles"===g.scalebarUnit||
"Kilometers"===g.scalebarUnit)k="esriKilometers",m="esriMiles";else if("Meters"===g.scalebarUnit||"Feet"===g.scalebarUnit)k="esriMeters",m="esriFeet";n={esriMiles:"mi",esriKilometers:"km",esriFeet:"ft",esriMeters:"m"};n={titleText:g.titleText,authorText:g.authorText,copyrightText:g.copyrightText,customTextElements:g.customTextElements,scaleBarOptions:{metricUnit:k,metricLabel:n[k],nonMetricUnit:m,nonMetricLabel:n[m]},legendOptions:{operationalLayers:l}}}k=this._getPrintDefinition(a.map,d);a.outSpatialReference&&
(k.mapOptions.spatialReference=a.outSpatialReference.toJson());a.template&&y.isDefined(a.template.showAttribution)&&(k.mapOptions.showAttribution=a.template.showAttribution);h.mixin(k,{exportOptions:q,layoutOptions:n});this.allLayerslegend&&h.mixin(k.layoutOptions,{legendOptions:{operationalLayers:this.allLayerslegend}});if(k.operationalLayers){q=k.operationalLayers;var p,t=function(b){return y.fixJson(h.mixin(b,{type:"esriSLS",cap:void 0,join:void 0,meterLimit:void 0}))};for(n=0;n<q.length;n++)if(q[n].featureCollection&&
q[n].featureCollection.layers)for(m=0;m<q[n].featureCollection.layers.length;m++){var u=q[n].featureCollection.layers[m];u.layerDefinition&&u.layerDefinition.drawingInfo&&u.layerDefinition.drawingInfo.renderer&&u.layerDefinition.drawingInfo.renderer.symbol&&(p=u.layerDefinition.drawingInfo.renderer,"esriCLS"===p.symbol.type?p.symbol=t(p.symbol):p.symbol.outline&&"esriCLS"===p.symbol.outline.type&&(p.symbol.outline=t(p.symbol.outline)));if(u.featureSet&&u.featureSet.features)for(g=0;g<u.featureSet.features.length;g++)p=
u.featureSet.features[g],p.symbol&&("esriCLS"===p.symbol.type?p.symbol=t(p.symbol):p.symbol.outline&&"esriCLS"===p.symbol.outline.type&&(p.symbol.outline=t(p.symbol.outline)))}}d={Web_Map_as_JSON:A.toJson(y.fixJson(k)),Format:d.format,Layout_Template:d.layout};a.extraParameters&&(d=h.mixin(d,a.extraParameters));var w=new D(F._dfdCanceller);a=function(a,c){b(a,c,e,f,w)};k=function(b){c(b,f,w)};w._pendingDfd=this.async?this.printGp.submitJob(d,a,null,k):this.printGp.execute(d,a,k);return w},onComplete:function(){},
_createMultipointLayer:function(){return{layerDefinition:{name:"multipointLayer",geometryType:"esriGeometryMultipoint",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryMultipoint",features:[]}}},_createPolygonLayer:function(){return{layerDefinition:{name:"polygonLayer",geometryType:"esriGeometryPolygon",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryPolygon",features:[]}}},_createPointLayer:function(){return{layerDefinition:{name:"pointLayer",geometryType:"esriGeometryPoint",
drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryPoint",features:[]}}},_createPolylineLayer:function(){return{layerDefinition:{name:"polylineLayer",geometryType:"esriGeometryPolyline",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryPolyline",features:[]}}},_convertSvgSymbol:function(a){if(!(8>=B("ie")||!a.path&&"image/svg+xml"!==a.contentType)){var e,f=z.createSurface(P.create("div"),1024,1024);e="image/svg+xml"===a.contentType?f.createObject(z.Image,{src:"data:image/svg+xml;base64,"+
a.imageData,width:v.pt2px(a.width),height:v.pt2px(a.height),x:0,y:0}):f.createObject(z.Path,a.path).setFill(a.color).setStroke(a.outline);"pendingRender"in f&&f._render(!0);var b=f.rawNode.getContext("2d"),c=Math.ceil(e.getBoundingBox().width),d=Math.ceil(e.getBoundingBox().height);e=b.getImageData(e.getBoundingBox().x,e.getBoundingBox().y,c,d);b.canvas.width=c;b.canvas.height=d;b.putImageData(e,0,0);b=b.canvas.toDataURL("image/png");a={type:"esriPMS",imageData:b.substr(22,b.length),angle:a.angle,
contentType:"image/png",height:a.size?a.size:v.px2pt(d),width:a.size?c/d*a.size:v.px2pt(c),xoffset:a.xoffset,yoffset:a.yoffset};f.destroy();return a}},_convertSvgRenderer:function(a){"simple"===a.type&&a.symbol&&(a.symbol.path||"image/svg+xml"===a.symbol.contentType)?a.symbol=this._convertSvgSymbol(a.symbol):"uniqueValue"===a.type?(a.defaultSymbol&&(a.defaultSymbol.path||"image/svg+xml"===a.defaultSymbol.contentType)&&(a.defaultSymbol=this._convertSvgSymbol(a.defaultSymbol)),a.uniqueValueInfos&&r.forEach(a.uniqueValueInfos,
function(a){if(a.symbol.path||"image/svg+xml"===a.symbol.contentType)a.symbol=this._convertSvgSymbol(a.symbol)},this)):"classBreaks"===a.type&&(a.defaultSymbol&&(a.defaultSymbol.path||"image/svg+xml"===a.defaultSymbol.contentType)&&(a.defaultSymbol=this._convertSvgSymbol(a.defaultSymbol)),a.classBreakInfos&&r.forEach(a.classBreakInfos,function(a){if(a.symbol.path||"image/svg+xml"===a.symbol.contentType)a.symbol=this._convertSvgSymbol(a.symbol)},this))},_createFeatureCollection:function(a,e,f){var b=
this._createPolygonLayer(),c=this._createPolylineLayer(),d=this._createPointLayer(),g=this._createMultipointLayer(),q=this._createPointLayer();q.layerDefinition.name="textLayer";delete q.layerDefinition.drawingInfo;if("esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass)b.layerDefinition.name=c.layerDefinition.name=d.layerDefinition.name=g.layerDefinition.name=h.getObject("arcgisProps.title",!1,a)||a.name||a.id;var n=a.renderer&&"esri.renderer.SimpleRenderer"===
a.renderer.declaredClass;if(!a.renderer||a.renderer.valueExpression||h.isFunction(a.renderer.attributeField))delete b.layerDefinition.drawingInfo,delete c.layerDefinition.drawingInfo,delete d.layerDefinition.drawingInfo,delete g.layerDefinition.drawingInfo;else{var l=a.renderer.toJson({useLegacyRotationProperties:!0});if("temporal"===l.type){var l={latestObservationRenderer:l.latestObservationRenderer,trackLinesRenderer:l.trackRenderer,observationAger:l.observationAger,renderer:l.observationRenderer},
k={};a._trackIdField&&(k.trackIdField=a._trackIdField);a._startTimeField&&(k.startTimeField=a._startTimeField);a._endTimeField&&(k.endTimeField=a._endTimeField);b.layerDefinition.drawingInfo=l;b.layerDefinition.timeInfo=k;c.layerDefinition.drawingInfo=l;c.layerDefinition.timeInfo=k;d.layerDefinition.drawingInfo=l;d.layerDefinition.timeInfo=k;g.layerDefinition.drawingInfo=l;g.layerDefinition.timeInfo=k}else b.layerDefinition.drawingInfo.renderer=l,c.layerDefinition.drawingInfo.renderer=l,d.layerDefinition.drawingInfo.renderer=
l,g.layerDefinition.drawingInfo.renderer=l}l=a.fields;l||!a.renderer||a.renderer.valueExpression||h.isFunction(a.renderer.attributeField)||("esri.renderer.ClassBreaksRenderer"===a.renderer.declaredClass?(l=[{name:a.renderer.attributeField,type:"esriFieldTypeDouble"}],a.renderer.normalizationField&&l.push({name:a.renderer.normalizationField,type:"esriFieldTypeDouble"})):"esri.renderer.UniqueValueRenderer"===a.renderer.declaredClass&&(l=[{name:a.renderer.attributeField,type:"esriFieldTypeString"}],
a.renderer.attributeField2&&l.push({name:a.renderer.attributeField2,type:"esriFieldTypeString"}),a.renderer.attributeField3&&l.push({name:a.renderer.attributeField3,type:"esriFieldTypeString"})));l&&(b.layerDefinition.fields=l,c.layerDefinition.fields=l,d.layerDefinition.fields=l,g.layerDefinition.fields=l);l=a.graphics;a.isFeatureReductionActive&&a.isFeatureReductionActive()&&(l=a.getSingleGraphics());var k=l.length,m,p;for(p=0;p<k;p++){var t=l[p];if(!1!==t.visible&&t.geometry){m=t.toJson();m.symbol&&
m.symbol.outline&&m.symbol.outline.color&&m.symbol.outline.color[3]&&(m.symbol.outline.color[3]=255);if(a.renderer&&!m.symbol&&(h.isFunction(a.renderer.attributeField)||a.renderer.valueExpression||this._isFeatureCollectionRequired(a.renderer,a)||"esri.renderer.DotDensityRenderer"===a.renderer.declaredClass||f)){f=f||a.renderer;var u=null;try{u=f.getSymbol(t)}catch(w){}if(!u)continue;m.symbol=u.toJson();this._isFeatureCollectionRequired(f,a)&&this._applyVisualVariables(m.symbol,{renderer:f,graphic:t,
symbol:u,mapResolution:e&&e.getResolutionInMeters(),mapScale:e&&e.getScale()})}m.symbol&&(m.symbol.path||"image/svg+xml"===m.symbol.contentType?m.symbol=this._convertSvgSymbol(m.symbol):m.symbol.text&&delete m.attributes);switch(t.geometry.type){case "polygon":b.featureSet.features.push(m);break;case "polyline":c.featureSet.features.push(m);break;case "point":m.symbol&&m.symbol.text?q.featureSet.features.push(m):d.featureSet.features.push(m);break;case "multipoint":g.featureSet.features.push(m);break;
case "extent":m.geometry=J.fromExtent(t.geometry).toJson(),b.featureSet.features.push(m)}}}e=[];0<b.featureSet.features.length&&e.push(b);0<c.featureSet.features.length&&e.push(c);0<g.featureSet.features.length&&e.push(g);0<d.featureSet.features.length&&e.push(d);0<q.featureSet.features.length&&e.push(q);if(!e.length)return null;r.forEach(e,function(b){var a=r.every(b.featureSet.features,function(b){return b.symbol});if(n||a)r.forEach(b.featureSet.features,function(b){delete b.attributes}),delete b.layerDefinition.fields;
a&&delete b.layerDefinition.drawingInfo});r.forEach(e,function(b){b.layerDefinition.drawingInfo&&b.layerDefinition.drawingInfo.renderer&&this._convertSvgRenderer(b.layerDefinition.drawingInfo.renderer)},this);return{id:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||0,featureCollection:{layers:e}}},_getPrintDefinition:function(a,e){var f={operationalLayers:this._createOperationalLayers(a,e)},b=this._vtlExtent||a.extent,c=a.spatialReference;this._vtlExtent=null;a.spatialReference._isWrappable()&&
(b=b._normalize(!0),c=b.spatialReference);b={mapOptions:{showAttribution:a.showAttribution,extent:b.toJson(),spatialReference:c.toJson()}};e.preserveScale&&h.mixin(b.mapOptions,{scale:e.outScale||a.getScale()});a.timeExtent&&h.mixin(b.mapOptions,{time:[a.timeExtent.startTime.getTime(),a.timeExtent.endTime.getTime()]});c={};h.mixin(c,b,f);return c},_createOperationalLayers:function(a,e){var f,b,c,d,g=[],q=0;e.preserveScale&&(q=e.outScale||a.getScale());this.allLayerslegend=this.legendAll?[]:null;this._vtlExtent=
null;var n=r.map(a.layerIds,a.getLayer,a);a._mapImageLyr&&n.push(a._mapImageLyr);for(f=0;f<n.length;f++)if(b=n[f],b.loaded&&b.visible&&(!q||b.isVisibleAtScale(q)))switch(c=b.declaredClass,d={id:b.id,title:h.getObject("arcgisProps.title",!1,b)||b.id,opacity:b.opacity,minScale:b.minScale||0,maxScale:b.maxScale||0},d=h.mixin(d,this._getUrlAndToken(b)),b.getNode()&&O.get(b.getNode(),"data-reference")&&(d._isRefLayer=!0),c){case "esri.layers.ArcGISDynamicMapServiceLayer":var l=[];c=!!b._params.layers;
if(b._params.dynamicLayers)c=A.fromJson(b._params.dynamicLayers),r.forEach(c,function(b){l.push({id:b.id,name:b.name,layerDefinition:b});delete b.id;delete b.name;delete b.maxScale;delete b.minScale}),0===l.length&&(d.visibleLayers=[-1]);else if(b.supportsDynamicLayers){if(c||b.layerDefinitions||b.layerTimeOptions){var k=b.createDynamicLayerInfosFromLayerInfos(),m=null;c&&(m=b.visibleLayers);var m=C._getVisibleLayers(k,m),p=C._getLayersForScale(e.outScale||a.getScale(),k);r.forEach(k,function(a){if(!a.subLayerIds){var c=
a.id;-1<r.indexOf(m,c)&&-1<r.indexOf(p,c)&&(a={source:a.source.toJson()},b.layerDefinitions&&b.layerDefinitions[c]&&(a.definitionExpression=b.layerDefinitions[c]),b.layerTimeOptions&&b.layerTimeOptions[c]&&(a.layerTimeOptions=b.layerTimeOptions[c].toJson()),l.push({id:c,layerDefinition:a}))}});0===l.length&&(d.visibleLayers=[-1])}}else r.forEach(b.layerInfos,function(a){var c={id:a.id,layerDefinition:{}};b.layerDefinitions&&b.layerDefinitions[a.id]&&(c.layerDefinition.definitionExpression=b.layerDefinitions[a.id]);
b.layerTimeOptions&&b.layerTimeOptions[a.id]&&(c.layerDefinition.layerTimeOptions=b.layerTimeOptions[a.id].toJson());(c.layerDefinition.definitionExpression||c.layerDefinition.layerTimeOptions)&&l.push(c)}),c&&(d.visibleLayers=b.visibleLayers);l.length&&(d.layers=l);g.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:b.id,subLayerIds:b.visibleLayers});break;case "esri.layers.ArcGISImageServiceLayer":d=h.mixin(d,{url:b.url,bandIds:b.bandIds,compressionQuality:b.compressionQuality,format:b.format,
interpolation:b.interpolation});b.mosaicRule&&h.mixin(d,{mosaicRule:b.mosaicRule.toJson()});(b.renderingRule||b.renderer)&&(c=b.getExportImageRenderingRule())&&h.mixin(d,{renderingRule:c.toJson()});g.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:b.id});break;case "esri.layers.WMSLayer":d=h.mixin(d,{url:b.url,title:b.title,type:"wms",version:b.version,transparentBackground:b.imageTransparency,visibleLayers:b.visibleLayers});g.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:b.id,
subLayerIds:b.visibleLayers});break;case "esri.virtualearth.VETiledLayer":c=b.mapStyle;"roadOnDemand"===c?c="Road":"aerialWithLabels"===c&&(c="Hybrid");d=h.mixin(d,{visibility:b.visible,type:"BingMaps"+c,culture:b.culture,key:b.bingMapsKey});g.push(d);break;case "esri.layers.OpenStreetMapLayer":d=h.mixin(d,{credits:b.copyright,type:"OpenStreetMap",url:H.getAbsoluteUrl(b.tileServers[0])});g.push(d);break;case "esri.layers.WMTSLayer":d=h.mixin(d,{url:b.url,type:"wmts",layer:b._identifier,style:b._style,
format:b.format,tileMatrixSet:b._tileMatrixSetId});g.push(d);break;case "esri.layers.MapImageLayer":c=b.getImages();r.forEach(c,function(a,c){a.visible&&a.href&&(d={id:b.id+"_image"+c,type:"image",title:b.id,minScale:b.minScale||0,maxScale:b.maxScale||0,opacity:b.opacity*a.opacity,extent:a.extent.toJson()},"data:image/png;base64,"===a.href.substr(0,22)?d.imageData=a.href.substr(22):d.url=a.href,g.push(d))});break;case "esri.layers.VectorTileLayer":d.type="image";d.url&&delete d.url;c=this._vtlExtent||
a.extent.offset(0,0);var t=e.exportOptions&&e.exportOptions.dpi||96,k={format:"png",pixelRatio:t/96};"MAP_ONLY"!==e.layout||!e.preserveScale||e.outScale&&e.outScale!==a.getScale()||96!==t||!e.exportOptions||e.exportOptions.width%2===a.width%2&&e.exportOptions.height%2===a.height%2||(k.area={x:0,y:0,width:a.width,height:a.height},e.exportOptions.width%2!==a.width%2&&--k.area.width,e.exportOptions.height%2!==a.height%2&&--k.area.height,this._vtlExtent||(t=a.toMap({x:k.area.width,y:k.area.height}),c.update(c.xmin,
t.y,t.x,c.ymax,c.spatialReference),this._vtlExtent=c));d.extent=c._normalize(!0).toJson();c=b.takeScreenshot(k);c.isResolved()?c.then(function(a){"data:image/png;base64,"===a.dataURL.substr(0,22)&&(d.imageData=a.dataURL.substr(22))}):console.error("PrintTask: VectorTileLayer.takeScreenshot() returned an unresolved Promise");d.imageData&&g.push(d);break;case "esri.layers.WebTiledLayer":c=b.url.replace(/\$\{/g,"{");d=h.mixin(d,{type:"WebTiledLayer",urlTemplate:c,credits:b.copyright});b.subDomains&&
0<b.subDomains.length&&(d.subDomains=b.subDomains);b._wmtsInfo&&(d.wmtsInfo=b._wmtsInfo);delete d.url;g.push(d);break;default:if(b.getTileUrl||b.getImageUrl)d=h.mixin(d,{url:b.url}),g.push(d)}n=r.map(a.graphicsLayerIds,a.getLayer,a);for(f=0;f<n.length;f++)b=n[f],b.isFeatureReductionActive&&b.isFeatureReductionActive()&&(b.getSingleGraphics().length?n.splice(++f,0,b.getFeatureReductionLayer()):n[f]=b.getFeatureReductionLayer());for(f=0;f<n.length;f++)if(b=n[f],b.loaded&&b.visible&&(!q||b.isVisibleAtScale(q)))switch(c=
b.declaredClass,c){case "esri.layers.FeatureLayer":case "esri.layers.LabelLayer":case "esri.layers.CSVLayer":case "esri.layers.StreamLayer":if("esri.layers.LabelLayer"===c&&!e.showLabels||b.renderer&&"esri.renderer.HeatmapRenderer"===b.renderer.declaredClass)continue;c=null;b.url&&b.renderer&&("esri.renderer.ScaleDependentRenderer"===b.renderer.declaredClass?"scale"===b.renderer.rangeType?c=b.renderer.getRendererInfoByScale(a.getScale())&&b.renderer.getRendererInfoByScale(a.getScale()).renderer:"zoom"===
b.renderer.rangeType&&(c=b.renderer.getRendererInfoByZoom(a.getZoom())&&b.renderer.getRendererInfoByZoom(a.getZoom()).renderer):c=b.renderer);if(c&&("esri.renderer.SimpleRenderer"===c.declaredClass||"esri.renderer.TemporalRenderer"===c.declaredClass||h.isString(c.attributeField)&&b._getField(c.attributeField,!0))&&!c.valueExpression&&!this._isFeatureCollectionRequired(c,b)&&"esri.renderer.DotDensityRenderer"!==c.declaredClass&&"esri.layers.CSVLayer"!==b.declaredClass&&"esri.layers.StreamLayer"!==
b.declaredClass)if(d={id:b.id,title:h.getObject("arcgisProps.title",!1,b)||b.id,opacity:b.opacity,minScale:b.minScale||0,maxScale:b.maxScale||0,layerDefinition:{drawingInfo:{renderer:c.toJson({useLegacyRotationProperties:!0})}}},d=h.mixin(d,this._getUrlAndToken(b)),"esri.renderer.TemporalRenderer"===c.declaredClass&&(k=d.layerDefinition.drawingInfo,k.latestObservationRenderer=k.renderer.latestObservationRenderer,k.trackLinesRenderer=k.renderer.trackRenderer,k.observationAger=k.renderer.observationAger,
k.renderer=k.renderer.observationRenderer,b._trackIdField&&(d.layerDefinition.timeInfo={trackIdField:b._trackIdField})),this._convertSvgRenderer(d.layerDefinition.drawingInfo.renderer),1>b.opacity||"esri.renderer.TemporalRenderer"===c.declaredClass||this._updateLayerOpacity(d))if(b._params.source&&(c=b._params.source.toJson(),h.mixin(d.layerDefinition,{source:c})),b.getDefinitionExpression()&&h.mixin(d.layerDefinition,{definitionExpression:b.getDefinitionExpression()}),2!==b.mode)0<b.getSelectedFeatures().length&&
(c=r.map(b.getSelectedFeatures(),function(a){return a.attributes[b.objectIdField]}),0<c.length&&b.getSelectionSymbol()&&h.mixin(d,{selectionObjectIds:c,selectionSymbol:b.getSelectionSymbol().toJson()}));else{c=r.map(b.getSelectedFeatures(),function(a){return a.attributes[b.objectIdField]});if(0===c.length||!b._params.drawMode)break;h.mixin(d.layerDefinition,{objectIds:c});c=null;b.getSelectionSymbol()&&(c=new K(b.getSelectionSymbol()));h.mixin(d.layerDefinition.drawingInfo,{renderer:c&&c.toJson()})}else d=
this._createFeatureCollection(b,a);else d=c&&(c.valueExpression||this._isFeatureCollectionRequired(c,b)||"esri.renderer.DotDensityRenderer"===c.declaredClass)?this._createFeatureCollection(b,a,c):this._createFeatureCollection(b,a);if(!d)continue;g.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:b.id});break;case "esri.layers._GraphicsLayer":case "esri.layers.GraphicsLayer":case "esri.layers.WFSLayer":if(d=this._createFeatureCollection(b,a))g.push(d),this.allLayerslegend&&this.allLayerslegend.push({id:b.id})}q&&
r.forEach(g,function(a){a.minScale=0;a.maxScale=0});a.graphics&&0<a.graphics.graphics.length&&(d=this._createFeatureCollection(a.graphics,a))&&g.push(d);a._labels&&e.showLabels&&(d=this._createFeatureCollection(a._labels,a))&&g.push(d);r.forEach(g,function(a,b,c){a._isRefLayer&&(delete a._isRefLayer,c.splice(b,1),c.push(a))});return g},_getUrlAndToken:function(a){return{token:a._getToken(),url:a._url?a._url.path:null}},_updateLayerOpacity:function(a){var e=this._colorEvaluator(a),e=r.filter(e,function(a){return h.isArray(a)&&
4===a.length}),f=!0;if(e.length){var b=e[0][3],c;for(c=1;c<e.length;c++)if(b!==e[c][3]){f=!1;break}if(f)for(a.opacity=b/255,c=0;c<e.length;c++)e[c][3]=255}return f},_isFeatureCollectionRequired:function(a,e){if(e&&e.isFeatureReductionActive&&e.isFeatureReductionActive())return!0;var f=!1,b=this._getVariable(a,"rotationInfo",!1);b&&(f=(f=b.field)&&h.isFunction(f)||b.valueExpression);return a.hasVisualVariables("sizeInfo")||a.hasVisualVariables("colorInfo")||a.hasVisualVariables("opacityInfo")||f},
_getVariable:function(a,e,f){var b;a&&(b=(a=a.getVisualVariablesForType(e,f))&&a[0]);return b},_applyVisualVariables:function(a,e){var f=e.renderer,b=e.graphic,c=e.symbol,d=e.mapResolution,g=e.mapScale,h=c.type;if("textsymbol"!==h&&"shieldlabelsymbol"!==h){var n=this._getVariable(f,"sizeInfo",!1),l=this._getVariable(f,"colorInfo",!1),k=this._getVariable(f,"opacityInfo",!1),m=this._getVariable(f,"rotationInfo",!1);c instanceof L&&(n=this._getVariable(f,"sizeInfo","outline")||n);d=n?f.getSize(b,{sizeInfo:n,
shape:"simplemarkersymbol"===h?c.style:null,resolution:d,scale:g}):b.size;null!=d&&("simplemarkersymbol"===h?a.size=v.px2pt(d):"picturemarkersymbol"===h?(g=c.width/c.height*d,a.width=v.px2pt(g),a.height=v.px2pt(d),0!==c.xoffset&&(a.xoffset=v.px2pt(c.xoffset/c.width*g)),0!==c.yoffset&&(a.yoffset=v.px2pt(c.yoffset/c.height*d))):"simplelinesymbol"===h?a.width=v.px2pt(d):a.outline&&(a.outline.width=v.px2pt(d)));l&&(!(c=f.getColor(b,{colorInfo:l}))||"simplemarkersymbol"!==h&&"simplelinesymbol"!==h&&"simplefillsymbol"!==
h||(a.color=G.toJsonColor(c)));k&&(h=f.getOpacity(b,{opacityInfo:k}),null!=h&&a.color&&(a.color[3]=Math.round(255*h)));m&&(f=f.getRotationAngle(b,{rotationInfo:m}))&&(a.angle=-f)}}});B("extend-esri")&&h.setObject("tasks.PrintTask",x,E);return x});