// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridDataUtil",[],function(){var b={isEmptyCell:function(a){return!a.get("value")&&!a.gridData[a.column.field]&&!b.getFieldInfo(a)},hasSpans:function(a){return b.getColumnSpan(a)||b.getRowSpan(a)},getColumnSpan:function(a){return a.gridData&&a.gridData.columnSpans&&a.gridData.columnSpans[a.column.field]},getRowSpan:function(a){return a.gridData&&a.gridData.rowSpans&&a.gridData.rowSpans[a.column.field]},getDataColumnSpan:function(a,b){return a&&
a.columnSpans&&a.columnSpans[b]},getDataRowSpan:function(a,b){return a&&a.rowSpans&&a.rowSpans[b]},getFieldInfo:function(a){return a&&a.gridData&&a.gridData.fieldInfos&&a.gridData.fieldInfos[a.column.field]},setFieldInfo:function(a,b){a.gridData&&((a.gridData.fieldInfos[a.column.field]=b)||a.setInfoTooltip&&a.setInfoTooltip(null))},provideFieldInfo:function(a){b.setFieldInfo(a,b.getFieldInfo(a)||{});return b.getFieldInfo(a)},getCellStyle:function(a,c){if(!a||!a.gridData)return null;var d=a.gridData.style&&
a.gridData.style.fields&&a.gridData.style.fields[a.column.field];!d&&c&&(d={},b.setCellStyle(a,d));return d},setCellStyle:function(a,b){var c=a.gridData.style=a.gridData.style||{};c.fields=c.fields||{};c.fields[a.column.field]=b},copyFieldStyle:function(a,c,d){a=b.getCellStyle(a);c=b.getCellStyle(c,!0);for(var e in d)void 0!==a[e]&&(c[e]=a[e])},getFieldCellText:function(a){return a.gridData&&a.gridData[a.column.field]},setFieldCellContent:function(a,b){a.set("value",b||"");a.gridData[a.column.field]=
a.get("value")},clearFieldInfo:function(a,b){a.fieldInfos&&delete a.fieldInfos[b.field];a[b.field]=""},getFieldCellUrl:function(a){if(a.gridData&&a.gridData.urls&&a.column)return a.gridData.urls[a.column.field]},setFieldCellUrl:function(a,b){a.gridData&&a.column&&(a.gridData.urls=a.gridData.urls||{},void 0===b?delete a.gridData.urls[a.column.field]:a.gridData.urls[a.column.field]=b)},getConditionalFormatting:function(a){return(a=b.getFieldInfo(a))&&a.triggerJson},setConditionalFormatting:function(a,
c){b.provideFieldInfo(a).triggerJson=c},isRichTextCell:function(a){return(a=b.getFieldInfo(a))&&a.isRichText},isVariableFieldCell:function(a){return(a=b.getFieldInfo(a))&&(a.hasVariable||a.script)},isOnlyVariableFieldCell:function(a){return(a=b.getFieldInfo(a))&&a.hasVariable},isScriptFieldCell:function(a){return(a=b.getFieldInfo(a))&&a.script},isUneditableScript:function(a){return(a=b.getFieldInfo(a))&&a.script&&a.script.isUneditableScript},isNumericVariableFieldCell:function(a){return(a=b.getFieldInfo(a))&&
(a.hasVariable||a.script&&(!a.script.isUneditableScript||"String"!=a.script.type))},isChartCell:function(a){return(a=b.getFieldInfo(a))&&a.isChart},isImageCell:function(a){return(a=b.getFieldInfo(a))&&a.isImage},isMapImageCell:function(a){return(a=b.getFieldInfo(a))&&a.isImage&&a.imageJson.isMapImage},isImageTriggerCell:function(a){return(a=b.getFieldInfo(a))&&a.isImage&&a.triggerJson},isShapeCell:function(a){return(a=b.getFieldInfo(a))&&a.isShape},isEmptyShapeCell:function(a){return(a=(a=b.getFieldInfo(a))&&
a.shapeJson)&&!a.g||!a.g.length},isReportSectionCell:function(a){return(a=b.getFieldInfo(a))&&a.isReportSection},isInfographicCell:function(a){return(a=b.getFieldInfo(a))&&a.isInfographic}};return b});