// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridCellRenderer","dojo/_base/declare ./GridDataUtil ./GridStyleUtil ./GridLayoutCalculator ./GridCellContentScaler ../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../supportClasses/templateJsonUtils/FieldInfoRenderer ../../supportClasses/templateJsonUtils/FieldInfoTooltipUtil ../../themes/ReportThemes esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes".split(" "),function(n,f,p,q,g,r,l,w,t,u){var v={color:"#FF0000"};
return n(null,{renderCellContent:function(a){var b=a.parentGrid,c=f.getFieldInfo(a);if(c){if(c.isChart){this._placeChartInCell(b,a);return}if(c.isImage||c.isShape){this._placeImageOrShapeInCell(b,a,c.isImage);return}if(c.isReportSection){this._placeReportSectionInCell(b,a);return}if(c.isInfographic){this._placeInfographicInCell(b,a);return}c.isMissing&&a.setStyle(v);b=this._getRenderedContent(a,c)}else b=a.gridData[a.column.field]||"";this._applyRenderedContent(a,b);a.setContent(null);c&&c.isRichText&&
a.setHoverTooltip&&a.setHoverTooltip("")},updateViewMode:function(a){var b=f.getFieldInfo(a);b&&(b.hasVariable||b.script||b.alias||b.isRichText)&&this._applyRenderedContent(a,this._getRenderedContent(a,b))},_getRenderedContent:function(a,b){var c=this._prepareRenderContextForFieldCell(a,b);return l.renderFieldInfoInTableCell(b,c)},_applyRenderedContent:function(a,b){f.setFieldCellContent(a,b&&b.label||b);b&&(a.setNumberValue(b.numberValue),b.conditionalStyle?a.setStyle(b.conditionalStyle):!1!==b.conditionalStyle&&
"string"!==typeof b||a.setStyle(p.combineCellStyle(a.parentGrid,a.gridData,a.column)));a.parentGrid&&a.parentGrid.viewModel.dynamicReportInfo&&a.setUrl(f.getFieldCellUrl(a))},_prepareRenderContextForFieldCell:function(a,b){var c=a.parentGrid,d;d=c.getSpecificViewMode();var e="previewValues"==c.getViewMode();!b||"SiteNote"!=b.name&&"SiteNotes"!=b.name||(e=!0);d&&("previewValues"==d.richText&&b&&b.isRichText?e=!0:"previewValues"==d.variable&&b&&(b.hasVariable||b.script)&&(e=!0));d=e;e="edit"==c.getViewMode();
return{previewValues:d,previewConditionalStyle:!d&&!e,getPreviewValueFunction:c.getPreviewValueFunction,fieldData:c.viewModel.dynamicReportInfo&&c.viewModel.dynamicReportInfo.fieldData,featureIndex:c.previewFeatureIndex||c.isMultiFeatureTable()&&q.calcRingIndexForCell(a),rowIndex:a.gridData&&a.gridData.index,isGraphicReport:c.viewModel.reportStyle==t.GRAPHIC}},_placeChartInCell:function(a,b){return this._createChartPageFromParams(a,b,{viewModel:a.viewModel,themeContext:a.themeContext,theme:a.theme,
previewFeatureIndex:a.previewFeatureIndex,showEditButton:!0})},_createChartPageFromParams:function(a,b,c){var d=f.getFieldInfo(b).chartJson;a=a.viewModel.layoutBuilder.createElement("chart",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},json:d,creationParams:c});g.fitContentInsideCell(b);return a},_placeImageOrShapeInCell:function(a,b,c){var d=f.getFieldInfo(b),e=d[c?"imageJson":"shapeJson"],k=b.getWidth(),g=b.getHeight();if(c){if(d.triggerJson&&a.viewModel.dynamicReportInfo){var m=
l.getValueFromFieldData(d.triggerJson.fieldInfo,{fieldData:a.viewModel.dynamicReportInfo.fieldData,formatValue:!1});r.processImageJsonForTrigger(e,m,d.triggerJson);b.setNumberValue(m)}e.style.width&&e.style.height&&!e.fitParent&&Math.round(e.style.width)!=Math.round(k)&&Math.round(e.style.height)!=Math.round(g)?e.fitParent=!1:(e.fitParent=!0,e.style.width=k,e.style.height=g)}else e.style.width=k,e.style.height=g;var h,d={alignParams:b.getFullStyle(),imageTriggerJson:d.triggerJson,createMapFunc:a.viewModel.dynamicReportInfo&&
a.viewModel.dynamicReportInfo.createMapFunc,getDynamicImageFunc:a.viewModel.getDynamicImageFunc.bind(a.viewModel),themeContext:a.themeContext,theme:a.theme,showError:!1,getPreviewValueFunction:a.getPreviewValueFunction,applyThemeStyle:a.applyThemeStyle,onInitialized:function(){if(b.domNode){var a=b.getWidth(),c=b.getHeight();h&&h.resize&&h.resize({w:a,h:c},b.getFullStyle())}},onContentLoadingStart:function(){a.onContentLoadingStart()},onContentLoadingEnd:function(){a.onContentLoadingEnd()}};return h=
this._createImageOrShapeFromParams(a,b,e,c,d)},_createImageOrShapeFromParams:function(a,b,c,d,e){return a.viewModel.layoutBuilder.createElement(d?"image":"shape",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},relativeParent:b.domNode,json:c,creationParams:e})},_placeReportSectionInCell:function(a,b){var c={"class":"adjustableGrid_inCellSection"};c.json=f.getFieldInfo(b).sectionJson;c.viewModel=a.viewModel;c.themeContext=a.themeContext;c.theme=a.theme;c.viewPortContainer=
a.viewPortContainer;c.initialWidth=b.getWidth();c.hasFixedLayout=!1;c.onContentLoadingStart=function(){a.onContentLoadingStart()};c.onContentLoadingEnd=function(){a.onContentLoadingEnd()};return this._createReportSectionFromParams(a,b,c)},_createReportSectionFromParams:function(a,b,c){c.parentGridCell=b;c=c.json&&c.json.stack&&c.json.type!=u.EMPTY?a.viewModel.layoutBuilder.createElement("section",c,b.getContentContainerNode()):a.viewModel.layoutBuilder.createElement("emptySection",c,b.getContentContainerNode());
b.setContent(c);c.setViewMode&&c.setViewMode(a.getViewMode());g.fitContentInsideCell(b);return c},_placeInfographicInCell:function(a,b){var c=f.getFieldInfo(b).infographicJson,d={viewModel:a.viewModel,themeContext:a.themeContext,theme:a.theme,width:b.getWidth(),height:b.getHeight(),showEditButton:!0,allowEditContent:!1,onContentLoadingStart:function(){a.onContentLoadingStart()},onContentLoadingEnd:function(){a.onContentLoadingEnd()}},c=this._createInfographicFromParams(a,b,c,d);c.setViewMode&&c.setViewMode(a.getViewMode());
return c},_createInfographicFromParams:function(a,b,c,d){a=a.viewModel.layoutBuilder.createElement("infographic",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},json:c,creationParams:d});g.fitContentInsideCell(b);return a}})});