// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ChartContainer.html":'\x3cdiv class\x3d"esriGEReportPlayer_chartContainer"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"editChartButton" class\x3d"chartContainer_editChartButton"\x3e${nls.editChart}\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"chartLabel" class\x3d"chartContainer_chartLabel"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"chartContainer_chartContainerWithAxis" data-dojo-attach-point\x3d"chartContainerWithAxis"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"chartContainerDiv"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"tableContainerDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"legendContainerDiv" class\x3d"chartContainer_legendContainer"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/ChartContainer","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/when dijit/_WidgetBase dijit/_TemplatedMixin dojox/charting/Chart dojox/charting/action2d/Magnify dojox/charting/action2d/Highlight ./chartUtils/action2d/RingHighlight ./_ChartLegendSupport ./_ChartEventSupport ./chartUtils/ChartBuilder ./chartUtils/ChartTypes ./chartUtils/ChartSorting ./chartUtils/ChartCalculator ./chartUtils/ChartStyleUtil ../themes/ReportThemes ./tooltips/ChartTooltip esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil ./iconRendering/IconRenderer ./textRendering/TextRenderer ./tableViewRendering/TableViewRenderer dojo/text!../templates/ChartContainer.html dojo/i18n!../../../../../nls/jsapi".split(" "),
function(t,q,v,w,m,R,e,x,y,z,A,B,C,D,E,F,G,h,f,H,u,I,J,K,g,L,M,N,O,P,r){r=r.geoenrichment.dijit.ReportPlayer.ReportPlayer;var Q=t(B,{_renderPlotBackground:function(a,b,c,d){this.theme.plotarea.backgroundImageData?this.surface.createImage({src:this.theme.plotarea.backgroundImageData,x:b.l-1,y:b.t-1,width:c+2,height:d+2}):this.inherited(arguments)}});return t([z,A,F,G],{templateString:P,nls:r,viewModel:null,themeContext:null,theme:null,previewFeatureIndex:null,immediateRender:!1,chartTheme:null,chart:null,
showEditButton:!1,onPlotChangeColor:null,onPlotChangeIcon:null,_currentSeries:null,_placements:["Left","Right","Top","Bottom"],_iconRenderer:null,_textRenderer:null,_tableViewRenderer:null,postCreate:function(){var a=this;this.inherited(arguments);this.viewModel.reportStyle==J.GRAPHIC&&w.add(this.domNode,"graphicReportChart");this.showEditButton?x(this.editChartButton,"mousedown",function(b){b.stopPropagation();a.onEdit()}):m.destroy(this.editChartButton);this._iconRenderer=(new this._getIconRendererClass)();
this.own(this._iconRenderer);this._textRenderer=(new this._getTextRendererClass)();this.own(this._textRenderer);this._tableViewRenderer=new O;this.own(this._tableViewRenderer)},_currentSeriesItems:null,_currentVisualProperties:null,_currentChartType:null,_isMultiFeatureChart:null,updateChart:function(a){if(a){this._currentSeriesItems=a.seriesItems;this._currentVisualProperties=a.visualProperties;this._currentChartType=a.type;if((this._isMultiFeatureChart=a.isMultiFeatureChart)&&this._currentSeriesItems.length){var b=
this._currentSeriesItems[0],c=this.viewModel.dynamicReportInfo.fieldData.featureData;this._currentSeriesItems=b.points.map(function(a){return{label:a.label,thickness:b.thickness,points:c.map(function(b){return{label:b["HEADERS.AREA_DESC"]||"",fieldName:a.fieldName,calculator:a.calculator}})}})}this._updateLabels();this._createChart();this._addPlotEventListeners();this._createLegend();this._updateSeries()}},getLegendNode:function(){return this.legendContainerDiv},_updateLabels:function(){this.chartLabel.innerHTML=
this._currentVisualProperties.title.text;g[this.chartLabel.innerHTML?"show":"hide"](this.chartLabel);e.set(this.chartLabel,"textAlign",this._currentVisualProperties.title.align);var a=q.mixin({},this.viewModel.getChartDefaultStyles(this.theme||this.themeContext).titleStyle,this._currentVisualProperties.title.style);e.set(this.chartLabel,I.getStyleObjWithUnits(a))},_createChart:function(){this._destroyChart();var a=m.create("div",{"class":"chartContainerDiv_innerChartNode"},this.chartContainerDiv);
this.chart=a=new Q(a);a.setTheme(this.chartTheme);h.getChartBuilder(this._currentChartType).configureChart({chart:a,seriesItems:this._currentSeriesItems,visualProperties:this._currentVisualProperties,chartType:this._currentChartType,themeSettings:this.viewModel.getChartDefaultStyles(this.theme||this.themeContext),viewModel:this.viewModel,previewFeatureIndex:this.previewFeatureIndex});this.viewModel.dynamicReportInfo&&(this._currentChartType!=f.PIE&&this._currentChartType!=f.DONUT||new C(a,"default",
{scale:1.03}),this._currentChartType==f.RING?new E(a,"default"):new D(a,"default"));if(this.viewModel.dynamicReportInfo||this._currentVisualProperties.conditionalStyling&&h.supportConditionalStyling(this._currentChartType))a=new K(a,"default",{duration:50}),a.showStatistics=!!this.viewModel.dynamicReportInfo,a.setChartType(this._currentChartType)},_destroyChart:function(){this._hideLevelLine();m.empty(this.chartContainerDiv);this.chart&&this.chart.destroy();this.chart=null;this._destroyLegend()},
_updateSeries:function(){var a=this;this._removeSeries();if(this._currentSeriesItems&&this._currentSeriesItems.length)return this._currentSeries=h.getChartBuilder(this._currentChartType).calcSeries({chart:this.chart,seriesItems:this._currentSeriesItems,visualProperties:this._currentVisualProperties,chartType:this._currentChartType,themeSettings:this.viewModel.getChartDefaultStyles(this.theme||this.themeContext),viewModel:this.viewModel,previewFeatureIndex:this.previewFeatureIndex,isMultiFeatureChart:this._isMultiFeatureChart,
excludedSeriesHash:this._excludedSeriesHash,sorting:this._sorting||this._currentVisualProperties.sorting}),this._currentSeries.forEach(function(b){a._excludedSeriesHash[b.name]||a.chart.addSeries(b.name,b.data,b.params)}),this.resize();this.resize()},_removeSeries:function(){var a=this;this._currentSeries=this._currentSeries||[];this._currentSeries.forEach(function(b){a.chart.removeSeries(b.name)});this._currentSeries.length=0},_chartWidth:0,_chartHeight:0,_resizedFlag:!1,_provideSpecialTextStyling:function(){if(-1!=
[f.COLUMN,f.LINE,f.BAR].indexOf(this._currentChartType)){var a=this._currentVisualProperties,b=this.viewModel.getChartDefaultStyles(this.theme||this.themeContext),c;for(c in this.chart.axes){var d=a[c+"Axis"],p=q.mixin({},b[c+"Axis"].style,d.style),g=q.mixin({},b[c+"Axis"].titleStyle,d.titleStyle),p="underline"==p.textDecoration,g="underline"==g.textDecoration;if(p||g){var k=this.chart.axes[c],l,h=[],n=this._currentChartType==f.BAR?"y":"x",d=!!d.title;if(c==n)for(l=d&&k.htmlElements[0],d=d?1:0;d<
k.htmlElements.length;d++)h.push(k.htmlElements[d]);else if(c!=n&&k.group&&k.group.children){n=[];for(l=0;l<k.group.children.length;l++){var m=k.group.children[l];m.rawNode&&"text"==m.rawNode.nodeName&&n.push(m.rawNode)}if(l=d&&n[0])n.shift(),h=n;else for(d=0;d<k.htmlElements.length;d++)h.push(k.htmlElements[d])}g&&l&&e.set(l,"textDecoration","underline");p&&h.forEach(function(a){e.set(a,"textDecoration","underline")})}}if("underline"==q.mixin({},b.dataLabelsStyle,a.dataLabelsStyle).textDecoration&&
this.chart.stack[0])for(c in this.chart.stack[0].htmlElements)e.set(this.chart.stack[0].htmlElements[c],"textDecoration","underline")}},_resizeDfd:null,resize:function(a,b,c){if(this._currentVisualProperties)return void 0!==a&&u.resizeVisualProperties(this._currentVisualProperties,a,b),this._resizedFlag||e.set(this.domNode,"opacity","0"),this._resizeDfd=this._resizeDfd||new v,c||this.immediateRender?this._doResizeChart():L.invoke(this,"_doResizeChart",50)},_doResizeChart:function(){function a(){setTimeout(function(){b._updateLegend();
b._updateIcons();b._updateTexts()});b.onRendered();b._resizeDfd&&b._resizeDfd.resolve();b._resizeDfd=null}var b=this;if(this.chart){this._resizedFlag||e.set(this.domNode,"opacity","1");this._resizedFlag=!0;this._updateLegend();var c=u.calcChartDimentions(this,{visualProps:this._currentVisualProperties,chartType:this._currentChartType,maxIconSize:this._iconRenderer.AXIS_ICON_MAX_SIZE}),d=c.w,c=c.h;if(this._chartWidth==d&&this._chartHeight==c&&this.chart&&this.chart.dim.width&&this.chart.dim.height)this.chart.render();
else{this._chartWidth=d;this._chartHeight=c;e.set(this.domNode,{width:this._currentVisualProperties.width+"px",height:this._currentVisualProperties.height+"px"});this._currentChartType!=f.COLUMN&&this._currentChartType!=f.BAR||h.getChartBuilder(this._currentChartType).updateBarSize({chart:this.chart,chartSize:this._currentChartType==f.COLUMN?this._chartWidth:this._chartHeight,seriesItems:this._currentSeriesItems,visualProperties:this._currentVisualProperties,chartType:this._currentChartType,viewModel:this.viewModel,
previewFeatureIndex:this.previewFeatureIndex});try{this.chart&&this.chart.resize(this._chartWidth,this._chartHeight),this._provideSpecialTextStyling()}catch(p){console.log(p)}}a()}},notifyShown:function(){this.resize()},onRendered:function(){},_getIconRendererClass:function(){return M},_updateIcons:function(){this._iconRenderer.renderIcons({viewModel:this.viewModel,themeContext:this.themeContext,theme:this.theme,chartType:this._currentChartType,iconNode:this.chartContainerWithAxis,chartW:this._chartWidth,
chartH:this._chartHeight,visualProperties:this._currentVisualProperties,chart:this.chart})},_getTextRendererClass:function(){return N},_updateTexts:function(){this._textRenderer.renderTexts({viewModel:this.viewModel,themeContext:this.themeContext,theme:this.theme,textNode:this.chartContainerWithAxis,chartW:this._chartWidth,chartH:this._chartHeight,visualProperties:this._currentVisualProperties,chart:this.chart})},setViewMode:function(a){this._iconRenderer.setViewMode(a);this._textRenderer.setViewMode(a);
this._tableViewRenderer.setViewMode(a)},_sorting:null,getSorting:function(){return this._sorting},sortChart:function(a){this._sorting=a&&a!=H.NONE?a:null;this._updateSeries()},_isTableView:!1,chartToTable:function(){if(!this._isTableView){this._isTableView=!0;g.hide([this.chartContainerDiv,this.legendContainerDiv]);for(var a=0;a<this.chartContainerWithAxis.children.length;a++){var b=this.chartContainerWithAxis.children[a];b!==this.tableContainerDiv&&g.hide(b)}this._tableViewRenderer.renderTableForChart({viewModel:this.viewModel,
themeContext:this.themeContext,theme:this.theme,tableNode:this.tableContainerDiv,width:e.get(this.domNode,"width")-2,height:e.get(this.domNode,"height")-e.get(this.chartLabel,"height"),seriesItems:this._currentSeriesItems,visualProperties:this._currentVisualProperties,chart:this.chart})}},tableToChart:function(){this._isTableView=!1;g.show([this.chartContainerDiv,this.legendContainerDiv]);for(var a=0;a<this.chartContainerWithAxis.children.length;a++)g.show(this.chartContainerWithAxis.children[a]);
this._tableViewRenderer.destroyTable()},getVisualState:function(){return{sorting:this.getSorting(),isTableView:this._isTableView}},setVisualState:function(a){a&&y(this._resizeDfd&&this._resizeDfd.promise,function(){a.sorting&&this.sortChart(a.sorting);a.isTableView&&this.chartToTable()}.bind(this))},getWidth:function(){return this._currentVisualProperties.width},getHeight:function(){return this._currentVisualProperties.height},onEdit:function(){},destroy:function(){this._destroyChart();this.inherited(arguments)}})});