// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/iconRendering/IconRenderer","dojo/_base/declare dojo/dom-construct dojo/dom-geometry dojo/dom-style dijit/Destroyable ../chartUtils/ChartTypes ../../supportClasses/templateJsonUtils/FieldInfoBuilder ../../supportClasses/TableUtil ../../infographics/infographicUtils/InfographicThemeUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/utils/DomUtil".split(" "),function(w,q,z,k,x,f,l,y,m,n,v){return w(x,
{AXIS_ICON_MAX_SIZE:50,renderIcons:function(a){this._destroyIcons();var b=this._getRenderFunction(a.chartType);b&&this[b](a);this._renderFloatingIcons(a)},_getRenderFunction:function(a){switch(a){case f.DONUT:return"_renderDonutIcons";case f.RING:return"_renderRingIcons";case f.COLUMN:return"_renderColumnIcons";case f.BAR:return"_renderBarIcons"}return null},_renderDonutIcons:function(a){if(a.visualProperties.showChartIcons){var b=a.chart.getPlot("default").getRenderResults();if(b){var d=q.create("div",
{"class":"chartContainer_chartIcon"},a.iconNode),b=b.radiusInner;k.set(d,{width:b+"px",height:b+"px",left:(a.chartW-b)/2+"px",top:(a.chartH-b)/2+"px"});this._createIconSection(a,a.visualProperties.chartIcons&&a.visualProperties.chartIcons[0]||this._getDefaultIcon(),b,d)}}},_renderRingIcons:function(a){if(a.visualProperties.showChartIcons){var b=a.chart.getPlot("default").getRenderResults();if(b){b.slicePies.sort(function(a,b){return a.r-b.r});var d=b.slicePies[0],e=b.slicePies[b.slicePies.length-
1],g=q.create("div",{"class":"chartContainer_chartIcon"},a.iconNode),c=0;b.labels?(c=Math.max(50,.8*Math.min(2*d.r,Math.min(b.maxLabelWidth,a.chartW-(e.cx+e.r)))),k.set(g,{width:c+"px",height:c+"px",left:Math.max(e.cx+e.r+15,e.cx+e.r+b.maxLabelWidth/2-c/2)+"px",top:e.cy-c/2+"px"})):(c=1.4*d.r,k.set(g,{width:c+"px",height:c+"px",left:d.cx-c/2+"px",top:d.cy-c/2+"px"}));this._createIconSection(a,a.visualProperties.chartIcons&&a.visualProperties.chartIcons[0]||this._getDefaultIcon(),c,g)}}},_renderColumnIcons:function(a){this._renderAxisIcons(a,
!0)},_renderBarIcons:function(a){this._renderAxisIcons(a,!1)},_renderAxisIcons:function(a,b){if(a.visualProperties.showAxisIcons){var d=this,e=a.chart.calculateGeometry();if(e.series[0].group){var g=e.series[0].group.children.map(function(a){return a.rawNode}),c,p;e.series[0].data.forEach(function(a,b){void 0!==a.unsortedIndex&&(c=c||{},c[b]=a.unsortedIndex);p=p||{};p[b]=a.fill});var f=a.visualProperties.isStacked?1:e.series.length,l=v.position(a.iconNode);g.forEach(function(e,u){var m=c?c[u]:u,r=
v.position(e),t=q.create("div",{"class":"chartContainer_chartIcon"},a.iconNode),h=Math.min(50,a.chartW/g.length);k.set(t,{width:h+"px",height:h+"px"});var n=a.visualProperties.xAxis.show?0:h/(b?2:3.5);b?k.set(t,{left:r.x-l.x+(r.w*f-h)/2+"px",bottom:-h+n+"px"}):k.set(t,{top:r.y-l.y+(r.h*f-h)/2+"px",left:-h+n+"px"});d._createIconSection(a,a.visualProperties.chartIcons&&a.visualProperties.chartIcons[m]||d._getDefaultIcon(),h,t,m,p&&p[u])})}}},_floatingIconsSection:null,_renderFloatingIcons:function(a){var b=
a.visualProperties.floatingIcons;if(b&&b.length){b.forEach(function(b){b=b.data.data[0].fieldInfos[b.data.columns[0].field].shapeJson;var d=a.viewModel.getChartDefaultStyles(a.theme||a.themeContext);m.applyThemeSettingsToShapeJson(b,d)});var d={"class":"chartContainer_floatingIconSection"};d.initialWidth=a.chartW;d.json={type:n.DETAILS,stack:b};d.viewModel=a.viewModel;d.themeContext=a.themeContext;d.theme=a.theme;d.tableClass="chartContainerFloatingIconTable";d.hasFixedLayout=!1;this._provideParamsForFloatingIconSection(d,
a);this._floatingIconsSection=a.viewModel.layoutBuilder.createElement("section",d,a.iconNode);this._floatingIconsSection.setResizedHeight(a.chartH);this._floatingIconsSection.setViewMode(this._viewMode||"edit")}},_provideParamsForFloatingIconSection:function(a,b){},_getDefaultIcon:function(){},_iconSections:null,_createIconSection:function(a,b,d,e,g,c){if(b&&(b.imageJson||b.shapeJson)){if(b.shapeJson){var f=a.viewModel.getChartDefaultStyles(a.theme||a.themeContext);m.applyThemeSettingsToShapeJson(b.shapeJson,
f);b.shapeJson.themeStyle&&c&&(b.shapeJson.themeStyle.borderColor=c,b.shapeJson.themeStyle.fillColor=c)}b=y.createSingleCellTable({width:d,height:d,fieldInfo:b.imageJson?l.createFieldInfoFromImage(b.imageJson):l.createFieldInfoFromShape(b.shapeJson),cellStyle:{backgroundColor:"transparent"}});c={};c.initialWidth=d;c.json={type:n.DETAILS,stack:[b]};c.viewModel=a.viewModel;c.themeContext=a.themeContext;c.theme=a.theme;c.tableClass="chartContainerIconTable";c.hasFixedLayout=!0;this._provideParamsForIconSection(c,
a);a=a.viewModel.layoutBuilder.createElement("section",c,e);a.setResizedHeight(d);a.setViewMode(this._viewMode||"edit");a.__unsortedIndex=g;this._iconSections.push(a)}},_getSectionUnsortedIndex:function(a){return a&&void 0!==a.__unsortedIndex?a.__unsortedIndex:-1},_provideParamsForIconSection:function(a,b,d){},_viewMode:null,setViewMode:function(a){this._viewMode=a;this._iconSections&&this._iconSections.forEach(function(b){b.setViewMode(a)});this._floatingIconsSection&&this._floatingIconsSection.setViewMode(a)},
_destroyIcons:function(){this._iconSections=this._iconSections||[];this._iconSections.forEach(function(a){var b=a.domNode&&a.domNode.parentNode;a.destroy();b&&q.destroy(b)});this._iconSections.length=0;this._floatingIconsSection&&this._floatingIconsSection.destroy();this._floatingIconsSection=null},destroy:function(){this._destroyIcons();this.inherited(arguments)}})});