// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/AdjustableGrid","dojo/_base/declare dojo/_base/lang dojo/on dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin ./_GridHighlightSupport ./ValueField ./coreUtils/GridBorderUtil ./coreUtils/GridDataUtil ./coreUtils/GridQueryUtil ./coreUtils/GridLayoutCalculator ./coreUtils/GridCellRenderer ./coreUtils/GridStyleUtil ./coreUtils/GridSortUtil ../themes/BorderStyles esri/dijit/geoenrichment/utils/DomUtil".split(" "),
function(p,l,B,k,n,C,g,q,r,t,u,v,h,D,f,w,x,m,E,y){var z={defaultRowHeight:15.33,rowMinHeight:3,columnMinWidth:3,defaultChartRowHeight:150};return p([q,r,t],{templateString:"\x3cdiv class\x3d'esriGEAdjustableGrid'\x3e\x3cdiv data-dojo-attach-point\x3d'mainNode' class\x3d'adjustableGridMainNode'\x3e\x3c/div\x3e\x3c/div\x3e",viewModel:null,themeContext:null,theme:null,columns:null,store:null,getPreviewValueFunction:null,previewFeatureIndex:null,fixedViewMode:null,fieldCellClass:null,applyThemeStyle:!0,
layoutDefaults:null,renderBordersFromTheme:!1,inheritThemeBackground:!0,renderCellBackground:!0,stickToRight:!1,looseResize:!1,keepGridSizeWhenResized:!1,allowSorting:!1,trimTextIfOverflows:!1,_cellRenderer:null,_createdFlag:!1,_fieldCells:null,_dynamicBindings:null,_isBeingResizedFlag:!1,postCreate:function(){this.inherited(arguments);this.layoutDefaults=l.mixin({},z,this.layoutDefaults);this._createdFlag=!0;this.setViewMode(null)},_renderInfo:null,refresh:function(a){this.domNode&&(a=a||{},f.markAsDirty(this),
a.preserveFocus||a.preserveFocusAll?this.__refreshAndPreserveFocus(a):this.__simpleRefresh(a),m.updateSorting(this,!1!==a.applyCurrentSorting))},__simpleRefresh:function(a){this.mainNode&&(a=a||{},this.store&&this._createdFlag&&(this._destroyFields(),n.empty(this.mainNode),this.isEmptyTable()?n.create("div",{"class":"adjustableGrid_emptyRow"},this.mainNode):(f.recalcRows(this),void 0===a.stickToRight&&(a.stickToRight=this.stickToRight),f.recalcColumns(this,a),f.autoSnapLayout(this),this._renderStoreData(),
this._processEdgeCells(),v.renderBorder(this,this._renderInfo),f.positionCells(this))))},__refreshAndPreserveFocus:function(a){this.__simpleRefresh(a)},getVisualState:function(){return{sorting:m.getSorting(this),cells:this.getFieldCells().map(function(a){return a.content&&a.content.getVisualState&&a.content.getVisualState()})}},setVisualState:function(a){if(a&&(a.sorting&&m.setSorting(this,a.sorting),a.cells)){var b=this.getFieldCells();a.cells.length==b.length&&b.forEach(function(b,d){b.content&&
b.content.setVisualState&&b.content.setVisualState(a.cells[d])})}},_renderStoreData:function(){var a=this,b=!0;this.store.data.forEach(function(c){a.columns.forEach(function(d,e){if(!(c.excludedIndexHorizontal&&c.excludedIndexHorizontal[e]||c.excludedIndexVertical&&c.excludedIndexVertical[e])){var A=d.index+(h.getDataColumnSpan(c,d.field)||1)==a.columns.length,f=c.index+(h.getDataRowSpan(c,d.field)||1)==a.store.data.length;a._createField(c,d,b,A,f)}});b=!b})},_processEdgeCells:function(){this._renderInfo=
{firstInRowCells:[],firstInColumnCells:[],lastInRowCells:[],lastInColumnCells:[]};var a=[],b=[];this._fieldCells.forEach(function(c){a[c.gridData.index]=a[c.gridData.index]||[];a[c.gridData.index][c.column.index]=c;b[c.column.index]=b[c.column.index]||[];b[c.column.index][c.gridData.index]=c});var c=this;a.forEach(function(b,e){a[e][0]&&c._renderInfo.firstInRowCells.push(a[e][0]);var d=a[e][a[e].length-1];if(d.column.index==c.columns.length-1||d.column.index+h.getColumnSpan(d)==c.columns.length)k.add(d.domNode,
"lastInRow"),c._renderInfo.lastInRowCells.push(d)});b.forEach(function(a,e){b[e][0]&&c._renderInfo.firstInColumnCells.push(b[e][0]);var d=b[e][b[e].length-1];k.add(d.domNode,"lastRow");c._renderInfo.lastInColumnCells.push(d)})},_destroyFields:function(){this._renderInfo=null;this._fieldCells=this._fieldCells||[];this._fieldCells.forEach(function(a){a.parentGrid=null;a.gridData=null;a.column=null;a.destroy()});this._fieldCells.length=0},_getFieldClass:function(){return u},_createField:function(a,b,
c,d,e){var f=this,h={fieldStyle:x.combineCellStyle(this,a,b),"class":"adjustableGridField",fieldCellClass:this.fieldCellClass,trimTextIfOverflows:this.trimTextIfOverflows,rowId:a.id,columnId:b.id,parentGrid:this,uniqueId:a.id+b.id,gridData:a,column:b,isOddRow:c,getBorders:function(){return f._getFieldCellBorders(d,e)}};a=this._doCreateFieldFromParams(h,a,b,c);g.set(a.domNode,"position","absolute");this._renderFieldContent(a);k.add(a.domNode,"adjustableGrid_cell field-"+b.field);this._fieldCells.push(a);
this._postCreateFieldCell(a);return a},_doCreateFieldFromParams:function(a,b,c,d){return(new this._getFieldClass)(a).placeAt(this.mainNode)},_postCreateFieldCell:function(a){},_getFieldCellBorders:function(a,b){var c="_fieldCellBorders"+!!a+!!b;return this[c]=this[c]||{outer:{t:1,b:b?1:0,l:1,r:a?1:0},inner:{t:1,b:1,l:1,r:1}}},_preRenderFieldCell:function(a){},_postRenderFieldCell:function(a){},_renderFieldContent:function(a){this._preRenderFieldCell(a);this._getCellRenderer().renderCellContent(a);
this._configureRenderedCellContentSpecificStyles(a);this._postRenderFieldCell(a)},_configureRenderedCellContentSpecificStyles:function(a){k[h.isVariableFieldCell(a)?"add":"remove"](a.domNode,"hasVariableFieldInfo");k[h.getConditionalFormatting(a)?"add":"remove"](a.domNode,"hasConditionalFormatting")},_getCellRenderer:function(){this._cellRenderer||(this._cellRenderer=new w);return this._cellRenderer},_setCellWidth:function(a,b){f.adjustColumnWidth(this,a.gridData,a.column,b);f.positionCells(this)},
_setCellHeight:function(a,b){f.adjustRowHeight(this,a.gridData,a.column.field,b);f.positionCells(this)},setCellWidth:function(a,b){this._setCellWidth(a,b)},setCellHeight:function(a,b){this._setCellHeight(a,b)},_maxWidth:500,_width:500,_height:0,_spaceAfter:0,_maxHeight:0,getMaxHeight:function(a){return this._maxHeight},setMaxHeight:function(a){this._maxHeight=a},getHeight:function(a,b){return g.get(this.domNode,"height")+(!1!==b?g.get(this.domNode,"top"):0)+(a?this._spaceAfter||0:0)},getMaxWidth:function(){return this._maxWidth},
setMaxWidth:function(a,b){var c=0;b&&b.preserveRightOffset&&(f.recalcGridWidth(this),c=this.getAllowedWidth(),c=(c-this._width)/c);this._maxWidth=a;b&&b.resizeToFitAllowedWidth&&this.resizeToFitAllowedWidth({rightOffsetWeight:b.preserveRightOffset?c:0})},setSpaceAfter:function(a){this._spaceAfter=a},getAllowedWidth:function(){return this._maxWidth-g.get(this.domNode,"left")},getAllowedWidthFromParent:function(){return g.get(this.domNode.parentNode,"width")-g.get(this.domNode,"left")},getTableBox:function(){var a=
this.getSettings().style;return{l:a.left,t:a.spaceBefore,w:a.width,h:this.getHeight(!1,!1)}},getDomPosition:function(){return y.position(this.domNode)},resizeToFitAllowedWidth:function(a){},resizeToFitWidth:function(a){},resizeToFitHeight:function(a,b){},scaleProportionallyWithinParent:function(a){},collapseContent:function(){this.getFieldCells().forEach(function(a){a.content&&a.content.collapseContent&&a.content.collapseContent()})},hasHiddenContent:function(){return this._checkNeedResizeRowHeightToShowCellsContent(!1)},
resizeRowHeightToShowCellsContent:function(){this._checkNeedResizeRowHeightToShowCellsContent(!0)},_checkNeedResizeRowHeightToShowCellsContent:function(a){var b=this,c;this.getFieldCells().forEach(function(d){if(d.content&&d.content.getPreferredHeight){var e=d.content.getPreferredHeight();e>d.getHeight()&&(a&&(e&&(e+=10),b._setCellHeight(d,e)),c=!0)}});return c},_tableAttributes:null,setSettings:function(a){var b,c=g.get(this.domNode,"left");this.columns.forEach(function(a){a.style&&"number"==typeof a.style.width&&
(a._wasBeforeRecalc=!0)});if(a.style){void 0!==a.style.left&&g.set(this.domNode,"left",a.style.left+"px");void 0!==a.style.spaceBefore&&g.set(this.domNode,"top",a.style.spaceBefore+"px");void 0!==a.style.spaceAfter&&(this._spaceAfter=a.style.spaceAfter);a.style.width&&(this._width=a.style.width);var d=this._width;this._width=Math.min(this._width,this.getAllowedWidth());if(this._width!=d||c!=g.get(this.domNode,"left"))b=!0}a.attributes&&(this._adjustColumnsForSettings(a)&&(b=!0),this._tableAttributes=
a.attributes,this._tableAttributes.rowCount&&this._tableAttributes.rowCount!==this.store.data.length&&this._adjustRowsForSettings(a),delete this._tableAttributes.rowCount,delete this._tableAttributes.columnCount);void 0!==a.scaleToFitWidth&&(this._scaleToFitWidth=a.scaleToFitWidth);void 0!==a.scaleToFitHeight&&(this._scaleToFitHeight=a.scaleToFitHeight);this._tableAttributes=this._tableAttributes||{};var e=[];this.columns.forEach(function(a){a._wasBeforeRecalc&&e.push(a);delete a._wasBeforeRecalc});
this.viewModel.dynamicReportInfo&&this.getNumDynamicColumns()?(f.trimColumnsForNumberOfFeatures(this),this.refresh({resetWidth:!0})):this.viewModel.dynamicReportInfo&&this.getNumDynamicRows()?(f.adjustRowsForNumberOfFeatures(this),this.refresh()):b?this.refresh({resetWidth:!0,columnsToPreserve:e}):this.refresh()},_adjustColumnsForSettings:function(a){return!1},_adjustRowsForSettings:function(a){},getSettings:function(){f.recalcGridWidth(this);return{style:{width:this._width,left:g.get(this.domNode,
"left"),spaceBefore:g.get(this.domNode,"top"),spaceAfter:this._spaceAfter},attributes:l.mixin(l.clone(this._tableAttributes),{columnCount:this.columns.length,rowCount:this.store.data.length}),scaleToFitWidth:this._scaleToFitWidth,scaleToFitHeight:this._scaleToFitHeight}},needScaleToFitWidth:function(){return this._scaleToFitWidth},needScaleToFitHeight:function(){return this._scaleToFitHeight},isEmptyTable:function(){return!this.columns||!this.columns.length||!this.store||!this.store.data.length},
isMultiFeatureTable:function(){return!!this.getNumDynamicColumns()||!!this.getNumDynamicRows()},getNumFixedColumns:function(){return this._tableAttributes&&this._tableAttributes.fixedColumns||0},setNumFixedColumns:function(a){this._tableAttributes.fixedColumns=a},getNumDynamicColumns:function(){return this._tableAttributes&&this._tableAttributes.dynamicColumns||0},setNumDynamicColumns:function(a){this._tableAttributes.dynamicColumns=a},getNumFixedRows:function(){return this._tableAttributes&&this._tableAttributes.fixedRows||
0},setNumFixedRows:function(a){this._tableAttributes.fixedRows=a},getNumDynamicRows:function(){return this._tableAttributes&&this._tableAttributes.dynamicRows||0},setNumDynamicRows:function(a){this._tableAttributes.dynamicRows=a},_viewMode:null,_specificViewMode:null,getViewMode:function(){return this._viewMode},getSpecificViewMode:function(){return this._specificViewMode},setViewMode:function(a,b){var c=this;this._viewMode=a=this.fixedViewMode||a;void 0!==b&&(this._specificViewMode=b);"edit"==a?
(k.add(this.domNode,"adjustableGridEditMode"),k.remove(this.domNode,"adjustableGridPreviewMode")):(k.remove(this.domNode,"adjustableGridEditMode"),k.add(this.domNode,"adjustableGridPreviewMode"));this._fieldCells&&this._fieldCells.forEach(function(b){b.content&&b.content.setViewMode&&b.content.setViewMode(a,c._specificViewMode);c._getCellRenderer().updateViewMode(b)})},getFieldCells:function(){return this._fieldCells},getFirstCell:function(){return this.getFieldCells()[0]},getCellText:function(a){return h.getFieldCellText(a)},
renderCell:function(a){this._renderFieldContent(a)},getInfographicJson:function(){var a=this.getFirstCell();return h.isInfographicCell(a)?h.getFieldInfo(a).infographicJson:null},getChartJson:function(){var a=this.getFirstCell();return h.isChartCell(a)?h.getFieldInfo(a).chartJson:null},toJson:function(){var a=this.getSettings();a.id="table";a.data={data:this.store.data,columns:this.columns};return l.clone(a)},notifyShown:function(){this.getFieldCells().forEach(function(a){a.content&&a.content.notifyShown&&
a.content.notifyShown()})},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},onRequestScaleToFitHeight:function(){},destroy:function(){this._destroyFields();this.inherited(arguments)}})});