// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/FillBucket","require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ../../core/ArrayPool ./Bucket ../2d/engine/webgl/Geometry ../../core/libs/earcut/earcut".split(" "),function(B,C,y,D,w,z,v,A){return function(x){function f(b,k,e,d,a,c){b=x.call(this,b,k)||this;b.polygonVertexBuffer=e;b.polygonIndexBuffer=d;b.polygonOutlineVertexBuffer=a;b.polygonOutlineIndexBuffer=c;return b}y(f,x);Object.defineProperty(f.prototype,
"polygonIndexStart",{get:function(){return this._triangleElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"polygonIndexCount",{get:function(){return this._triangleElementsNum},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"polygonOutlineIndexStart",{get:function(){return this._outlineElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"polygonOutlineIndexCount",{get:function(){return this._outlineElementsNum},enumerable:!0,
configurable:!0});f.prototype.assignBufferInfo=function(b){b._triangleElementsStart=this._triangleElementsStart;b._triangleElementsNum=this._triangleElementsNum;b.layer.hasPaintProperty("fill-outline-color")?(b._outlineElementsStart=this._outlineElementsStart,b._outlineElementsNum=this._outlineElementsNum):(b._outlineElementsStart=0,b._outlineElementsNum=0)};f.prototype.processFeatures=function(b,k){this._triangleElementsStart=this.polygonIndexBuffer.index;this._triangleElementsNum=0;this._outlineElementsStart=
this.polygonOutlineIndexBuffer.index;this._outlineElementsNum=0;b&&b.setExtent(this.layerExtent);for(var e=this.layer.getPaintValue("fill-pattern",this.zoom),e=this.layer.getPaintValue("fill-antialias",this.zoom)&&void 0===e,d=0,a=this._features;d<a.length;d++){var c=a[d].getGeometry(b);this._processFeature(c,e)}};f.prototype._processFeature=function(b,k){if(b){var e=b.length;if(k)for(var d=0;d<e;d++)this._processOutline(b[d]);for(var a,d=0;d<e;d++){var c=f._area(b[d]);128<c?(void 0!==a&&this._processFill(b,
a),a=[d]):-128>c&&void 0!==a&&a.push(d)}void 0!==a&&this._processFill(b,a)}};f.prototype._processOutline=function(b){var k=this.polygonOutlineVertexBuffer,e=this.polygonOutlineIndexBuffer,d=e.index,a,c,f,l=new v.Point(0,0),m=new v.Point(0,0),n=new v.Point(0,0),h=-1,g=-1,r=a=-1,u=-1,p=b.length;if(!(2>p)){var t=b[0];for(a=b[p-1];p&&a.isEqual(t);)--p,a=b[p-1];if(!(2>p-0)){for(t=0;t<p;++t){0===t?(a=b[p-1],c=b[0],f=b[1],l.assignSub(c,a),l.normalize(),l.rightPerpendicular()):(a=c,c=f,f=t!==p-1?b[t+1]:b[0],
l.assign(m));m.assignSub(f,c);m.normalize();m.rightPerpendicular();a=l.x*m.y-l.y*m.x;n.assignAdd(l,m);n.normalize();var q=-n.x*-l.x+-n.y*-l.y,q=Math.abs(0!==q?1/q:1);8<q&&(q=8);0<=a?(a=k.add(c.x,c.y,l.x,l.y,0,1),-1===r&&(r=a),0<=h&&0<=g&&0<=a&&e.add(h,g,a),g=k.add(c.x,c.y,q*-n.x,q*-n.y,0,-1),-1===u&&(u=g),0<=h&&0<=g&&0<=a&&e.add(h,g,a),h=g,g=a,a=k.add(c.x,c.y,n.x,n.y,0,1),0<=h&&0<=g&&0<=a&&e.add(h,g,a),g=k.add(c.x,c.y,m.x,m.y,0,1)):(a=k.add(c.x,c.y,q*n.x,q*n.y,0,1),-1===r&&(r=a),0<=h&&0<=g&&0<=a&&
e.add(h,g,a),g=k.add(c.x,c.y,-l.x,-l.y,0,-1),-1===u&&(u=g),0<=h&&0<=g&&0<=a&&e.add(h,g,a),h=g,g=a,a=k.add(c.x,c.y,-n.x,-n.y,0,-1),0<=h&&0<=g&&0<=a&&e.add(h,g,a),h=k.add(c.x,c.y,-m.x,-m.y,0,-1));0<=h&&0<=g&&0<=a&&e.add(h,g,a)}0<=h&&0<=g&&0<=r&&e.add(h,g,r);0<=h&&0<=r&&0<=u&&e.add(h,u,r);this._outlineElementsNum+=3*(e.index-d)}}};f.prototype._processFill=function(b,k){var e;1<k.length&&(e=[]);for(var d=0,a=0;a<k.length;a++){var c=k[a];0!==d&&e.push(d);d+=b[c].length}for(var a=2*d,d=w.acquire(),f=0;f<
k.length;f++)for(var c=k[f],c=b[c],l=c.length,m=0;m<l;++m)d.push(c[m].x),d.push(c[m].y);e=A(d,e,2);f=e.length;if(0<f){c=this.polygonVertexBuffer.index;for(l=0;l<a;)this.polygonVertexBuffer.add(d[l++],d[l++]);for(a=0;a<f;)this.polygonIndexBuffer.add(c+e[a++],c+e[a++],c+e[a++]);this._triangleElementsNum+=f}w.release(d)};f._area=function(b){for(var f=0,e=b.length-1,d=0;d<e;d++)f+=(b[d].x-b[d+1].x)*(b[d].y+b[d+1].y);f+=(b[e].x-b[0].x)*(b[e].y+b[0].y);return.5*f};return f}(z)});