// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/SymbolBucket","require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ./Bucket ../2d/engine/webgl/Geometry ./style/StyleLayer ./Placement ./GeometryUtils ./TextShaping dojox/string/BidiEngine".split(" "),function(O,P,H,Q,I,y,E,F,u,J,K){function L(u,h){if(u.iconMosaicItem&&h.iconMosaicItem){if(u.iconMosaicItem.page!==h.iconMosaicItem.page)return u.iconMosaicItem.page<h.iconMosaicItem.page?-1:1}else{if(u.iconMosaicItem&&
!h.iconMosaicItem)return 1;if(!u.iconMosaicItem&&h.iconMosaicItem)return-1}return 0}var M=function(){return function(){}}(),N=function(){return function(u,h,a,f){this.line=h;this.shaping=u;this.iconMosaicItem=a;this.anchor=f}}();(function(){return function(){}})();return function(G){function h(a,f,c,d,b,e,g,l){a=G.call(this,a,f)||this;a._markerRatio=1;a._markerMap=new Map;a._glyphMap=new Map;a._glyphBufferDataStorage=new Map;a._markerVertexBuffer=c;a._markerIndexBuffer=d;a._textVertexBuffer=b;a._textIndexBuffer=
e;a._placementEngine=g;a._workerTileHandler=l;return a}H(h,G);Object.defineProperty(h.prototype,"markerPageMap",{get:function(){return this._markerMap},enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"glyphsPageMap",{get:function(){return this._glyphMap},enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"textIndexStart",{get:function(){return this._textTriangleElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"textIndexCount",{get:function(){return this._textTriangleElementsNum},
enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"sdfMarker",{get:function(){return!1},enumerable:!0,configurable:!0});h.prototype.copy=function(a,f,c,d,b){b=new h(this.layer,this.zoom,a,f,c,d,b,this._workerTileHandler);b.layerIndex=this.layerIndex;b.layerExtent=this.layerExtent;b._markerVertexStart=a.index;b._markerTriangleElementsStart=f.index;b._textVertexStart=c.index;b._textTriangleElementsStart=d.index;b._markerTriangleElementsNum=0;b._textTriangleElementsNum=0;b._symbolInstances=
this._symbolInstances;b._workerTileHandler=this._workerTileHandler;b._font=this._font;b._textLayout=this._textLayout;b._markerLayout=this._markerLayout;b._isLinePlacement=this._isLinePlacement;b._avoidEdges=this._avoidEdges;return b};h.prototype.getResources=function(a,f,c){var d=this.layer,b=this.zoom;a&&a.setExtent(this.layerExtent);for(var e=d.getLayoutValue("icon-image",b),g=d.getLayoutValue("text-field",b),l=d.getLayoutValue("text-font",b),d=d.getLayoutValue("text-transform",b),b=[],A=0,t=this._features;A<
t.length;A++){var p=t[A],v=p.getGeometry(a);if(v&&0!==v.length){var m=void 0;e&&(m=this._replaceKeys(e,p.values))&&f.add(m);var k=void 0,q=!1;if(g){k=this._replaceKeys(g,p.values);switch(d){case 2:k=k.toLowerCase();break;case 1:k=k.toUpperCase()}h._bidiEngine.hasBidiChar(k)&&(q=void 0,q="rtl"===h._bidiEngine.checkContextual(k)?"IDNNN":"ICNNN",k=h._bidiEngine.bidiTransform(k,q,"VLYSN"),q=!0);p=k.length;if(0<p){var n=c[l];n||(n=c[l]=new Set);for(var r=0;r<p;r++){var u=k.charCodeAt(r);n.add(u)}}}if(m||
k)p=new M,p.sprite=m,p.label=k,p.rtl=q,p.geometry=v,b.push(p)}}this._symbolFeatures=b};h.prototype.processFeatures=function(a,f){a&&a.setExtent(this.layerExtent);var c=this.layer,d=this.zoom,b=this._isLinePlacement=1===c.getLayoutValue("symbol-placement",d),e=this._avoidEdges=c.getLayoutValue("symbol-avoid-edges",d)&&!b,g=8*c.getLayoutValue("symbol-spacing",d),l=c.getLayoutValue("icon-image",d),A=c.getLayoutValue("text-field",d),t=this._workerTileHandler,p;l&&(this._markerLayout=new E.IconLayout(c,
d,b),p=t.getSpriteItems());var v,m;if(A){var k=this._textLayout=new E.TextLayout(c,d,b);v=void 0;k.font&&k.font.length&&(this._font=v=k.font[0]);m=.5;switch(k.anchor){case 5:case 1:case 7:m=0;break;case 6:case 2:case 8:m=1}c=.5;switch(k.anchor){case 5:case 3:case 6:c=0;break;case 7:case 4:case 8:c=1}d=.5;switch(k.justify){case 0:d=0;break;case 2:d=1}var l=24*k.letterSpacing,A=b?0:24*k.maxWidth,q=24*k.lineHeight,k=[24*k.offset[0],24*k.offset[1]];v=t.getGlyphItems(v);m=new J(v,A,q,l,k,m,c,d)}this._markerVertexStart=
this._markerVertexBuffer.index;this._markerTriangleElementsStart=this._markerIndexBuffer.index;this._textVertexStart=this._textVertexBuffer.index;this._textTriangleElementsStart=this._textIndexBuffer.index;this._textTriangleElementsNum=this._markerTriangleElementsNum=0;this._markerMap.clear();this._glyphMap.clear();this._symbolInstances=t=[];c=this._textLayout;d=1;c&&c.size&&(d=c.size/24);l=c?c.maxAngle*u.C_DEG_TO_RAD:0;A=c?8*c.size:0;q=0;for(k=this._symbolFeatures;q<k.length;q++){var n=k[q],r=void 0;
n.sprite&&(r=p[n.sprite]);var C=void 0,x=n.label,w=0;if(x&&(C=m.getShaping(x,n.rtl))&&0<C.length){for(var w=1E30,x=-1E30,z=0,B=C;z<B.length;z++)var y=B[z],w=Math.min(w,y.x),x=Math.max(x,y.x);w=(x-w+48)*d*8}x=0;for(n=n.geometry;x<n.length;x++)for(z=n[x],y=void 0,b?(C&&0<C.length&&c&&c.size&&h._smoothVertices(z,8*c.size*(2+Math.min(2,4*Math.abs(c.offset[1])))),y=h._findAnchors(z,g,w)):y=[new F.Anchor(z[0].x,z[0].y)],B=0;B<y.length;B++){var D=y[B];0>D.x||4096<D.x||0>D.y||4096<D.y||b&&0<w&&0===c.rotationAlignment&&
!h._honorsTextMaxAngle(z,D,w,l,A)||t.push(new N(C,z,r,D))}}t.sort(L);for(b=0;b<t.length;b++)this._processFeature(t[b],v,e);this._addPlacedGlyphs()};h.prototype.updateSymbols=function(){this._markerVertexStart=this._markerVertexBuffer.index;this._markerTriangleElementsStart=this._markerIndexBuffer.index;this._textVertexStart=this._textVertexBuffer.index;this._textTriangleElementsStart=this._textIndexBuffer.index;this._textTriangleElementsNum=this._markerTriangleElementsNum=0;this._markerMap.clear();
this._glyphMap.clear();for(var a=this._workerTileHandler.getGlyphItems(this._font),f=this._avoidEdges,c=0,d=this._symbolInstances;c<d.length;c++)this._processFeature(d[c],a,f);this._addPlacedGlyphs()};h.prototype._replaceKeys=function(a,f){return a.replace(/{([^{}]+)}/g,function(a,d){return d in f?f[d]:""})};h.prototype._processFeature=function(a,f,c){var d=a.line,b=a.iconMosaicItem,e=a.shaping,g=a.anchor,l=(a=this._markerLayout)&&!!b,A=!0,t=1;l&&(t=a.size/(1/this._markerRatio)*8,A=a.optional||!b);
var p=this._textLayout,h=p&&e&&0<e.length,m;m=1;var k=!0;h&&(m=p.size/24,m*=8,k=p.optional||!e||0===e.length);var q=new y.Point(0,-17),n;if(l){n=this._placementEngine.getIconPlacement(g,b,t,d,a,c);if(n.footprint.minzoom===u.C_INFINITY&&!A)return;g.minzoom>n.footprint.minzoom&&(n.footprint.minzoom=g.minzoom)}var r;if(h&&(r=this._placementEngine.getTextPlacement(g,q,e,f,m,d,p,c))){if(r.footprint.minzoom===u.C_INFINITY&&!k)return;g.minzoom>r.footprint.minzoom&&(r.footprint.minzoom=g.minzoom)}if(!k&&
!A||!A&&r&&r.footprint.minzoom!==u.C_INFINITY||!k&&n&&n.footprint.minzoom!==u.C_INFINITY)f=Math.max(n.footprint.minzoom,r.footprint.minzoom),n.footprint.minzoom=f,r.footprint.minzoom=f;r&&r.footprint.minzoom!==u.C_INFINITY&&(p.ignorePlacement||this._placementEngine.add(r),this._storePlacedGlyphs(r.shapes,r.footprint.minzoom,this.zoom));n&&n.footprint.minzoom!==u.C_INFINITY&&(a.ignorePlacement||this._placementEngine.add(n),this._addPlacedIcons(n.shapes,n.footprint.minzoom,this.zoom,b.page))};h.prototype._addPlacedIcons=
function(a,f,c,d){f=Math.max(c+u.log2(f),0);for(var b=this._markerVertexBuffer,e=this._markerIndexBuffer,g=0;g<a.length;g++){var l=a[g],h=Math.max(c+u.log2(l.minzoom),f),t=Math.min(c+u.log2(l.maxzoom),25);if(!(t<=h)){var p=l.tl,v=l.tr,m=l.bl,k=l.br,q=l.mosaicRect,n=-l.labelAngle,l=l.anchor,r=b.index,y=q.x,x=q.y,w=y+q.width,q=x+q.height;b.add(l.x,l.y,p.x,p.y,y,x,n,h,t,f);b.add(l.x,l.y,v.x,v.y,w,x,n,h,t,f);b.add(l.x,l.y,m.x,m.y,y,q,n,h,t,f);b.add(l.x,l.y,k.x,k.y,w,q,n,h,t,f);e.add(r+0,r+1,r+2);e.add(r+
1,r+2,r+3);this._markerMap.has(d)?this._markerMap.get(d)[1]+=6:this._markerMap.set(d,[this._markerTriangleElementsStart+this._markerTriangleElementsNum/3,6]);this._markerTriangleElementsNum+=6}}};h.prototype._addPlacedGlyphs=function(){var a=this,f=this._textVertexBuffer,c=this._textIndexBuffer;this._glyphBufferDataStorage.forEach(function(d,b){for(var e=0;e<d.length;e++){var g=d[e],l=f.index;f.add(g.glyphAnchor[0],g.glyphAnchor[1],g.tl[0],g.tl[1],g.xmin,g.ymin,g.labelAngle,g.minLod,g.maxLod,g.placementLod);
f.add(g.glyphAnchor[0],g.glyphAnchor[1],g.tr[0],g.tr[1],g.xmax,g.ymin,g.labelAngle,g.minLod,g.maxLod,g.placementLod);f.add(g.glyphAnchor[0],g.glyphAnchor[1],g.bl[0],g.bl[1],g.xmin,g.ymax,g.labelAngle,g.minLod,g.maxLod,g.placementLod);f.add(g.glyphAnchor[0],g.glyphAnchor[1],g.br[0],g.br[1],g.xmax,g.ymax,g.labelAngle,g.minLod,g.maxLod,g.placementLod);c.add(l+0,l+1,l+2);c.add(l+1,l+2,l+3);a._glyphMap.has(b)?a._glyphMap.get(b)[1]+=6:a._glyphMap.set(b,[a._textTriangleElementsStart+a._textTriangleElementsNum/
3,6]);a._textTriangleElementsNum+=6}});this._glyphBufferDataStorage.clear()};h.prototype._storePlacedGlyphs=function(a,f,c){f=Math.max(c+u.log2(f),0);for(var d=0;d<a.length;d++){var b=a[d],e=Math.max(c+u.log2(b.minzoom),f),g=Math.min(c+u.log2(b.maxzoom),25);if(!(g<=e)){var l=b.tl,h=b.tr,t=b.bl,p=b.br,v=-b.labelAngle,m=b.anchor,k=b.mosaicRect;this._glyphBufferDataStorage.has(b.page)||this._glyphBufferDataStorage.set(b.page,[]);this._glyphBufferDataStorage.get(b.page).push({glyphAnchor:[m.x,m.y],tl:[l.x,
l.y],tr:[h.x,h.y],bl:[t.x,t.y],br:[p.x,p.y],xmin:k.x,ymin:k.y,xmax:k.x+k.width,ymax:k.y+k.height,labelAngle:v,minLod:e,maxLod:g,placementLod:f})}}};h._findAnchors=function(a,f,c){f+=c;for(var d=0,b=a.length-1,e=0;e<b;e++)d+=y.Point.distance(a[e],a[e+1]);e=.5*(c||f);if(d<=e)return[];c=e/d;f=d/Math.max(Math.round(d/f),1);for(var d=0,b=-f/2,g=[],l=a.length-1,e=0;e<l;e++){for(var h=a[e],t=a[e+1],p=t.x-h.x,v=t.y-h.y,m=Math.sqrt(p*p+v*v),k=void 0;b+f<d+m;){var b=b+f,q=(b-d)/m,n=u.interpolate(h.x,t.x,q),
q=u.interpolate(h.y,t.y,q);void 0===k&&(k=Math.atan2(v,p));g.push(new F.Anchor(n,q,k,e,c))}d+=m}return g};h.deviation=function(a,f,c){return Math.atan2((f.x-a.x)*(c.y-f.y)-(f.y-a.y)*(c.x-f.x),(f.x-a.x)*(c.x-f.x)+(f.y-a.y)*(c.y-f.y))};h._honorsTextMaxAngle=function(a,f,c,d,b){var e=0;c/=2;for(var g=new y.Point(f.x,f.y),l=f.segment+1;e>-c;){--l;if(0>l)return!1;e-=y.Point.distance(a[l],g);g=a[l]}e+=y.Point.distance(a[l],a[l+1]);f=[];for(var g=0,h=a.length;e<c;){var t=a[l],p=void 0;do{++l;if(l===h)return!1;
p=a[l]}while(p.isEqual(t));var v=l,m=void 0;do{++v;if(v===h)return!1;m=a[v]}while(m.isEqual(p));t=this.deviation(t,p,m);f.push({deviation:t,distToAnchor:e});for(g+=t;e-f[0].distToAnchor>b;)g-=f.shift().deviation;if(Math.abs(g)>d)return!1;e+=y.Point.distance(p,m)}return!0};h._smoothVertices=function(a,f){if(!(0>=f)){var c=a.length;if(!(3>c)){var d=[],b=0;d.push(0);for(var e=1;e<c;e++)b+=y.Point.distance(a[e],a[e-1]),d.push(b);f=Math.min(f,.2*b);b=[];b.push(a[0].x);b.push(a[0].y);var g=a[c-1].x,l=a[c-
1].y,e=y.Point.sub(a[0],a[1]);e.normalize();a[0].x+=f*e.x;a[0].y+=f*e.y;e.assignSub(a[c-1],a[c-2]);e.normalize();a[c-1].x+=f*e.x;a[c-1].y+=f*e.y;for(e=1;e<c;e++)d[e]+=f;d[c-1]+=f;for(var h=.5*f,e=1;e<c-1;e++){for(var t=0,p=0,v=0,m=e-1;0<=m&&!(d[m+1]<d[e]-h);m--){var k=h+d[m+1]-d[e],q=d[m+1]-d[m],n=d[e]-d[m]<h?1:k/q;if(1E-6>Math.abs(n))break;var r=n*n,u=n*k-.5*r*q,x=n*q/f,w=a[m+1],z=a[m].x-w.x,B=a[m].y-w.y,t=t+x/u*(w.x*n*k+.5*r*(k*z-q*w.x)-r*n*q*z/3),p=p+x/u*(w.y*n*k+.5*r*(k*B-q*w.y)-r*n*q*B/3),v=
v+x}for(m=e+1;m<c&&!(d[m-1]>d[e]+h);m++){k=h-d[m-1]+d[e];q=d[m]-d[m-1];n=d[m]-d[e]<h?1:k/q;if(1E-6>Math.abs(n))break;r=n*n;u=n*k-.5*r*q;x=n*q/f;w=a[m-1];z=a[m].x-w.x;B=a[m].y-w.y;t+=x/u*(w.x*n*k+.5*r*(k*z-q*w.x)-r*n*q*z/3);p+=x/u*(w.y*n*k+.5*r*(k*B-q*w.y)-r*n*q*B/3);v+=x}b.push(t/v);b.push(p/v)}b.push(g);b.push(l);for(m=e=0;e<c;e++)a[e].x=b[m++],a[e].y=b[m++]}}};h._bidiEngine=new K;return h}(I)});