// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/FieldParser","esri/dijit/geoenrichment/utils/JsonXmlConverter ../../../supportClasses/templateJsonUtils/RichTextJsonUtil ../../../supportClasses/templateJsonUtils/FieldInfoBuilder ../../ConversionUtil ../../ShapeConverter ../../../annotations/annotationUtils/ShapeJsonUtil".split(" "),function(r,v,g,e,t,w){function n(a){(a=a.attributes||{},a.m)||!a.decimals&&!a.symbol&&void 0===a.thousands||(a.m={showCurrency:"currency"==
a.symbol,showPercent:"percent"==a.symbol,useThousandsSeparator:!1!==a.thousands,decimals:Number(a.decimals)||0});return a}function p(a,c,b){if(!a)return null;var d=b.variableProvider;a=a.substr(a.indexOf(".")+1).toUpperCase();return(b=b.queryMetaDataFunc(a))?g[b.isMissing?"createFieldInfoFromMissingVariable":b.isScript?"createFieldInfoFromScript":"createFieldInfoFromCalculator"](b,d,c):null}function u(a){return r.queryJson(a,/^d$|^text$|^reportName$|^reportTitle2/)}var h={},q={parseImageTrigger:function(a,
c){var b={fieldInfo:p(a.attributes.field,null,c),cases:[]},d=this;a.tags.forEach(function(a){var f="case"==a.name?a.attributes.key:"default";a=a.tags[0];var g=c.processFileName(a.attributes.value);b.cases.push({compareInfos:d._getCompareInfosFromTriggerKey(f),setters:[{property:a.attributes.property,value:g}]});c.putImageData(g)});return b},parseFieldTrigger:function(a,c,b){c.triggerJson={fieldInfo:b&&p(a.attributes.field,null,b),cases:[]};var d=this;a.tags.forEach(function(a){var b={compareInfos:d._getCompareInfosFromTriggerKey("case"==
a.name?a.attributes.key:"default"),setters:[]};c.triggerJson.cases.push(b);a.tags.forEach(function(a){b.setters.push({property:a.attributes.property,value:a.attributes.value})})})},_getCompareInfosFromTriggerKey:function(a){return a.split(e.KEY_INTERVAL_SEPARATOR).map(function(a){var b=e.ONE_FIELD_KEY_TEST.test(a)?a.replace(e.KEY_OPERATOR_RE,""):a;a=a.substr(0,a.length-b.length)||"\x3d";return{value:b,operator:a}})}},x={getFieldInfo:function(a,c,b,d){return(a=d.parsers.getParser("chart").portalToEditor(a,
c,d.queryMetaDataFunc,d.variableProvider,d))&&g.createFieldInfoFromChart(a)}},y={getFieldInfo:function(a,c,b,d){return(a=d.parsers.getParser("infographic").portalToEditor(a,c,d))&&g.createFieldInfoFromInfographic(a)}},z={getFieldInfo:function(a,c,b,d){c=d.processFileName(a.attributes.src);b={id:"img",fileName:c,circularMask:a.attributes.circularMask,style:{top:e.ptToPx(a.attributes.top),left:e.ptToPx(a.attributes.left),width:e.ptToPx(a.attributes.width),height:e.ptToPx(a.attributes.height),angle:Number(a.attributes.angle)||
0,opacity:Math.min(1,Number(0===a.attributes.opacity?0:a.attributes.opacity||1))}};1>d.revisionVersion&&(b.style.angle=e.ptToPx(b.style.angle),b.style.opacity=Math.min(1,e.ptToPx(b.style.opacity)));d.putImageData(c);var f;a.tags&&a.tags[0]&&"trigger"==a.tags[0].name&&(f=q.parseImageTrigger(a.tags[0],d));return g.createFieldInfoFromImage(b,f)}},A={getFieldInfo:function(a,c,b,d){c=t.svgJsonToShapeObject(a);a=t.getStylesFromSvgJson(a);a=w.createShapeJsonFromShapeObj(c,a);return g.createFieldInfoFromShape(a)}},
B={getFieldInfo:function(a,c,b,d){a=d.parsers.getParser("section").parseSection(a,d);return g.createFieldInfoFromSection(a)}},m={getFieldInfo:function(a,c,b,d,f){a=n(a);c=a[c||"f"];var l=g.createFieldInfoFromSpecialFieldName(c,a.m);if(!l){var e;2==b.tags.length&&"#text"==b.tags[1].name&&(e=b.tags[1].text);l=p(c,{format:a.m,additionalText:e},f)}l&&d&&q.parseFieldTrigger(d,l,f);return l}};h.parseField=function(a,c,b,d){var f;if(a){if("chart"==a.name)return x.getFieldInfo(a,c,b,d);if("infographic"==
a.name)return y.getFieldInfo(a,c,b,d);if("img"==a.name&&a.attributes)return z.getFieldInfo(a,c,b,d);if("svg"==a.name)return A.getFieldInfo(a,c,b,d);if("section"==a.name)return B.getFieldInfo(a,c,b,d);if("d"==a.name)f=m.getFieldInfo(a,null,c,b,d);else if("a"==a.name&&a.tags&&"d"==a.tags[0].name){var e=a.tags[0];(f=m.getFieldInfo(e,null,c,b,d))&&a.attributes&&a.attributes.hreff&&(f.linkFieldInfo=m.getFieldInfo(e,"hreff",c,b,d))}else f="text"==a.name?g.createFieldInfoFromSpecialFieldName(n(a).name):
g.createFieldInfoFromSpecialFieldName(a.name,n(a).m)}if(!f){a=u(c);if(1==a.length&&a[0].attributes&&"TrialUrlText"==a[0].attributes.name)return g.createFieldInfoFromSpecialFieldName(a[0].attributes.name);f=h.parseRichTextTag(c,d)}return f};h.parseRichTextTag=function(a,c){var b,d=u(a);if(d.length){var f=[],e=[],h=!0;d.some(function(b,d){var k=b.attributes?b.attributes.name:b.name,k="d"==b.name?m.getFieldInfo(b,null,a,null,c):k&&g.createFieldInfoFromSpecialFieldName(k);if(!k)return h=!1,!0;"d"==b.name?
f.push(k):e.push(k)});h&&(b=v.createFieldInfoFromRichText(r.getInnerHTML(a),f,e))}return b};h.parseFieldTrigger=function(a,c,b){c=c||{};q.parseFieldTrigger(a,c,b);return c.triggerJson};return h});