// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/InfographicConverterPtoE",["dojo/_base/lang","../../ConversionUtil","esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicTypes"],function(k,d,b){return{portalToEditor:function(a,p,f){function l(){var e=a.tags.slice(),b=e.shift();b&&"infographicHeader"==b.attributes.type&&(c={type:a.attributes.type,isDefault:a.attributes.isDefault,style:{width:d.ptToPx(a.attributes.width),height:d.ptToPx(a.attributes.height),
minWidth:d.ptToPx(a.attributes.minWidth),minHeight:d.ptToPx(a.attributes.minHeight),backgroundColor:a.attributes.backgroundColor},header:f.parsers.getParser("section").parseTable(b,f),variableTables:e.map(function(a){var c={style:d.ptToPxObj({left:a.attributes.left,top:a.attributes.top,width:a.attributes.width,height:a.attributes.height})};a.tags.forEach(function(a){var d=a.attributes.type,b=f.parsers.getParser("section").parseTable(a,f),e=b.data.data[0],g=b.data.columns[0].field;a={isContrastColor:a.attributes.isContrastColor,
isHighlighted:a.attributes.isHighlighted,style:k.mixin({width:b.data.columns[0].style.width,height:e.style.height,left:b.style.left,top:b.style.spaceBefore},e.style.fields[g])};"shape"==d&&(a.shapeJson=e.fieldInfos[g].shapeJson);"image"==d?a.imageJson=e.fieldInfos[g].imageJson:"variable"==d?a.fieldInfo=e.fieldInfos[g]:"description"==d&&(a.text=e[g]);c[d]=a});return c})})}function m(){var e,b,h;a.tags.forEach(function(a){switch(a.name){case "header":e=a;break;case "attributes":b=a;break;case "notes":h=
a}});c={type:a.attributes.type,showNotes:a.attributes.showNotes,showAttributes:a.attributes.showAttributes,attributesLayout:a.attributes.attributesLayout,style:{width:d.ptToPx(a.attributes.width),height:d.ptToPx(a.attributes.height),backgroundColor:a.attributes.backgroundColor},header:f.parsers.getParser("section").parseTable(e.tags[0],f),attributesStyle:f.parsers.getParser("section").parseTableCellAttributes(b&&b.attributes||{},null,f),notesStyle:f.parsers.getParser("section").parseTableCellAttributes(h&&
h.attributes||{},null,f)}}function n(){var b=f.templateJson.metadata.infographicCalculatorsHash[a.attributes.name];c={type:a.attributes.type,title:a.attributes.title||"",variables:b&&b.variables,calcData:null,levels:b&&b.levels,highestLevel:b&&b.highestLevel,style:{width:d.ptToPx(a.attributes.width),height:d.ptToPx(a.attributes.height),backgroundColor:a.attributes.backgroundColor},showVerticalAxis:a.attributes.showVerticalAxis,dataCollectionID:a.attributes.dataCollectionID,variableID:a.attributes.variableID};
c.variables||(c.variables=c.dataCollectionID?[c.dataCollectionID+".*"]:[c.variableID]);delete c.dataCollectionID;delete c.variableID;1<c.variables.length&&(c.variables=[c.variables[0].substr(0,c.variables[0].lastIndexOf("."))+".*"])}var c;switch(a.attributes.type){case b.STATIC:l();break;case b.ATTACHMENTS:c={type:a.attributes.type,useCircularMask:a.attributes.useCircularMask,alwaysShowCaptions:a.attributes.alwaysShowCaptions,scaleToCover:a.attributes.scaleToCover,style:{width:d.ptToPx(a.attributes.width),
height:d.ptToPx(a.attributes.height),backgroundColor:a.attributes.backgroundColor}};break;case b.AREA_DETAILS:m();break;case b.INTERESTING_FACTS:c={type:a.attributes.type,style:{width:d.ptToPx(a.attributes.width),height:d.ptToPx(a.attributes.height),backgroundColor:a.attributes.backgroundColor}};break;case b.AGE_PYRAMID:case b.TAPESTRY:case b.RELATED_VARS:case b.ONE_VAR:n();break;default:return null}return c}}});