// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/SectionParser",["dojo/_base/lang","esri/dijit/geoenrichment/utils/JsonXmlConverter","esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/RichTextJsonUtil","../../../supportClasses/DocumentOptions","../../ConversionUtil"],function(y,v,z,A,f){function B(a,c,b,d,u){if(a.spannedWidths||a.spannedHeights){var m=a.spannedWidths?a.spannedWidths.split(";").map(function(a){return f.ptToPx(a)}):
[f.ptToPx(a.width)];a=a.spannedHeights?a.spannedHeights.split(";").map(function(a){return f.ptToPx(a)}):[f.ptToPx(a.height)];for(var h=0;h<m.length;h++)for(var q=0;q<a.length;q++){var e=b[u+h],k=c[d+q],e=k.style.fields[e.field]=k.style.fields[e.field]||{};e.width=m[h];e.height=a[q]}}}var m={},C={getElement:function(a,c){var b=c.templateJson.metadata.mapImageInfosHash[a.attributes.name],d="mapImage"==a.name,m=d?null:c.processFileName(a.attributes.src),b={id:"img",fileName:m,isMapImage:d,circularMask:a.attributes.circularMask,
webMapId:b?b.webMapId:a.attributes.webMapId,defaultBasemapId:b?b.defaultBasemapId:a.attributes.defaultBasemapId,mapScale:b?b.mapScale:null,style:{top:f.ptToPx(a.attributes.top),left:f.ptToPx(a.attributes.left),width:f.ptToPx(a.attributes.width),height:f.ptToPx(a.attributes.height),angle:Number(a.attributes.angle)||0,opacity:Math.min(1,Number(0===a.attributes.opacity?0:a.attributes.opacity||1))},isLogoPlaceholder:a.attributes.isLogoPlaceholder,dynamicBehavior:a.attributes.dynamicBehavior};1>c.revisionVersion&&
(b.style.angle=f.ptToPx(b.style.angle),b.style.opacity=Math.min(1,f.ptToPx(b.style.opacity)));m&&c.putImageData(m,a.attributes.data);return b}},D={getElement:function(a,c){var b=f.parseStyleString(a.attributes.style);return{id:"hr",style:{height:f.ptToPx(a.attributes.height),backgroundColor:b.backgroundColor}}}},l={getElement:function(a,c){var b=f.pxToPt(A.getPageBox(c.templateJson.documentOptions).contentW);if(a.attributes.widths&&Number(a.attributes.width)>b){var d=f.splitTrim(a.attributes.widths,
";",!0),u=Number(a.attributes.width)-b,l=Number(d[d.length-1]);l>u&&(d[d.length-1]=l-u,a.attributes.widths=d.join(";"),a.attributes.width=b)}var h=0,q=a.attributes.widths?f.splitTrim(a.attributes.widths,";",!0).map(function(a){return{field:"field"+h++,style:{width:f.ptToPx(a)}}}):[],e=Number(a.attributes.fixedColumns)||0,k=Number(a.attributes.dynamicColumns)||0,w={},x=a.tags&&a.tags.map(function(){return{style:{fields:{}},fieldInfos:{}}});a.tags&&a.tags.forEach(function(a,b){var d=x[b];a.attributes&&
a.attributes.height&&(d.style.height=f.ptToPx(a.attributes.height));var p=0;if(k&&a.tags&&a.tags.length>e){var h=a.tags.slice(0,e),l=a.tags.slice(e,e+k),u=Math.round((q.length-h.length)/l.length);a.tags=h;for(h=0;h<u;h++)a.tags=a.tags.concat(l)}a.tags&&a.tags.forEach(function(a){function f(a){a=a.tags&&1==a.tags.length&&a.tags[0];if(!a||!a.tags)return null;"b"==a.name?l.fontWeight="bold":"i"==a.name?l.fontStyle="italic":"u"==a.name&&(l.textDecoration="underline");return"b"==a.name||"i"==a.name||"u"==
a.name?f(a)||{tag:a.tags[0],parentTag:a}:null}function h(a){v.isRichText(a)?d.fieldInfos[e]=z.createFieldInfoFromRichText(a):d[e]=v.unrichHTML(a)}if(1<=c.revisionVersion)for(;w[p+"_"+b];)p++;if(q[p]){var e=q[p].field,g=a.attributes||{},l=d.style.fields[e]={};m.parseTableCellAttributes(g,l,c);g.width&&B(g,x,q,b,p);var r=Number(g.colspan),g=Number(g.rowspan);r&&(d.columnSpans=d.columnSpans||{},d.columnSpans[e]=r);g&&(d.rowSpans=d.rowSpans||{},d.rowSpans[e]=g);if(1<r||1<g)for(var r=r||1,g=g||1,n=p;n<
p+r;n++)for(var k=b;k<b+g;k++)if(n!=p||k!=b)w[n+"_"+k]=!0;n=function(a){var b,d,c;if(a.tags&&a.tags.length)if(c=a.tags.filter(function(a){return"br"!=a.name}),(d=c[0])&&"trigger"==d.name&&c[1]&&"d"==c[1].name)b=d,d=c[1];else{var e=f(a);d=e&&e.tag||c[0];a=e&&e.parentTag||a}return{firstTag:d,trigerTag:b,parentTag:a,hasMultipleTags:c&&1<c.length}}(a);a=n.firstTag;var r=n.parentTag,g=n.trigerTag,n=n.hasMultipleTags,t;n&&!g&&(k=c.parsers.getParser("field").parseRichTextTag(r,c))&&(d.fieldInfos[e]=k,t=
!0);if(a&&!t)if(g=c.parsers.getParser("field").parseField(a,r,g,c),"number"==typeof g)d[e]=g+"",t=!0;else if(g)d.fieldInfos[e]=g,t=!0;else if("chart"==a.name)t=!0;else if("img"==a.name)t=!0;else if("text"==a.name)d[e]=a.attributes.name,t=!0;else if("a"==a.name&&a.tags&&"#text"==a.tags[0].name){if(g=a.attributes.href)d.urls=d.urls||{},d.urls[e]=g,d[e]=a.tags[0].text,t=!0}else"#text"!=a.name||n||(h(a.text),t=!0);t||h(v.getInnerHTML(r));for(p++;w[p+"_"+b];)p++}})});b={id:"table",data:{columns:q,data:x||
[]},style:{width:f.ptToPx(a.attributes.width),top:f.ptToPx(a.attributes.top),left:f.ptToPx(a.attributes.left),spaceBefore:f.ptToPx(a.attributes.spaceBefore),spaceAfter:f.ptToPx(a.attributes.spaceAfter)},attributes:{}};e&&(b.attributes.fixedColumns=e);k&&(b.attributes.dynamicColumns=k);a.attributes.fixedRows&&(b.attributes.fixedRows=Number(a.attributes.fixedRows)||0);a.attributes.dynamicRows&&(b.attributes.dynamicRows=Number(a.attributes.dynamicRows)||0);return b}};m.parseTableCellAttributes=function(a,
c,b){b=b.tableDefaultStyles;c=c||{};a.overrideStyle&&(c.overrideStyle=a.overrideStyle);a.align&&(c.horizontalAlign=a.align);a.valign&&(c.verticalAlign=f.getPropValuePtoE("valign",a.valign));a.pad&&(c.horizontalPadding=a.pad);a.width&&(c.width=a.width);a.height&&(c.height=a.height);y.mixin(c,f.parseStyleString(a.style));f.ptToPxObj(c);if(c.overrideStyle&&b){a=b.getStyle(c.overrideStyle);for(var d in a)delete c[d]}return c};m.parseSection=function(a,c){var b={type:a.attributes.type,stack:[]};b.type||
(console.log(Error("Section type is not supported!")),b.type=a.attributes.type);a.tags&&a.tags.forEach(function(a){a.attributes=a.attributes||{};"img"==a.name||"mapImage"==a.name?b.stack.push(C.getElement(a,c)):"hr"==a.name?b.stack.push(D.getElement(a,c)):"pageBreak"==a.name?b.stack.push({id:"pageBreak"}):"table"==a.name&&b.stack.push(l.getElement(a,c))});return b};m.parseTable=function(a,c){return l.getElement(a,c)};return m});