// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/supportClasses/SectionLayoutManager",["dojo/_base/declare","dojo/dom-style"],function(h,d){var g=h(null,{section:null,constructor:function(a){this.section=a},getWidth:function(){return d.get(this.section.domNode,"width")},_widthInitializedFlag:!1,setWidth:function(a,b){b=b||{};var c=this._widthInitializedFlag?d.get(this.section.domNode,"width"):0;b&&b.previousDim&&(c=b.previousDim.w,this._widthInitializedFlag=!0);d.set(this.section.domNode,
"width",a+"px");this._widthInitializedFlag=this._widthInitializedFlag||1<a;this.section.hasFixedLayout&&this.section.getTables().forEach(function(c){c.getMaxWidth()!=a&&c.setMaxWidth(a,{resizeToFitAllowedWidth:b.resizeContentToFit,preserveRightOffset:b.preserveRightOffset})});!this.section.hasFixedLayout&&this._widthInitializedFlag&&b&&b.resizeContentProportionally&&c&&a&&c!=a&&this.scaleFloatingContentProportionally({xScale:a/c,yScale:1})},getHeight:function(a){if(!this.section.hasFixedLayout)return 0;
var b=0;this.section._stackElements.forEach(function(c){switch(c.stackId){case "table":b+=c.getHeight(a);break;case "hr":b+=d.get(c,"height");break;case "pageBreak":b+=d.get(c,"height")}});return b},getResizedHeight:function(){return this.section.hasFixedLayout?this.getHeight(!0):d.get(this.section.domNode,"height")},_resizedHeightInitializedFlag:!1,_setResizedHeight:function(a,b){if(this.section.hasFixedLayout){var c=this.section.getLastTable();c&&c.setSpaceAfter(a-this.getHeight())}c=this._resizedHeightInitializedFlag?
d.get(this.section.domNode,"height"):0;b&&b.previousDim&&(c=b.previousDim.h,this._resizedHeightInitializedFlag=!0);d.set(this.section.domNode,"height",a+"px");this._resizedHeightInitializedFlag=this._resizedHeightInitializedFlag||1<a;!this.section.hasFixedLayout&&b&&b.resizeContentProportionally&&c&&a&&c!=a&&this.scaleFloatingContentProportionally({xScale:1,yScale:a/c})},setResizedHeight:function(a,b){this._setResizedHeight(a,b);if(this.section.hasFixedLayout){var c=this;this.section.getTables().forEach(function(a){a.needScaleToFitHeight()&&
c._scaleFixedTableToFitHeight(a)})}},updateHeightAfterContentChange:function(){this.section.hasFixedLayout&&this._setResizedHeight(this.getResizedHeight())},scaleFloatingContentProportionally:function(a){this.section.hasFixedLayout||1==a.xScale&&1==a.yScale||this.section._stackElements.forEach(function(b){switch(b.stackId){case "table":b.scaleProportionallyWithinParent&&b.scaleProportionallyWithinParent(a);break;case "img":b.scaleProportionallyWithinParent&&b.scaleProportionallyWithinParent(a)}})},
getFloatingContentBox:function(){var a,b,c,e;function d(d){a=Math.min(a,d.l);b=Math.min(b,d.t);c=Math.max(c,d.l+d.w);e=Math.max(e,d.t+d.h)}b=a=Infinity;e=c=0;this.section._stackElements.forEach(function(a){switch(a.stackId){case "table":d(a.getTableBox());break;case "img":d(a.getImageBox(!1))}});return{l:a,t:b,w:c-a,h:e-b}},fitContentNicely:function(a,b){a=a||{};this.section.hasFixedLayout?this._fitFixedTablesNicely(a,b):this._fitFloatingContentNicely(a,b)},_fitFixedTablesNicely:function(a,b){if("none"!=
a.fitMode){"all"==a.fitMode&&delete a.fitMode;var c=this;(b||this.section.getTables()).forEach(function(b){"table"==b.stackId&&("width"!=a.fitMode&&a.fitMode||b.resizeToFitAllowedWidth(),"height"!=a.fitMode&&a.fitMode||c._scaleFixedTableToFitHeight(b))});this.section._notifyContentChanged()}},_scaleFixedTableToFitHeight:function(a){a.resizeToFitHeight(this.section.getResizedHeight());a.setSpaceAfter(0)},_fitFloatingContentNicely:function(a,b){function c(a){d.set(a.domNode,{left:g+d.get(a.domNode,
"left")+"px",top:h+d.get(a.domNode,"top")+"px"})}if("none"!=a.fitMode){var e=this.getFloatingContentBox(),f={xScale:"height"==a.fitMode?1:(this.section.getWidth()-2-10)/e.w,yScale:"width"==a.fitMode?1:(d.get(this.section.domNode,"height")-2-10)/e.h},g=5-e.l*f.xScale,h=5-e.t*f.yScale;b=b||this.section._stackElements;b.forEach(function(a){switch(a.stackId){case "table":a.scaleProportionallyWithinParent&&a.scaleProportionallyWithinParent(f);c(a);break;case "img":a.scaleProportionallyWithinParent&&a.scaleProportionallyWithinParent(f),
c(a)}})}},getPreferredHeight:function(){var a=this.section.getInfographicWithTable();if(!a||!a.infographic.getPreferredHeight)return 0;var b=a.table.getTableBox(),c=b.t,b=this.getResizedHeight()-b.t-b.h,a=a.infographic.getPreferredHeight()||0;return c+b+a}});g.TABLE_FIT_PRETTY_OFFSET=5;return g});