// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/Section.html":'\x3cdiv class\x3d"esriGEReportPlayer_section"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"stackNode" class\x3d"section_stackNode"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"errorDiv" class\x3d"esriGEAbsoluteStretched section_errorDiv"\x3e${nls.mapLoadError}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/Section","dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/dom-class dojo/dom-style dojo/store/Memory dijit/_WidgetBase dijit/_TemplatedMixin ./_SectionQueryElementsMixin ../supportClasses/TableUtil ../grid/coreUtils/GridDataUtil ./supportClasses/SectionLayoutManager ./supportClasses/SectionDynamicSettingsBuilder ./sectionUtils/SectionJsonUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes dojo/text!../templates/Section.html dojo/i18n!../../../../../nls/jsapi".split(" "),function(p,
q,h,l,d,r,t,u,v,z,A,w,x,m,n,e,y,g){g=g.geoenrichment.dijit.ReportPlayer.ReportPlayer;return p([t,u,v],{templateString:y,nls:g,json:null,viewModel:null,themeContext:null,theme:null,previewFeatureIndex:null,initialWidth:null,hasFixedLayout:!0,isInfographicSection:!1,parentGridCell:null,infographicViewController:null,calculationStatesGroup:null,tableClass:null,tableParams:null,_stackElements:null,_defaultJson:null,_layoutManager:null,_dynamicSettingsBuilder:null,_topSpacer:null,_bottomSpacer:null,postCreate:function(){this.inherited(arguments);
this._showError(!1);this._layoutManager=new w(this);this._stackElements=[];this.initialWidth&&this.setWidth(this.initialWidth);this.infographicViewController&&this.infographicViewController.addSection(this);this.fromJson(this.json||this._defaultJson);this.viewModel.dynamicReportInfo&&(this._dynamicSettingsBuilder=new x(this))},_createStack:function(a){this._destroyStack();if(a){this._topSpacer=h.create("div",{"class":"stackNodeSpacer"},this.stackNode);var b=this;a.stack.forEach(function(a,f){switch(a.id){case "table":b._createGrid(a);
break;case "img":b._createImage(a);break;case "hr":b._createHorizontalLine(a,f);break;case "pageBreak":b._createPageBreak(a)}});this.setViewMode(this._viewMode);this._bottomSpacer=h.create("div",{"class":"stackNodeSpacer"},this.stackNode);this._updateSpacersForHorizontalLines()}},_addEmptyLine:function(){h.create("div",{"class":"stackNodeEmptyLine"},this.stackNode)},_getGridCreateParams:function(a,b){return null},_createGrid:function(a,b,c,f){var d=this;a.style=a.style||{};a.attributes=a.attributes||
{};a.data.columns=a.data.columns||[];a.data.data=a.data.data||[];var e=m.tableJsonHasInfographic(a),g=m.tableJsonHasChart(a),k=b&&(b.domNode||b);c=k?c||"after":void 0;k=k||this.stackNode;f=this.viewModel.layoutBuilder.createElement("grid",q.mixin({"class":"inSectionAdjustableGrid"+(this.tableClass?" "+this.tableClass:""),fieldCellClass:"inSectionAdjustableGridCell"+(this.tableClass?" "+this.tableClass+"Cell":""),viewModel:this.viewModel,themeContext:this.themeContext,theme:this.theme,columns:a.data.columns,
store:new r({data:a.data.data,idProperty:"id"}),allowSorting:!this.isInfographicSection&&!!this.viewModel.dynamicReportInfo,previewFeatureIndex:this.previewFeatureIndex,fixedViewMode:a.attributes.viewMode,renderCellBackground:!e&&!g,getPreviewValueFunction:this.infographicViewController&&function(){return d.infographicViewController.getValueInfo(d)},onContentLoadingStart:function(){d.onContentLoadingStart()},onContentLoadingEnd:function(){d.onContentLoadingEnd()}},this._getGridCreateParams(a,f),this.tableParams),
k);h.place(f.domNode,k,c);f.setMaxWidth(this.hasFixedLayout?this.getWidth():1E5);f.setSettings({style:{width:a.style.width,left:a.style.left,spaceBefore:a.style.spaceBefore,spaceAfter:a.style.spaceAfter},attributes:{fixedColumns:a.attributes.fixedColumns,dynamicColumns:a.attributes.dynamicColumns,fixedRows:a.attributes.fixedRows,dynamicRows:a.attributes.dynamicRows},scaleToFitWidth:a.scaleToFitWidth,scaleToFitHeight:a.scaleToFitHeight});f.stackId="table";b?this._stackElements.splice(this._stackElements.indexOf(b)+
("after"==c?1:0),0,b):this._stackElements.push(f);this.isInfographicSection||!this.viewModel.dynamicReportInfo||this.hasChart()||this.hasInfographic()||f.set("highlightRowsOnHover",!0);return f},_createImage:function(a){var b=this;a.style=a.style||{};var c,f={createMapFunc:this.viewModel.dynamicReportInfo&&this.viewModel.dynamicReportInfo.createMapFunc,getDynamicImageFunc:this.viewModel.getDynamicImageFunc.bind(this.viewModel),themeContext:this.themeContext,theme:this.theme,onInitialized:function(){c&&
c.resize()},onContentLoadingStart:function(){b.onContentLoadingStart()},onContentLoadingEnd:function(){b.onContentLoadingEnd()},onMapLoadError:function(){b._showError(!0)}};c=this._doCreateImageWithParams(f,a);c.stackId="img";this._stackElements.push(c);return c},_doCreateImageWithParams:function(a,b){return this.viewModel.layoutBuilder.createElement("image",{node:this.stackNode,relativeParent:this.domNode,json:b,creationParams:a})},_createHorizontalLine:function(a,b){a.style=a.style||{};var c=h.create("div",
{"class":"templateHorizontalLine"},this.stackNode);0==b?(l.add(c,"templateHorizontalLineTop"),this._stackElements.unshift(c),c._isTopLine=!0):(l.add(c,"templateHorizontalLineBottom"),this._stackElements.push(c),c._isTopLine=!1);c.stackId="hr";a.style.backgroundColor&&d.set(c,"backgroundColor",a.style.backgroundColor);a.style.height&&d.set(c,"height",a.style.height+"px")},_updateSpacersForHorizontalLines:function(){var a=this._queryElementsById("hr");d.set(this._topSpacer,"height","0px");d.set(this._bottomSpacer,
"height","0px");var b=this;a.forEach(function(a){d.set(a._isTopLine?b._topSpacer:b._bottomSpacer,"height",d.get(a,"height")+"px")})},_createPageBreak:function(a){a=h.create("div",{"class":"esriGEReportPlayer_pageBreak"},this.stackNode);a.stackId="pageBreak";h.create("div",{"class":"pageBreakLine dijitInline"},a);h.create("div",{"class":"pageBreakLabel dijitInline",innerHTML:g.pageBreak},a);h.create("div",{"class":"pageBreakLine dijitInline"},a);this._stackElements.push(a)},_destroyStack:function(){for(;this._stackElements.length;)this._removeElement(this._stackElements[0]);
this.stackNode&&h.empty(this.stackNode);this._addEmptyLine()},removeElement:function(a){a&&this._removeElement(a)},_removeElement:function(a){a.destroy?a.destroy():h.destroy(a);this._stackElements.splice(this._stackElements.indexOf(a),1);"hr"==a.stackId&&this._updateSpacersForHorizontalLines()},getWidth:function(){return this._layoutManager.getWidth()},setWidth:function(a,b){this._layoutManager.setWidth(a,b)},getHeight:function(a){return this._layoutManager.getHeight(a)},getResizedHeight:function(){return this._layoutManager.getResizedHeight()},
setResizedHeight:function(a,b){this._layoutManager.setResizedHeight(a,b)},getPreferredHeight:function(){return this._layoutManager.getPreferredHeight()},collapseContent:function(){var a=this.getInfographicWithTable();a&&a.infographic.collapseContent()},calculateFloatingContentBox:function(){return this._layoutManager.getFloatingContentBox()},scaleFloatingContentProportionally:function(a){this._layoutManager.scaleFloatingContentProportionally(a)},fitContentNicely:function(a,b){this._layoutManager.fitContentNicely(a,
b)},_getFirstCellContent:function(){var a=this.getFirstTable();return(a=a&&a.getFirstCell())&&a.content},sortChart:function(a){var b=this._getFirstCellContent();b&&b.sortChart(a)},chartToTable:function(){var a=this._getFirstCellContent();a&&a.chartToTable()},tableToChart:function(){var a=this._getFirstCellContent();a&&a.tableToChart()},setChartCalculationState:function(a){this.onCalculationStateChanged(a)},onCalculationStateChanged:function(a){},getSettings:function(){var a=this._queryElementsById("hr"),
b=a[0]&&a[0]._isTopLine?a[0]:null,a=a.filter(function(a){return!a._isTopLine})[0],c={type:this._sectionType,hasTopLine:!!b,hasBottomLine:!!a};b&&(c.topLineHeight=d.get(b,"height"),c.topLineColor=d.get(b,"backgroundColor"));a&&(c.bottomLineHeight=d.get(a,"height"),c.bottomLineColor=d.get(a,"backgroundColor"));return c},setSettings:function(a){var b=this;this._queryElementsById("hr").map(function(a){b._removeElement(a)});a.hasTopLine&&this._createHorizontalLine({style:{height:a.topLineHeight,backgroundColor:a.topLineColor}},
0);a.hasBottomLine&&this._createHorizontalLine({style:{height:a.bottomLineHeight,backgroundColor:a.bottomLineColor}})},_notifyContentChanged:function(){this._layoutManager.updateHeightAfterContentChange()},_viewMode:null,_specificViewMode:null,setViewMode:function(a,b){var c=this;this._viewMode=a;void 0!==b&&(this._specificViewMode=b);this._stackElements.forEach(function(b){b.setViewMode&&b.setViewMode(a,c._specificViewMode)})},notifyShown:function(){this._stackElements.forEach(function(a){a.notifyShown&&
a.notifyShown()})},_sectionType:null,getSectionType:function(){return this._sectionType},isEmpty:function(){return!1},isDataSection:function(){var a=this.getSectionType();return!this.hasPageBreak()&&this.hasNonEmptyTables()&&(a==e.DETAILS||a==e.DETAILS_HEADER||a==e.GROUP)},isPageHeader:function(){return this.getSectionType()==e.PAGE_HEADER},isPageFooter:function(){return this.getSectionType()==e.PAGE_FOOTER},getSectionName:function(){if(this.hasPageBreak())return"";switch(this._sectionType){case e.PAGE_HEADER:return g.pageHeader;
case e.DETAILS_HEADER:return g.detailsHeader;case e.DETAILS:return g.details;case e.GROUP:return g.group;case e.REPORT_FOOTER:return g.reportFooter;case e.PAGE_FOOTER:return g.pageFooter}return""},getVisualState:function(){return{stackElements:this._stackElements.map(function(a){return a.getVisualState&&a.getVisualState()})}},setVisualState:function(a){a&&a.stackElements&&a.stackElements.length==this._stackElements.length&&(this._stackElements.forEach(function(b,c){b.setVisualState&&b.setVisualState(a.stackElements[c])}),
this._dynamicSettingsBuilder.setVisualState(a))},updateContentFromJson:function(a){this.fromJson(a);this._notifyContentChanged()},fromJson:function(a){this._showError(!1);this._sectionType=a.type;this.previewFeatureIndex=a.previewFeatureIndex;this._createStack(a)},toJson:function(){var a={type:this._sectionType,stack:[]};this._stackElements.forEach(function(b){var c;switch(b.stackId){case "table":case "img":c=b.toJson();break;case "hr":c={id:"hr",style:{height:d.get(b,"height"),backgroundColor:d.get(b,
"backgroundColor")}};break;case "pageBreak":c={id:"pageBreak"}}c&&a.stack.push(c)});return a},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},_showError:function(a){n[a?"show":"hide"](this.errorDiv);n[a?"hide":"show"](this.stackNode)},destroy:function(){this._destroyStack();this.inherited(arguments)}})});