// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/plots/Donut","dojo/_base/lang dojo/_base/declare dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx dojox/gfx/matrix dojox/lang/functional dojox/lang/utils dojo/has".split(" "),function(A,I,J,K,T,L,O,u,y,P){return I([J,K],{enableHole:!0,enableGap:!0,defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelStyle:"outside",htmlLabels:!0,radGrad:"native",fanSize:5,startAngle:0},optionalParams:{radius:0,
omitLabels:!1,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},constructor:function(h,a){this.opt=A.clone(this.defaultParams);y.updateWithObject(this.opt,a);y.updateWithPattern(this.opt,a,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(h){return this},addSeries:function(h){this.run=h;return this},getSeriesStats:function(){return A.delegate(T.defaultStats)},
getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(h,a){if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var l=this.group,f=this.chart.theme;if(!this.run||!this.run.data.length)return this;var d=(h.width-a.l-a.r)/2,b=(h.height-a.t-a.b)/2,c=Math.min(d,b),g="font"in this.opt?this.opt.font:f.series.font,k,z=O._degToRad(this.opt.startAngle),m=z,n,v,x,r,q,A=this.events(),
B=this.run.data.map(function(a,c){"number"!=typeof a&&a.hidden&&(this.runFilter.push(c),a.hidden=!1);return this.runFilter.some(function(a){return a==c})?"number"==typeof a?0:{y:0,text:a.text}:a},this);this.dyn=[];"radius"in this.opt&&(q=c=this.opt.radius);var e={cx:a.l+d,cy:a.t+b,r:c},C;n=u.map(B,"x ? Math.max(x.y, 0) : 0");if(u.every(n,"\x3c\x3d 0"))return l.createCircle(e).setStroke(f.series.stroke),this.dyn=n.map(function(){return{}}),this;v=u.map(n,"/this",u.foldl(n,"+",0));this.opt.labels&&
(x=v.map(function(a,c){if(0>a)return"";var e=B[c];return"text"in e?e.text:this._getLabel(100*a)+"%"},this));var F=u.map(B,function(a,c){var e=[this.opt,this.run];null!==a&&"number"!=typeof a&&e.push(a);this.opt.styleFunc&&e.push(this.opt.styleFunc(a));return f.next("slice",e,!0)},this),D=this.enableHole?(f.series.donutHolePercent||0)/100:0,w=this.enableGap?(f.series.donutGap||0)/360:0;if(this.opt.labels)switch(r=k=0,x.forEach(function(a,c){var e=L._base._getTextBox(a,{font:F[c].series.font});k=Math.max(k,
e.h);r=Math.max(r,e.w)}),this.opt.labelStyle){case "outside":n=c;c=Math.min(d-r,b-k)-5;q=c+r/2;c=Math.max(c,n/2);break;case "inside":q=Math.abs((c-c*D)/2+c*D+(c-r/2))/2;break;case "columns":q=c=Math.min(d-r-20,b-2*k)}var M=Array(v.length);v.some(function(f,d){if(0>f)return!1;var b=B[d],g=F[d],p;if(0==f)return this.dyn.push({fill:g.series.fill,stroke:g.series.stroke}),!1;if(1<=f){p=this._plotFill(g.series.fill,h,a);var t;if(D){var k=c-c*D;C=c-k/2;t=l.createCircle({cx:e.cx,cy:e.cy,r:C}).setStroke({color:p,
width:k})}else C=c,t=l.createCircle(e).setFill(p).setStroke(g.series.stroke);this.dyn.push({fill:p,stroke:g.series.stroke});A&&(b={element:"slice",index:d,run:this.run,shape:t,x:d,y:"number"==typeof b?b:b.y,cx:e.cx,cy:e.cy,cr:c},this._connectEvents(b),M[d]=b);return!1}k=m+2*f*Math.PI-w;d+1==v.length&&(k=z+2*Math.PI-w);C=p=c*D;t=k-m;var n=e.cx+c*Math.cos(m),q=e.cy+c*Math.sin(m),r=e.cx+c*Math.cos(k),R=e.cy+c*Math.sin(k);O._degToRad(this.opt.fanSize);if(p){var Q=e.cx+p*Math.cos(m),u=e.cy+p*Math.sin(m),
x=e.cx+p*Math.cos(k),y=e.cy+p*Math.sin(k);t=l.createPath().moveTo(Q,u).lineTo(n,q).arcTo(c,c,0,t>Math.PI,!0,r,R).lineTo(x,y).arcTo(p,p,0,t>Math.PI,!1,Q,u).closePath().setStroke(g.series.stroke)}else t=l.createPath().moveTo(e.cx,e.cy).lineTo(n,q).arcTo(c,c,0,t>Math.PI,!0,r,R).lineTo(e.cx,e.cy).closePath().setStroke(g.series.stroke);p=g.series.fill;t.setFill(p);this.dyn.push({fill:p,stroke:g.series.stroke});A&&(b={element:"slice",index:d,run:this.run,shape:t,x:d,y:"number"==typeof b?b:b.y,cx:e.cx,cy:e.cy,
cr:c},this._connectEvents(b),M[d]=b);m=k+w;return!1},this);if(this.opt.labels){var y=P("dojo-bidi")&&this.chart.isRightToLeft();if("outside"==this.opt.labelStyle||"inside"==this.opt.labelStyle)m=z,v.some(function(a,b){if(0>=a)return!1;var d=F[b];if(1<=a)return this.renderLabel(l,e.cx,e.cy+k/2,x[b],d,!0),!0;var c=m+2*a*Math.PI-w;b+1==v.length&&(c=z+2*Math.PI-w);if(this.opt.omitLabels&&.001>c-m)return!1;var f=(m+c)/2,g=q;"outside"===this.opt.labelStyle&&(g=1.15*q+(k-r/2-.15*q)*Math.abs(Math.sin(f)));
var n=e.cx+g*Math.cos(f);this.renderLabel(l,y?h.width-n:n,e.cy+g*Math.sin(f)+k/2,x[b],d,!0);m=c+w;return!1},this);else if("columns"==this.opt.labelStyle){var m=z,I=this.opt.omitLabels,G=[];v.forEach(function(a,b){var c=m+2*a*Math.PI-w;b+1==v.length&&(c=z+2*Math.PI-w);var d=(m+c)/2;G.push({angle:d,left:0>Math.cos(d),theme:F[b],index:b,omit:I?.001>c-m:!1});m=c+w});b=L._base._getTextBox("a",{font:g}).h;this._getProperLabelRadius(G,b,1.1*q);for(b=0;b<G.length;b++)if(g=G[b],!g.omit){var E=e.cx-d,H=e.cx+
d;n=L._base._getTextBox(x[b],{font:g.theme.series.font}).w;var J=e.cx+g.labelR*Math.cos(g.angle),N=e.cy+g.labelR*Math.sin(g.angle),H=g.left?E+n:H-n,E=g.left?E:H,S=l.createPath().moveTo(e.cx+q*Math.cos(g.angle),e.cy+q*Math.sin(g.angle));S.lineTo(J,N);S.lineTo(H,N).setStroke(g.theme.series.labelWiring);this.renderLabel(l,y?h.width-n-E:E,N,x[b],g.theme,!1,"left")}}}var K=0;this._eventSeries[this.run.name]=u.map(B,function(a){return 0>=a?null:M[K++]});P("dojo-bidi")&&this._checkOrientation(this.group,
h,a);this._lastRenderResults={labels:this.opt.labels,radiusInner:C,radiusOuter:c};return this},_getProperLabelRadius:function(h,a,l){var f,d,b=1,c=1;if(1==h.length)h[0].labelR=l;else{for(var g=0;g<h.length;g++){var k=Math.abs(Math.sin(h[g].angle));h[g].left?b>=k&&(b=k,f=h[g]):c>=k&&(c=k,d=h[g])}f.labelR=d.labelR=l;this._calculateLabelR(f,h,a);this._calculateLabelR(d,h,a)}},_calculateLabelR:function(h,a,l){for(var f=h.index,d=a.length,b=h.labelR;!(a[f%d].left^a[(f+1)%d].left);)a[(f+1)%d].omit||(b=
(Math.sin(a[f%d].angle)*b+(a[f%d].left?-l:l))/Math.sin(a[(f+1)%d].angle),b=b<h.labelR?h.labelR:b,a[(f+1)%d].labelR=b),f++;f=h.index;for(d=0==f?d-1:f-1;!(a[f].left^a[d].left);)a[d].omit||(b=(Math.sin(a[f].angle)*b+(a[f].left?l:-l))/Math.sin(a[d].angle),b=b<h.labelR?h.labelR:b,a[d].labelR=b),f--,d--,f=0>f?f+a.length:f,d=0>d?d+a.length:d}})});