// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/plots/PictureClusteredBars","dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/has dojox/charting/plot2d/CartesianBase dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx/fx dojox/gfx dojox/lang/utils dojox/lang/functional dojox/lang/functional/reversed ./labelsRendering/_BarsLabelRenderingFix ./pictureUtil/Converter".split(" "),function(g,x,B,D,E,F,n,G,p,v,H,I,J,C){var K=I.lambda("item.purgeGroup()");
return B("dojox.charting.plot2d.Bars",[E,F,J],{defaultParams:{gap:0,animate:null,enableCache:!1},optionalParams:{minBarSize:1,maxBarSize:1,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:""},constructor:function(a,b){this.opt=g.clone(g.mixin(this.opt,this.defaultParams));v.updateWithObject(this.opt,b);v.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate;this.renderingOptions={"shape-rendering":"crispEdges"}},getSeriesStats:function(){var a=
n.collectSimpleStats(this.series),b;a.hmin-=.5;a.hmax+=.5;b=a.hmin;a.hmin=a.vmin;a.vmin=b;b=a.hmax;a.hmax=a.vmax;a.vmax=b;return a},createRect:function(a,b,d){var e;this.opt.enableCache&&0<a._rectFreePool.length?(e=a._rectFreePool.pop(),e.setShape(d),b.add(e)):e=b.createRect(d);this.opt.enableCache&&a._rectUsePool.push(e);return e},render:function(a,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,b);this.dirty=this.isDirty();this.resetEvents();var d;this.dirty&&(x.forEach(this.series,
K),this._eventSeries={},this.cleanGroup(),d=this.getGroup(),H.forEachRev(this.series,function(a){a.cleanGroup(d)}));var e=this.chart.theme,h=this._hScaler.scaler.getTransformerFromModel(this._hScaler),L=this._vScaler.scaler.getTransformerFromModel(this._vScaler),m=Math.max(0,this._hScaler.bounds.lower),q=h(m),g=this.events(),y=this.getBarProperties(),p=this.series.length;x.forEach(this.series,function(a){a.hidden&&p--});for(var n=p,z=this.series.length-1;0<=z;--z){var c=this.series[z];if(this.dirty||
c.dirty){c.cleanGroup();this.opt.enableCache&&(c._rectFreePool=(c._rectFreePool?c._rectFreePool:[]).concat(c._rectUsePool?c._rectUsePool:[]),c._rectUsePool=[]);var A=e.next("bar",[this.opt,c]);if(c.hidden)c.dyn.fill=A.series.fill,c.dyn.stroke=A.series.stroke;else{n--;var v=Array(c.data.length);d=c.group;for(var w=x.some(c.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),B=w?Math.min(c.data.length,Math.ceil(this._vScaler.bounds.to)):c.data.length,f=w?Math.max(0,Math.floor(this._vScaler.bounds.from-
1)):0;f<B;++f){var r=c.data[f];if(null!=r){var k=this.getValue(r,f,z,w),l=h(k.y),t=Math.abs(l-q),u;this.opt.styleFunc||"number"!=typeof r?(u="number"!=typeof r?[r]:[],this.opt.styleFunc&&u.push(this.opt.styleFunc(r)),u=e.addMixin(A,"bar",u,!0)):u=e.post(A,"bar");0<=t&&1<=y.height&&(l={x:b.l+(k.y<m?l:q),y:a.height-b.b-L(k.x+1.5)+y.gap+y.thickness*(p-n-1),width:t,height:y.height},t=this._drawBarPictures(d,u.series.chartIcons[f]||C.DEFAULT_SHAPE,l),g&&(t={element:"bar",index:f,run:c,shape:t,cx:k.y,cy:k.x+
1.5,x:w?f:c.data[f].x,y:w?c.data[f]:c.data[f].y},this._connectEvents(t),v[f]=t),!isNaN(k.py)&&k.py>m&&(l.x+=h(k.py),l.width-=h(k.py)),this.createLabel(d,r,l,u))}}this._eventSeries[c.name]=v;c.dirty=!1}}else e.skip(),this._reconnectEvents(c.name)}this.dirty=!1;D("dojo-bidi")&&this._checkOrientation(this.group,a,b);return this},_drawBarPictures:function(a,b,d){a=a.createGroup();b=b.shapeJson;for(var e=d.height/b.style.height,h=b.style.width*e,g=Math.ceil(d.width/h),m=0;m<g;m++){var q=a.createGroup(),
n=C.shapeJsonToGFXJson(b);p.utils.deserialize(q,n);m===g-1&&q.setClip({x:0,y:0,width:(h-(g*h-d.width))/e,height:b.style.height});q.applyTransform(p.matrix.translate(d.x+m*h,d.y));q.applyTransform(p.matrix.scale(e))}return a},getValue:function(a,b,d,e){e?(d="number"==typeof a?a:a.y,a=b):(d=a.y,a=a.x-1);return{y:d,x:a}},getBarProperties:function(){var a=this.series.length;x.forEach(this.series,function(b){b.hidden&&a--});var b=n.calculateBarSize(this._vScaler.bounds.scale,this.opt,a);return{gap:b.gap,
height:b.size,thickness:b.size}},_animateBar:function(a,b,d){0==d&&(d=1);G.animateTransform(g.delegate({shape:a,duration:1200,transform:[{name:"translate",start:[b-b/d,0],end:[0,0]},{name:"scale",start:[1/d,1],end:[1,1]},{name:"original"}]},this.animate)).play()}})});