// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/plots/PictureClusteredColumns","dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/has dojox/charting/plot2d/CartesianBase dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/lang/functional dojox/lang/functional/reversed dojox/lang/utils dojox/gfx/fx dojox/gfx ./labelsRendering/_BarsLabelRenderingFix ./pictureUtil/Converter".split(" "),function(f,w,D,E,F,G,u,H,I,x,J,l,K,C){var L=I.lambda("item.purgeGroup()");
return D("dojox.charting.plot2d.Columns",[F,G,K],{defaultParams:{gap:0,animate:null,enableCache:!1},optionalParams:{minBarSize:1,maxBarSize:1,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:""},constructor:function(a,b){this.opt=f.clone(f.mixin(this.opt,this.defaultParams));x.updateWithObject(this.opt,b);x.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate;this.renderingOptions={"shape-rendering":"crispEdges"}},getSeriesStats:function(){var a=
u.collectSimpleStats(this.series);a.hmin-=.5;a.hmax+=.5;return a},createRect:function(a,b,c){var e;this.opt.enableCache&&0<a._rectFreePool.length?(e=a._rectFreePool.pop(),e.setShape(c),b.add(e)):e=b.createRect(c);this.opt.enableCache&&a._rectUsePool.push(e);return e},render:function(a,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,b);this.resetEvents();this.dirty=this.isDirty();var c;this.dirty&&(w.forEach(this.series,L),this._eventSeries={},this.cleanGroup(),c=this.getGroup(),H.forEachRev(this.series,
function(a){a.cleanGroup(c)}));var e=this.chart.theme,M=this._hScaler.scaler.getTransformerFromModel(this._hScaler),m=this._vScaler.scaler.getTransformerFromModel(this._vScaler),h=Math.max(0,this._vScaler.bounds.lower),n=m(h),r=this.events(),y=this.getBarProperties(),f=this.series.length;w.forEach(this.series,function(a){a.hidden&&f--});for(var z=this.series.length-1;0<=z;--z){var d=this.series[z];if(this.dirty||d.dirty){d.cleanGroup();this.opt.enableCache&&(d._rectFreePool=(d._rectFreePool?d._rectFreePool:
[]).concat(d._rectUsePool?d._rectUsePool:[]),d._rectUsePool=[]);var l=e.next("column",[this.opt,d]),u=Array(d.data.length);if(d.hidden)d.dyn.fill=l.series.fill;else{f--;c=d.group;for(var v=w.some(d.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),x=v?Math.min(d.data.length,Math.ceil(this._hScaler.bounds.to)):d.data.length,g=v?Math.max(0,Math.floor(this._hScaler.bounds.from-1)):0;g<x;++g){var p=d.data[g];if(null!=p){var k=this.getValue(p,g,z,v),B=m(k.y),t=Math.abs(B-n),q;this.opt.styleFunc||
"number"!=typeof p?(q="number"!=typeof p?[p]:[],this.opt.styleFunc&&q.push(this.opt.styleFunc(p)),q=e.addMixin(l,"column",q,!0)):q=e.post(l,"column");if(1<=y.width&&0<=t){var t={x:b.l+M(k.x+.5)+y.gap+y.thickness*f,y:a.height-b.b-(k.y>h?B:n),width:y.width,height:t},A=this._drawColumnPictures(c,q.series.chartIcons[g]||C.DEFAULT_SHAPE,t);r&&(A={element:"column",index:g,run:d,shape:A,cx:k.x+.5,cy:k.y,x:v?g:d.data[g].x,y:v?d.data[g]:d.data[g].y},this._connectEvents(A),u[g]=A);!isNaN(k.py)&&k.py>h&&(t.height=
B-m(k.py));this.createLabel(c,p,t,q)}}}this._eventSeries[d.name]=u;d.dirty=!1}}else e.skip(),this._reconnectEvents(d.name)}this.dirty=!1;E("dojo-bidi")&&this._checkOrientation(this.group,a,b);return this},_drawColumnPictures:function(a,b,c){a=a.createGroup();b=b.shapeJson;for(var e=c.width/b.style.width,f=b.style.height*e,m=Math.ceil(c.height/f),h=0;h<m;h++){var n=a.createGroup(),r=C.shapeJsonToGFXJson(b);l.utils.deserialize(n,r);h===m-1&&(r=(f-(m*f-c.height))/e,n.setClip({x:0,y:b.style.height-r,
width:b.style.width,height:r}));n.applyTransform(l.matrix.translate(c.x,c.y+c.height-(h+1)*f));n.applyTransform(l.matrix.scale(e))}return a},getValue:function(a,b,c,e){e?(c="number"==typeof a?a:a.y,a=b):(c=a.y,a=a.x-1);return{x:a,y:c}},getBarProperties:function(){var a=this.series.length;w.forEach(this.series,function(b){b.hidden&&a--});var b=u.calculateBarSize(this._hScaler.bounds.scale,this.opt,a);return{gap:b.gap,width:b.size,thickness:b.size,clusterSize:a}},_animateColumn:function(a,b,c){0==c&&
(c=1);J.animateTransform(f.delegate({shape:a,duration:1200,transform:[{name:"translate",start:[0,b-b/c],end:[0,0]},{name:"scale",start:[1,1/c],end:[1,1]},{name:"original"}]},this.animate)).play()}})});