// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.22/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/plots/Ring","dojo/_base/lang dojo/_base/declare dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx dojox/gfx/matrix dojox/lang/functional dojox/lang/utils dojo/has".split(" "),function(t,z,A,B,C,D,L,l,u,J){var w=z([A,B],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:20,labelStyle:"default",htmlLabels:!0,radGrad:"native",fanSize:5,startAngle:0},optionalParams:{radius:0,
omitLabels:!1,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},_lastRenderResults:null,constructor:function(e,g){this.opt=t.clone(this.defaultParams);u.updateWithObject(this.opt,g);u.updateWithPattern(this.opt,g,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(e){return this},addSeries:function(e){this.run=e;return this},
getSeriesStats:function(){return t.delegate(C.defaultStats)},getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(e,g){function r(a){return D._base._getTextBox(a,{font:h.series.font}).w}if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var m=this.group,h=this.chart.theme;if(!this.run||!this.run.data.length)return this;var d=(e.width-g.l-g.r)/2,n=(e.height-g.t-
g.b)/2,b=Math.min(d,n),t="font"in this.opt?this.opt.font:h.series.font,E=L._degToRad(90),f,u=this.events(),v=this.run.data.map(function(a,c){"number"!=typeof a&&a.hidden&&(this.runFilter.push(c),a.hidden=!1);return this.runFilter.some(function(a){return a==c})?"number"==typeof a?0:{y:0,text:a.text}:a},this);this.dyn=[];"radius"in this.opt&&(b=this.opt.radius);var c={cx:g.l+d,cy:g.t+n,r:b},d=l.map(v,"x ? Math.max(x.y, 0) : 0");if(l.every(d,"\x3c\x3d 0"))return m.createCircle(c).setStroke(h.series.stroke),
this.dyn=d.map(function(){return{}}),this;d=l.map(d,"/this",l.foldl(d,"+",0));if(this.opt.labels)if(f=d.map(function(a,c){if(0>a)return"";var b=v[c];return"text"in b?b.text:this._getLabel(100*a)+"%"},this),f[0]&&-1!=f[0].indexOf(w.LABEL_SEPARATOR)){var F=0;f.forEach(function(a){a=a.split(w.LABEL_SEPARATOR)[0];a=r(a);F=Math.max(F,a)});var z=r("\x26nbsp;");f=f.map(function(a){a=a.split(w.LABEL_SEPARATOR);for(var c=Math.round((F-r(a[0]))/z),b="",e=0;e<c+4;e++)b+="\x26nbsp;";return"\x3cdiv\x3e\x3cspan\x3e"+
a[0]+"\x3c/span\x3e"+b+"\x3cspan\x3e"+a[1]+"\x3c/span\x3e\x3c/div\x3e"})}else f=f.map(function(a){return"\x3cdiv\x3e"+a+"\x3c/div\x3e"});var A=l.map(v,function(a,c){var b=[this.opt,this.run];null!==a&&"number"!=typeof a&&b.push(a);this.opt.styleFunc&&b.push(this.opt.styleFunc(a));return h.next("slice",b,!0)},this),x=0;if(this.opt.labels){f.forEach(function(a){x=Math.max(x,r(a))});var p=c.cx+b+x+g.r-e.width;0<p&&(n=c.cx-b,n>p?c.cx-=p:(p=(p-n)/2,c.cx-=n+p,b-=p))}c.cx-=c.cx-b-(e.width-(2*b+x))/2;var G=
Array(d.length),y=Math.min(b/10,.5*b/d.length),K=b,b=b-y/2,H=[],I=[];d.some(function(a,d){if(0>a)return!1;var k=v[d],f=A[d],q;if(0==a)return this.dyn.push({fill:f.series.fill,stroke:f.series.stroke}),!1;if(1<=a){q=this._plotFill(f.series.fill,e,g);var h={cx:c.cx,cy:c.cy,r:b};I.push(h);h=m.createCircle(h).setStroke({color:q,width:y});this.dyn.push({fill:q,stroke:f.series.stroke});u&&(k={element:"slice",index:d,run:this.run,shape:h,x:d,y:"number"==typeof k?k:k.y,cx:c.cx,cy:c.cy,cr:b},this._connectEvents(k),
G[d]=k);H.push({x:c.cx,y:c.cy+b});return!1}q=E+2*a*Math.PI;var h=c.cx+b*Math.cos(E),p=c.cy+b*Math.sin(E),l=c.cx+b*Math.cos(q),r=c.cy+b*Math.sin(q);q=f.series.fill;var n={cx:c.cx,cy:c.cy,r:b};I.push(n);m.createCircle(n).setStroke({color:f.series.ringBackgroundColor||"#DDDDDD",width:y});h=m.createPath().moveTo(h,p).arcTo(b,b,0,.5<a,!0,l,r).setStroke({color:q,width:y});this.dyn.push({fill:q,stroke:f.series.stroke});u&&(k={element:"slice",index:d,run:this.run,shape:h,x:d,y:"number"==typeof k?k:k.y,cx:c.cx,
cy:c.cy,cr:b},this._connectEvents(k),G[d]=k);H.push({x:c.cx,y:c.cy+b});b-=y+3;return!1},this);if(this.opt.labels){J("dojo-bidi")&&this.chart.isRightToLeft();var B=D._base._getTextBox("a",{font:t}).h;H.forEach(function(a,b){m.createPath().moveTo(a.x-5,a.y).lineTo(a.x+K-5,a.y).setStroke(h.series.labelWiring);this.renderLabel(m,a.x+K,a.y+B/3,f[b],h,!1,"left")},this);h.series.show100PercentLabel&&this._show100PercentLabel(h,b,m,c)}var C=0;this._eventSeries[this.run.name]=l.map(v,function(a){return 0>=
a?null:G[C++]});J("dojo-bidi")&&this._checkOrientation(this.group,e,g);this._lastRenderResults={labels:this.opt.labels,slicePies:I,maxLabelWidth:x};return this},_show100PercentLabel:function(e,g,l,m){e={series:t.mixin({},e.series)};e.series.font=e.series.font.replace(/\s\w*px/," "+Math.min(50,.6*g)+"px");g=D._base._getTextBox("100%",{font:e.series.font});this.renderLabel(l,m.cx-g.w/2,m.cy+g.h/3,"100%",e,!1,"left").style.opacity="0.5"}});w.LABEL_SEPARATOR="\x26nbsp;";return w});